#!/usr/bin/env python3
"""Verify test-vectors/encryption.json against spec/encryption.md.

Stdlib-only checks (always run):
  - HKDF-SHA256 key derivation reproduces the pinned key fingerprint
    (ground-truth continuity with the published vectors and with
    tools/interop-reference.py, which pins the same fingerprint).
  - Every vector's `aad_hex` reconstructs byte-for-byte from its fields
    (tenant_id, cache_key, format, compressed, optional original_type),
    including the frozen ASCII boolean tokens `True` / `False`.
  - Keyring vectors: entry derivation, metadata, AAD, and fingerprint selection
    pinned to the HKDF-derived per-tenant encryption key, never the master key.
  - The vector count never drops below the frozen floor — vectors are
    ground truth and may be added, never removed.

Seal check (runs when `cryptography` is installed; `--require-seal` makes
its absence a hard failure — CI passes the flag in the optional-deps step):
  - Every vector's `ciphertext_hex` decrypts under the derived key + AAD to
    `plaintext_hex`. (No re-seal comparison: AES-GCM is deterministic per
    (key, nonce, aad, plaintext), so a successful decrypt + plaintext match
    already proves the seal.)
  - Keyring vectors decrypt under [k2, k1] at the declared entry, and the k1 entry
    is rejected under [k2] alone (sequential-attempt path).

Exit status is non-zero on any mismatch. Vectors are frozen ground truth and
are never regenerated by this tool.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import sys
from pathlib import Path

VECTORS_PATH = Path(__file__).resolve().parent.parent / "test-vectors" / "encryption.json"

# Frozen protocol constants (spec/encryption.md, "compressed tokens").
TOKEN_TRUE = b"True"
TOKEN_FALSE = b"False"

# Vectors are append-only ground truth: published names may never disappear.
# Removal or rename (even with a same-count replacement) must go red in CI.
FROZEN_VECTOR_NAMES = frozenset(
    {
        "basic_bytes",
        "special_cache_key",
        "compressed_basic",
        "arrow_uncompressed",
        "arrow_compressed",
        "orjson_uncompressed",
        "original_type_numpy",
    }
)

# format registry per spec/encryption.md — vectors must not invent tokens.
FORMAT_REGISTRY = frozenset({"msgpack", "orjson", "arrow"})

# Keyring conformance vectors: frozen name -> the entry that sealed it. The
# conformance keyring is current=k2 with decrypt-only k1 (KEYRING_ORDER).
FROZEN_KEYRING_VECTORS = {"encrypted_with_k1": "k1", "encrypted_with_k2": "k2"}
FROZEN_KEYRING_VECTOR_NAMES = frozenset(FROZEN_KEYRING_VECTORS)
KEYRING_ORDER = ("k2", "k1")


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int = 32) -> bytes:
    """RFC 5869 HKDF-Extract + Expand with SHA-256."""
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
        i += 1
    return okm[:length]


def construct_salt(domain: str, tenant_salt: str) -> bytes:
    d, t = domain.encode("utf-8"), tenant_salt.encode("utf-8")
    return b"cachekit_v1_" + bytes([len(d)]) + d + len(t).to_bytes(2, "big") + t


def derive_encryption_key(master_key: bytes, tenant_id: str) -> bytes:
    return hkdf_sha256(master_key, construct_salt("encryption", tenant_id), b"encryption")


def key_fingerprint(key: bytes) -> str:
    return hashlib.sha256(b"key_fingerprint_v1" + key).digest()[:16].hex()


def decrypt_with_keyring(keys: list[bytes], ciphertext: bytes, aad: bytes) -> tuple[int, bytes] | None:
    """Try each key once, in keyring order, with identical authenticated data."""
    from cryptography.exceptions import InvalidTag  # noqa: PLC0415
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: PLC0415

    nonce, sealed = ciphertext[:12], ciphertext[12:]
    for index, key in enumerate(keys):
        try:
            return index, AESGCM(key).decrypt(nonce, sealed, aad)
        except InvalidTag:
            continue
    return None


def aad_v3(tenant_id: str, cache_key: str, *, fmt: str, compressed: bool, original_type: str | None = None) -> bytes:
    """AAD v0x03 per spec/encryption.md — 4-byte BE length-prefixed components.

    Unlike interop-reference.py's aad_v3, this supports the optional fifth
    original_type component. The interop copy omits it DELIBERATELY — interop
    AAD is exactly four components; do not "harmonize" the two.
    """
    components = [
        tenant_id.encode("utf-8"),
        cache_key.encode("utf-8"),
        fmt.encode("utf-8"),
        TOKEN_TRUE if compressed else TOKEN_FALSE,
    ]
    if original_type is not None:
        components.append(original_type.encode("utf-8"))
    aad = bytearray([0x03])
    for component in components:
        aad += len(component).to_bytes(4, "big") + component
    return bytes(aad)


def verify_keyring(keyring: dict | None, *, seal: bool) -> int:
    """Return the number of failed keyring checks (spec/encryption.md § Key Rotation).

    Entry derivation, metadata, AAD reconstruction and fingerprint selection are
    stdlib and always run; only the decrypt attempts need `cryptography` (`seal`).
    """
    if keyring is None:
        print("FAIL keyring vectors missing")
        return 1
    failures = 0

    entries = keyring.get("entries", [])
    ids = [entry.get("id") for entry in entries]
    if len(set(ids)) != len(ids) or not set(KEYRING_ORDER) <= set(ids):
        print(f"FAIL keyring entries must have unique ids including {sorted(KEYRING_ORDER)}; got {ids}")
        return failures + 1
    derived_keys: dict[str, bytes] = {}
    for entry in entries:
        derived = derive_encryption_key(bytes.fromhex(entry["master_key_hex"]), keyring["tenant_id"])
        derived_keys[entry["id"]] = derived
        if key_fingerprint(derived) != entry["derived_key_fingerprint_hex"]:
            print(f"FAIL keyring {entry['id']}: derived-key fingerprint mismatch")
            failures += 1
    # Selection table for the per-entry-identity path: fingerprints of the
    # HKDF-DERIVED per-tenant encryption keys only — a master-key fingerprint
    # is deliberately not in here, so a vector carrying one cannot select.
    derived_fingerprints = {key_fingerprint(derived): key_id for key_id, derived in derived_keys.items()}

    vectors = keyring.get("vectors", [])
    missing = FROZEN_KEYRING_VECTOR_NAMES - {vec.get("name") for vec in vectors}
    if missing:
        print(f"FAIL frozen keyring vectors missing: {sorted(missing)}")
        failures += 1
    if not seal:
        print("note: keyring decrypt checks require cryptography — AAD, metadata and fingerprint selection only")

    full_keyring = [derived_keys[key_id] for key_id in KEYRING_ORDER]
    current_only = [derived_keys[KEYRING_ORDER[0]]]
    for vec in vectors:
        name = vec["name"]
        encrypted_with = vec.get("encrypted_with")
        if encrypted_with not in KEYRING_ORDER or FROZEN_KEYRING_VECTORS.get(name, encrypted_with) != encrypted_with:
            print(
                f"FAIL keyring {name}: encrypted_with must be the entry the frozen name declares (one of {list(KEYRING_ORDER)}); got {encrypted_with!r}"
            )
            failures += 1
            continue
        if not isinstance(vec["compressed"], bool) or vec["format"] not in FORMAT_REGISTRY:
            print(
                f"FAIL keyring {name}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})"
            )
            failures += 1
            continue
        aad = aad_v3(keyring["tenant_id"], vec["cache_key"], fmt=vec["format"], compressed=vec["compressed"])
        if aad.hex() != vec["aad_hex"]:
            print(f"FAIL keyring {name}: AAD mismatch\n  expected {vec['aad_hex']}\n  rebuilt  {aad.hex()}")
            failures += 1
            continue
        if derived_fingerprints.get(vec.get("key_fingerprint_hex")) != encrypted_with:
            print(
                f"FAIL keyring {name}: stored key fingerprint must select the HKDF-derived key of {encrypted_with} (never a master key)"
            )
            failures += 1
            continue
        if not seal:
            print(f"ok  keyring {name} (AAD + fingerprint selection only)")
            continue

        ciphertext = bytes.fromhex(vec["ciphertext_hex"])
        full_result = decrypt_with_keyring(full_keyring, ciphertext, aad)
        if full_result is None or full_result[1].hex() != vec["plaintext_hex"]:
            print(f"FAIL keyring {name}: {list(KEYRING_ORDER)} did not decrypt to plaintext_hex")
            failures += 1
            continue
        if full_result[0] != KEYRING_ORDER.index(encrypted_with):
            print(
                f"FAIL keyring {name}: decrypted with keyring entry {KEYRING_ORDER[full_result[0]]}, expected {encrypted_with}"
            )
            failures += 1
            continue
        if encrypted_with != KEYRING_ORDER[0] and decrypt_with_keyring(current_only, ciphertext, aad) is not None:
            print(f"FAIL keyring {name}: [{KEYRING_ORDER[0]}] alone accepted the {encrypted_with} entry")
            failures += 1
            continue
        print(f"ok  keyring {name}")
    return failures


def verify(doc: dict, *, require_seal: bool) -> int:
    failures = 0

    missing = FROZEN_VECTOR_NAMES - {v["name"] for v in doc["vectors"]}
    if missing:
        print(f"FAIL frozen vectors missing (append-only file — never remove/rename): {sorted(missing)}")
        return 1

    key = derive_encryption_key(bytes.fromhex(doc["master_key_hex"]), doc["tenant_id"])
    if key_fingerprint(key) != doc["derived_key_fingerprint_hex"]:
        print(f"FAIL key fingerprint: derived {key_fingerprint(key)}, pinned {doc['derived_key_fingerprint_hex']}")
        return 1
    print(f"ok  key fingerprint {doc['derived_key_fingerprint_hex']}")

    invalid_tag_exc: type[BaseException] = Exception
    try:
        from cryptography.exceptions import InvalidTag  # noqa: PLC0415
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: PLC0415

        aesgcm: AESGCM | None = AESGCM(key)
        invalid_tag_exc = InvalidTag
    except ImportError:
        if require_seal:
            print("FAIL --require-seal set but `cryptography` is not installed")
            return 1
        aesgcm = None
        print("note: `cryptography` not installed — AAD reconstruction only, AES-GCM seal NOT verified")

    for vec in doc["vectors"]:
        name = vec["name"]
        if not isinstance(vec["compressed"], bool) or vec["format"] not in FORMAT_REGISTRY:
            print(
                f"FAIL {name}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})"
            )
            failures += 1
            continue
        aad = aad_v3(
            doc["tenant_id"],
            vec["cache_key"],
            fmt=vec["format"],
            compressed=vec["compressed"],
            original_type=vec.get("original_type"),
        )
        if aad.hex() != vec["aad_hex"]:
            print(f"FAIL {name}: AAD mismatch\n  expected {vec['aad_hex']}\n  rebuilt  {aad.hex()}")
            failures += 1
            continue

        if aesgcm is not None:
            ct = bytes.fromhex(vec["ciphertext_hex"])
            nonce, sealed = ct[:12], ct[12:]
            try:
                plaintext = aesgcm.decrypt(nonce, sealed, aad)
            except invalid_tag_exc:
                print(f"FAIL {name}: decrypt failed (InvalidTag — AAD/key/ciphertext mismatch)")
                failures += 1
                continue
            if plaintext.hex() != vec["plaintext_hex"]:
                print(f"FAIL {name}: plaintext mismatch\n  expected {vec['plaintext_hex']}\n  got      {plaintext.hex()}")
                failures += 1
                continue
        print(f"ok  {name}")

    failures += verify_keyring(doc.get("keyring"), seal=aesgcm is not None)

    if failures:
        print(f"{failures} vector(s) FAILED")
        return 1
    mode = "AAD + AES-GCM seal" if aesgcm is not None else "AAD-only"
    keyring_count = len(doc.get("keyring", {}).get("vectors", []))
    print(f"all {len(doc['vectors'])} encryption vectors plus {keyring_count} keyring vectors verified ({mode})")
    return 0


def main() -> int:
    require_seal = "--require-seal" in sys.argv[1:]
    return verify(json.loads(VECTORS_PATH.read_text()), require_seal=require_seal)


if __name__ == "__main__":
    sys.exit(main())
