#!/usr/bin/env python3
"""Verify test-vectors/encryption.json against spec/encryption.md.

Stdlib-only checks (always run):
  - HKDF-SHA256 key derivation reproduces the pinned key fingerprint
    (ground-truth continuity with the published vectors and with
    tools/interop-reference.py, which pins the same fingerprint).
  - Every vector's `aad_hex` reconstructs byte-for-byte from its fields
    (tenant_id, cache_key, format, compressed, optional original_type),
    including the frozen ASCII boolean tokens `True` / `False`.
  - Keyring vectors: entry derivation, metadata, AAD, and fingerprint selection
    pinned to the HKDF-derived per-tenant encryption key, never the master key.
  - Master key input rows (spec/intent-presets.md § Master Key Input): each accept
    row is accepted, and each reject row refused, by a conformant hex entry point
    whether it takes exactly 32 bytes or 32 and more, and under both readings of
    what rule 1 leaves open (an uppercase digit, white space, a 0x prefix); each raw
    reject row is not 32 bytes; an accept row shares neither its master key nor its
    cache_key or plaintext with a default_tenant entry or the other accept row; each accept
    row's fingerprint and AAD. Each mistake a
    row's note names is modelled in WRONG_HEX_ENTRY_POINTS or WRONG_RAW_ENTRY_POINTS
    and must misjudge the rows it lists, so editing a row until it no longer shows
    the mistake goes red.
  - Post-decryption containers (spec/encryption.md, ENC-2 and ENC-3): each row is sealed
    under the AAD of the reader it names and holds the plaintext its name pins, a
    conforming reader of that container gives what its outcome says, and each mistake a
    note names is modelled
    in WRONG_CONTAINER_READERS and returns a value its row's outcome forbids, read with
    the same stdlib decoders.
  - Keyring configurations (spec/encryption.md § Key Rotation, ENC-7 and ENC-9): each
    accept row loads, and each reject row is refused, under both readings of what
    intent-presets.md rule 1 leaves open, and no row holds a key twice in its
    decrypt-only list, which the spec leaves open too. Each mistake a note names is
    modelled in WRONG_KEYRING_LOADS and must misjudge the rows it lists.
  - AAD reject rows (spec/encryption.md, ENC-1): each presents a published vector's
    ciphertext under AAD inputs that differ from its own in exactly the component its
    name declares, and with `cryptography` the ciphertext fails authentication under
    them, so a reader that never retries refuses every row. Each retry a note names is
    modelled in WRONG_AAD_RETRIES and must rebuild the sealed vector's AAD.
  - No vector table outside the ones verified here: tools/conformance.py indexes
    every list under a key ending in "vectors".
  - Writer-shape vectors (spec/encryption.md, ENC-10) keep the AAD shape a writer emits,
    and their plaintext is the container their compressed flag claims: a ByteStorage
    envelope under True, one MessagePack document that is no envelope under False,
    read with the stdlib decoders of interop-reference.py, wire-format-reference.py and
    interop-v2-reference.py.
  - The vector count never drops below the frozen floor — vectors are
    ground truth and may be added, never removed.

Seal check (runs when `cryptography` is installed; `--require-seal` makes
its absence a hard failure — CI passes the flag in the optional-deps step):
  - Every vector's `ciphertext_hex` decrypts under the derived key + AAD to
    `plaintext_hex`. (No re-seal comparison: AES-GCM is deterministic per
    (key, nonce, aad, plaintext), so a successful decrypt + plaintext match
    already proves the seal.)
  - Keyring vectors decrypt under [k2, k1] at the declared entry, and the k1 entry
    is rejected under [k2] alone (sequential-attempt path).
  - Each master key input accept row decrypts under the key its own master key
    derives for tenant "default".

Exit status is non-zero on any mismatch. Vectors are frozen ground truth and
are never regenerated by this tool.
"""

from __future__ import annotations

import functools
import hashlib
import hmac
import importlib.util
import json
import re
import string
import sys
from collections.abc import Callable, Iterator
from pathlib import Path
from types import ModuleType

VECTORS_PATH = Path(__file__).resolve().parent.parent / "test-vectors" / "encryption.json"

# Frozen protocol constants (spec/encryption.md, "compressed tokens").
TOKEN_TRUE = b"True"
TOKEN_FALSE = b"False"

# Vectors are append-only ground truth: a published row may never be removed, renamed or moved. Removal or rename
# (even with a same-count replacement) and reordering must go red in CI, because consumers index rows by position as
# well as by name (cachekit-ts and cachekit-rs read vectors[0] and accept_vectors[0]). Each frozen tuple below is in
# file order, and frozen_order_failure holds every table to it.
FROZEN_VECTOR_NAMES = (
    "basic_bytes",
    "special_cache_key",
    "compressed_basic",
    "arrow_uncompressed",
    "arrow_compressed",
    "orjson_uncompressed",
    "original_type_numpy",
    "standard_serializer_default",
    "standard_serializer_integrity_off",
)

# Vectors that pin the AAD shape a writer emits over that writer's own plaintext (spec/encryption.md, ENC-10):
# cachekit-py's StandardSerializer with integrity checking on and off, as (format, compressed, original_type).
WRITER_SHAPES = {
    "standard_serializer_default": ("msgpack", True, "msgpack"),
    "standard_serializer_integrity_off": ("msgpack", False, "msgpack"),
}

# format registry per spec/encryption.md — vectors must not invent tokens.
FORMAT_REGISTRY = frozenset({"msgpack", "orjson", "arrow"})

# Keyring conformance vectors: frozen name -> the entry that sealed it. The
# conformance keyring is current=k2 with decrypt-only k1 (KEYRING_ORDER).
FROZEN_KEYRING_VECTORS = {"encrypted_with_k1": "k1", "encrypted_with_k2": "k2"}
KEYRING_ORDER = ("k2", "k1")

# Default-tenant conformance (spec/intent-presets.md § Master Key Input rule 5): the
# tenant MUST be the literal "default" and the vector names are frozen like the rest.
DEFAULT_TENANT_ID = "default"
FROZEN_DEFAULT_TENANT_VECTOR_NAMES = ("default_tenant_interop",)

# Master key input (spec/intent-presets.md § Master Key Input): hex keys an entry point must accept or refuse, and raw
# keys a raw-bytes entry point must refuse. Names are frozen per table, and each table's rows have exactly its fields.
FROZEN_MASTER_KEY_INPUT_VECTORS = {
    "accept_vectors": ("master_key_every_hex_digit", "master_key_first_byte_80"),
    "reject_vectors": (
        "master_key_odd_65_digits",
        "master_key_odd_63_digits",
        "master_key_non_hex_digit",
        "master_key_trailing_non_hex",
        "master_key_plus_sign",
        "master_key_31_bytes",
        "master_key_24_bytes",
        "master_key_16_bytes",
        "master_key_31_bytes_and_crlf",
        "master_key_31_bytes_with_spaces",
        "master_key_0x_and_31_bytes",
    ),
    "raw_reject_vectors": ("raw_key_31_bytes", "raw_key_24_bytes", "raw_key_16_bytes", "raw_key_33_bytes", "raw_key_ascii_hex_string"),
}
MASTER_KEY_INPUT_FIELDS = {
    "accept_vectors": frozenset(
        {
            "name",
            "master_key_hex",
            "derived_key_fingerprint_hex",
            "plaintext_hex",
            "cache_key",
            "format",
            "compressed",
            "aad_hex",
            "ciphertext_hex",
            "note",
        }
    ),
    "reject_vectors": frozenset({"name", "master_key_hex", "note"}),
    "raw_reject_vectors": frozenset({"name", "raw_key_hex", "note"}),
}
KEY_BYTES = 32
# Rule 3 lets a hex entry point accept exactly 32 bytes or 32 and more, so every row must get one verdict under both.
EXACTLY, OR_MORE = "exactly 32 bytes", "32 bytes or more"
HEX_LENGTH_RULES: dict[str, Callable[[int], bool]] = {
    EXACTLY: lambda n: n == KEY_BYTES,
    OR_MORE: lambda n: n >= KEY_BYTES,
}
LOWER_HEX = frozenset("0123456789abcdef")
# Rule 1 does not say whether a key may hold uppercase hex digits, white space or a 0x prefix, so every row must get
# one verdict under both readings of it: each reading, and whether read_hex_key reads leniently under it. The white
# space is the ASCII set Python's bytes.fromhex skips, which JavaScript's trim() strips too.
READINGS = {
    "refuses uppercase digits, white space and a 0x prefix": False,
    "drops white space and a 0x prefix and reads uppercase as lowercase": True,
}
ASCII_WHITE_SPACE = frozenset(" \t\n\r\x0b\x0c")
# Rows hold printable ASCII and that white space only, so none turns on how a parser treats any other character
# (trim() also strips non-ASCII white space and U+FEFF).
ROW_CHARACTERS = frozenset(string.printable)

# AAD reject rows (spec/encryption.md § AAD v0x03 Format, ENC-1): a vector's ciphertext presented under AAD inputs that
# differ from its own in one component. A reader that retries with the input it was sealed under decrypts a row; a
# reader that never retries fails authentication. Names are frozen in file order, each with the vector whose
# ciphertext it carries, the input it changes, the value it presents (None: the component is absent), the container of
# the reader that presents it, and whether that reader, once a retry has decrypted the row, reads a value from the
# plaintext; where it does not, only a test that asserts the authentication failure tells a retry apart. A row has
# exactly these fields, original_type optional.
FROZEN_AAD_REJECT_VECTORS: dict[str, tuple[str, str, object, str, bool]] = {
    "aad_compressed_false_sealed_true": ("compressed_basic", "compressed", False, "plain_msgpack", False),
    "aad_compressed_true_sealed_false": ("basic_bytes", "compressed", True, "bytestorage_envelope", False),
    "aad_format_msgpack_sealed_arrow": ("arrow_uncompressed", "format", "msgpack", "arrow_checksummed", False),
    "aad_without_original_type_sealed_with": ("original_type_numpy", "original_type", None, "plain_msgpack", True),
    "aad_with_original_type_sealed_without": ("basic_bytes", "original_type", "msgpack", "plain_msgpack", False),
    "aad_key_with_prefix_sealed_without": ("basic_bytes", "cache_key", "app:test:vector:1", "plain_msgpack", False),
    "aad_compressed_false_sealed_true_five_components": ("standard_serializer_default", "compressed", False, "plain_msgpack", True),
    "aad_compressed_true_sealed_false_five_components": (
        "standard_serializer_integrity_off",
        "compressed",
        True,
        "bytestorage_envelope",
        False,
    ),
    "aad_without_original_type_sealed_with_msgpack": (
        "standard_serializer_default",
        "original_type",
        None,
        "bytestorage_envelope",
        True,
    ),
    "aad_format_arrow_sealed_msgpack": ("standard_serializer_default", "format", "arrow", "bytestorage_envelope", True),
}
AAD_REJECT_FIELDS = frozenset({"name", "sealed_as", "cache_key", "format", "compressed", "aad_hex", "ciphertext_hex", "note"})
AAD_INPUTS = ("cache_key", "format", "compressed", "original_type")
# The original_type values cachekit-py emits (spec/encryption.md § original_type).
ORIGINAL_TYPES = ("msgpack", "orjson", "arrow", "numpy", "dataframe", "series")


def _with(inputs: dict, **changes: object) -> dict:
    """AAD inputs with some changed; None removes original_type."""
    out = {**inputs, **changes}
    return {k: v for k, v in out.items() if v is not None or k != "original_type"}


# Plausible retrying readers, one per mistake an AAD reject note names: each gives the inputs it retries with after the
# presented ones fail, and must reach the row's sealed AAD, so it decrypts the row; it lists a row only if that row's
# note names its mistake.
WRONG_AAD_RETRIES: dict[str, tuple[Callable[[dict], list[dict]], tuple[str, ...]]] = {
    "retries with the other compressed value": (
        lambda i: [_with(i, compressed=not i["compressed"])],
        (
            "aad_compressed_false_sealed_true",
            "aad_compressed_true_sealed_false",
            "aad_compressed_false_sealed_true_five_components",
            "aad_compressed_true_sealed_false_five_components",
        ),
    ),
    "flips the compressed value only on five-component AADs": (
        lambda i: [_with(i, compressed=not i["compressed"])] if "original_type" in i else [],
        ("aad_compressed_false_sealed_true_five_components", "aad_compressed_true_sealed_false_five_components"),
    ),
    "retries with the other registry format tokens": (
        lambda i: [_with(i, format=fmt) for fmt in sorted(FORMAT_REGISTRY - {i["format"]})],
        ("aad_format_msgpack_sealed_arrow", "aad_format_arrow_sealed_msgpack"),
    ),
    "retries with msgpack, the StandardSerializer's own format token": (
        lambda i: [_with(i, format="msgpack")] if i["format"] != "msgpack" else [],
        ("aad_format_arrow_sealed_msgpack",),
    ),
    "retries with each original_type value cachekit-py emits": (
        lambda i: [_with(i, original_type=t) for t in ORIGINAL_TYPES if t != i.get("original_type")],
        ("aad_without_original_type_sealed_with", "aad_without_original_type_sealed_with_msgpack"),
    ),
    "retries with msgpack, the StandardSerializer's own original_type": (
        lambda i: [_with(i, original_type="msgpack")] if i.get("original_type") != "msgpack" else [],
        ("aad_without_original_type_sealed_with_msgpack",),
    ),
    "retries without original_type": (
        lambda i: [_with(i, original_type=None)] if "original_type" in i else [],
        ("aad_with_original_type_sealed_without",),
    ),
    "retries with the cache key stripped of its first segment": (
        lambda i: [_with(i, cache_key=i["cache_key"].split(":", 1)[1])] if ":" in i["cache_key"] else [],
        ("aad_key_with_prefix_sealed_without",),
    ),
}

# Every vector table this file may hold. tools/conformance.py indexes each list under a key ending in "vectors", so a
# table missing here would publish rows that nothing verifies.
VECTOR_TABLES = frozenset(
    {"vectors", "aad_reject_vectors", "decrypted_container.vectors", "keyring.vectors", "keyring.configuration.vectors"}
    | {"default_tenant.vectors"}
    | {f"master_key_input.{t}" for t in FROZEN_MASTER_KEY_INPUT_VECTORS}
)


def frozen_order_failure(table: str, rows: object, frozen: tuple[str, ...]) -> str | None:
    """A FAIL line when `rows` do not open with the frozen rows in their frozen order, else None."""
    names = [row.get("name") if isinstance(row, dict) else None for row in rows] if isinstance(rows, list) else []
    if names[: len(frozen)] != list(frozen):
        return (
            f"FAIL frozen {table} rows missing or moved (append-only: never remove, rename or move a row): "
            f"want {list(frozen)} first, got {names[: len(frozen)]}"
        )
    return None


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int = 32) -> bytes:
    """RFC 5869 HKDF-Extract + Expand with SHA-256."""
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
        i += 1
    return okm[:length]


def construct_salt(domain: str, tenant_salt: str) -> bytes:
    d, t = domain.encode("utf-8"), tenant_salt.encode("utf-8")
    return b"cachekit_v1_" + bytes([len(d)]) + d + len(t).to_bytes(2, "big") + t


def derive_encryption_key(master_key: bytes, tenant_id: str) -> bytes:
    return hkdf_sha256(master_key, construct_salt("encryption", tenant_id), b"encryption")


def key_fingerprint(key: bytes) -> str:
    return hashlib.sha256(b"key_fingerprint_v1" + key).digest()[:16].hex()


def decrypt_with_keyring(keys: list[bytes], ciphertext: bytes, aad: bytes) -> tuple[int, bytes] | None:
    """Try each key once, in keyring order, with identical authenticated data."""
    from cryptography.exceptions import InvalidTag  # noqa: PLC0415
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: PLC0415

    nonce, sealed = ciphertext[:12], ciphertext[12:]
    for index, key in enumerate(keys):
        try:
            return index, AESGCM(key).decrypt(nonce, sealed, aad)
        except InvalidTag:
            continue
    return None


def aad_v3(tenant_id: str, cache_key: str, *, fmt: str, compressed: bool, original_type: str | None = None) -> bytes:
    """AAD v0x03 per spec/encryption.md — 4-byte BE length-prefixed components.

    Unlike interop-reference.py's aad_v3, this supports the optional fifth
    original_type component. The interop copy omits it DELIBERATELY — interop
    AAD is exactly four components; do not "harmonize" the two.
    """
    components = [
        tenant_id.encode("utf-8"),
        cache_key.encode("utf-8"),
        fmt.encode("utf-8"),
        TOKEN_TRUE if compressed else TOKEN_FALSE,
    ]
    if original_type is not None:
        components.append(original_type.encode("utf-8"))
    aad = bytearray([0x03])
    for component in components:
        aad += len(component).to_bytes(4, "big") + component
    return bytes(aad)


@functools.cache
def _load_tool(filename: str) -> ModuleType:
    """A sibling stdlib-only reference tool, loaded as a module (its filename is hyphenated)."""
    path = Path(__file__).resolve().parent / filename
    spec = importlib.util.spec_from_file_location(path.stem.replace("-", "_"), path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def one_document(data: bytes) -> bytes | None:
    """`data` if it is exactly one MessagePack document, else None: what a plain-MessagePack reader returns."""
    try:
        _load_tool("interop-reference.py").decode_value(data)
    except ValueError:
        return None
    return data


def envelope_value(data: bytes) -> bytes | None:
    """The bytes a ByteStorage envelope holds (LZ4-decompressed, checksum unchecked), or None if `data` is not one."""
    try:
        compressed, _, size, _, _ = _load_tool("wire-format-reference.py").decode_envelope(data)
        return _load_tool("interop-v2-reference.py").lz4_block_decompress(compressed, size)
    except ValueError:
        return None


def writer_shape_failure(vec: dict) -> str | None:
    """Why a WRITER_SHAPES vector no longer pins its writer's shape over that writer's container; None when it does."""
    fmt, compressed, original_type = WRITER_SHAPES[vec["name"]]
    if (vec["format"], vec["compressed"], vec.get("original_type")) != (fmt, compressed, original_type):
        return f"must keep the AAD shape ({fmt}, {compressed}, {original_type}) its writer emits"
    plaintext = bytes.fromhex(vec["plaintext_hex"])
    envelope = envelope_value(plaintext) is not None
    if compressed and not envelope:
        return "claims compressed True, but its plaintext is no ByteStorage envelope"
    if not compressed and (envelope or one_document(plaintext) is None):
        return "claims compressed False, but its plaintext is not one plain MessagePack document"
    return None


def verify_sealed_vector(
    label: str, vec: dict, tenant_id: str, keys: list[bytes], *, seal: bool, original_type: str | None = None
) -> tuple[bytes, int | None] | None:
    """Per-vector conformance body shared by every block: metadata, AAD rebuild, then decrypt + plaintext.

    Prints a FAIL line and returns None on the first mismatch. Otherwise returns the
    rebuilt AAD and the index of the key in `keys` that decrypted (None when `seal`
    is off). The caller prints the ok-line, so block-specific guards run first.
    """
    if not isinstance(vec["compressed"], bool) or vec["format"] not in FORMAT_REGISTRY:
        print(f"FAIL {label}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})")
        return None
    aad = aad_v3(tenant_id, vec["cache_key"], fmt=vec["format"], compressed=vec["compressed"], original_type=original_type)
    if aad.hex() != vec["aad_hex"]:
        print(f"FAIL {label}: AAD mismatch\n  expected {vec['aad_hex']}\n  rebuilt  {aad.hex()}")
        return None
    if not seal:
        return aad, None
    result = decrypt_with_keyring(keys, bytes.fromhex(vec["ciphertext_hex"]), aad)
    if result is None:
        print(f"FAIL {label}: decrypt failed (InvalidTag — AAD/key/ciphertext mismatch)")
        return None
    index, plaintext = result
    if plaintext.hex() != vec["plaintext_hex"]:
        print(f"FAIL {label}: plaintext mismatch\n  expected {vec['plaintext_hex']}\n  got      {plaintext.hex()}")
        return None
    return aad, index


def verify_aad_rejects(doc: dict, key: bytes, *, seal: bool) -> int:
    """Return the number of failed AAD reject rows (spec/encryption.md ENC-1: readers never retry with another AAD input).

    Each row names the vector in `vectors` whose ciphertext it carries (`sealed_as`) and presents AAD inputs that differ
    from that vector's in exactly one of cache_key, format, compressed and original_type (present or absent). Its
    aad_hex must rebuild from what it presents. With `cryptography`, the ciphertext must fail authentication under the
    presented AAD, which the one-input rule already implies; the check shows the row's claim with the cipher itself.
    """
    rows = doc.get("aad_reject_vectors")
    if not isinstance(rows, list) or not all(isinstance(row, dict) and isinstance(row.get("name"), str) for row in rows):
        print("FAIL aad_reject_vectors missing, or a row that is not an object with a string name")
        return 1
    failures = 0
    missing = set(FROZEN_AAD_REJECT_VECTORS) - {row["name"] for row in rows}
    if missing:
        print(f"FAIL frozen aad_reject_vectors missing (append-only, never rename): {sorted(missing)}")
        failures += 1
    if moved := frozen_order_failure("aad_reject_vectors", rows, tuple(FROZEN_AAD_REJECT_VECTORS)):
        print(moved)
        failures += 1
    sealed = {v["name"]: v for v in doc["vectors"]}
    seen: set[str] = set()
    checked: dict[str, tuple[dict, dict]] = {}
    for row in rows:
        name = row["name"]
        label = f"aad_reject {name}"
        if set(row) - {"original_type"} != AAD_REJECT_FIELDS:
            print(f"FAIL {label}: fields {sorted(row)} != {sorted(AAD_REJECT_FIELDS)} (original_type optional)")
            failures += 1
            continue
        if name in seen:
            print(f"FAIL {label}: duplicate name")
            failures += 1
            continue
        seen.add(name)
        if not isinstance(row["note"], str) or not row["note"].strip():
            print(f"FAIL {label}: note must be a non-empty string")
            failures += 1
            continue
        if not isinstance(row["compressed"], bool) or row["format"] not in FORMAT_REGISTRY:
            print(f"FAIL {label}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})")
            failures += 1
            continue
        base = sealed.get(row["sealed_as"])
        if base is None:
            print(f"FAIL {label}: sealed_as names no vector in `vectors`: {row['sealed_as']!r}")
            failures += 1
            continue
        if row["ciphertext_hex"] != base["ciphertext_hex"]:
            print(f"FAIL {label}: ciphertext is not {row['sealed_as']}'s")
            failures += 1
            continue
        aad = aad_v3(doc["tenant_id"], row["cache_key"], fmt=row["format"], compressed=row["compressed"], original_type=row.get("original_type"))
        if aad.hex() != row["aad_hex"]:
            print(f"FAIL {label}: AAD mismatch\n  expected {row['aad_hex']}\n  rebuilt  {aad.hex()}")
            failures += 1
            continue
        differs = [f for f in AAD_INPUTS if (f in row) != (f in base) or row.get(f) != base.get(f)]
        if len(differs) != 1:
            print(f"FAIL {label}: differs from {row['sealed_as']} in {differs or 'no'} AAD input(s); a row presents exactly one alternative")
            failures += 1
            continue
        sealed_as, component, presented, container, retry_value = FROZEN_AAD_REJECT_VECTORS.get(
            name, (row["sealed_as"], differs[0], row.get(differs[0]), None, None)
        )
        if row["sealed_as"] != sealed_as or differs != [component] or row.get(component) != presented:
            print(f"FAIL {label}: must carry {sealed_as}'s ciphertext and present {component} {presented!r}, as its frozen name declares")
            failures += 1
            continue
        if container is not None and (CONFORMING_READERS[container](bytes.fromhex(base["plaintext_hex"])) is not None) != retry_value:
            print(
                f"FAIL {label}: a {container} reader that retried {'would not' if retry_value else 'would'} read a value from "
                f"{sealed_as}'s plaintext, against what its frozen name declares"
            )
            failures += 1
            continue
        if seal and decrypt_with_keyring([key], bytes.fromhex(row["ciphertext_hex"]), aad) is not None:
            print(f"FAIL {label}: decrypts under the AAD it presents, so a reader that never retries returns a value")
            failures += 1
            continue
        checked[name] = (row, base)
        print(f"ok  {label} ({differs[0]} differs{'; authentication fails' if seal else ''})")
    # Each retrying reader must rebuild the sealed vector's AAD from what a row it lists presents: that AAD
    # authenticates the ciphertext (the sealed vector's own check), so the retry decrypts the row.
    listed: set[str] = set()
    for label, (retries, targets) in WRONG_AAD_RETRIES.items():
        for target in targets:
            listed.add(target)
            if target not in FROZEN_AAD_REJECT_VECTORS:
                print(f"FAIL wrong AAD retry {label!r} lists {target}, which is not a frozen row of its table")
                failures += 1
                continue
            if target not in checked:
                continue  # the frozen-name or row guards report it
            row, base = checked[target]
            presented = {f: row[f] for f in AAD_INPUTS if f in row}
            rebuilt = {
                aad_v3(doc["tenant_id"], i["cache_key"], fmt=i["format"], compressed=i["compressed"], original_type=i.get("original_type")).hex()
                for i in retries(presented)
            }
            if base["aad_hex"] not in rebuilt:
                print(f"FAIL wrong AAD retry {label!r} never reaches {target}'s sealed AAD, so the row no longer shows the mistake its note names")
                failures += 1
    unshown = sorted((set(FROZEN_AAD_REJECT_VECTORS) | set(checked)) - listed)
    if unshown:
        print(f"FAIL no wrong AAD retry shows why these rows exist: {unshown}")
        failures += 1
    return failures


# Post-decryption containers (spec/encryption.md § AAD v0x03 Format, ENC-2 and ENC-3). Each row names the reader whose
# AAD sealed it and what a conforming read returns. Names are frozen and a row has exactly these fields.
# Each row's plaintext is pinned by its sha256: the bytes its note names (python-frame.json's and interop-mode.json's),
# which no structural check here can tell from a lookalike (an Arrow IPC file, an envelope with a valid checksum). Names
# are frozen in file order.
FROZEN_CONTAINER_VECTORS = {
    "container_envelope_to_plain_reader": ("plain_msgpack", "not_unwrapped", "d010549e486e806ba50c56f199cc91faac5a1cf796b8f36a6cc57e5fa69b0493"),
    "container_trailing_byte_to_interop_reader": ("interop", "error", "8c280077d054f1c13e0ae440a9195e19d650ba2ac7bde15e879f4b542b499287"),
    "container_plain_to_envelope_reader": ("bytestorage_envelope", "error", "b1d42254e4b144c645aa00b536a2f14fc2f00689a039190854a3fb9583e5c9d7"),
    "container_bare_arrow_to_arrow_reader": ("arrow_checksummed", "error", "d3fd80caec4d017644d047560abe29b356569ceed943daf0b0a4c56161b885bb"),
    "container_plain_json_to_orjson_reader": ("orjson_checksummed", "error", "dbeff30d1e42fca9a2f7d3607009347623357c6188c0394bf602a55849faaf2b"),
    "container_incomplete_tail_to_interop_reader": ("interop", "error", "94f62f2542793da7c4f64704e437f796327ca2d9e6b255a6a511c16f01aac52b"),
}
CONTAINER_OUTCOMES = ("not_unwrapped", "error")
CONTAINER_FIELDS = frozenset(
    {"name", "reader", "cache_key", "format", "compressed", "aad_hex", "plaintext_hex", "ciphertext_hex", "outcome", "note"}
)
# The AAD inputs each reader builds, as (format, compressed, original_type): what its writer's container did. The Arrow
# rows hold uncompressed IPC, so their flag is False. An interop reader builds the plain-MessagePack AAD, under a key of
# interop-mode.json's, and alone among the plain readers MUST consume exactly one document (spec/interop-mode.md); for
# the others, and for an envelope reader, whether bytes after the document or envelope are refused is not stated, so
# no row asks it of them.
READER_AAD: dict[str, tuple[str, bool, str | None]] = {
    "plain_msgpack": ("msgpack", False, None),
    "interop": ("msgpack", False, None),
    "bytestorage_envelope": ("msgpack", True, None),
    "arrow_checksummed": ("arrow", False, "arrow"),
    "orjson_checksummed": ("orjson", False, "orjson"),
}
INTEROP_VECTORS_PATH = VECTORS_PATH.parent / "interop-mode.json"
ARROW_MAGIC = b"ARROW1"


def first_document(data: bytes) -> bytes | None:
    """The bytes of the first MessagePack document in `data`, whatever follows it, or None if none is complete."""
    try:
        _, end = _load_tool("interop-reference.py")._decode(data, 0)  # noqa: SLF001 -- the reference's own decoder
    except ValueError:
        return None
    return data[:end]


def second_document_complete(data: bytes) -> bytes | None:
    """The first document, unless a complete second one follows it: a reader that refuses only a second document it can
    read, and ignores an incomplete one."""
    first = first_document(data)
    if first is None:
        return None
    rest = data[len(first) :]
    return first if not rest or first_document(rest) is None else None


def _non_json_constant(token: str) -> object:
    """json.loads accepts NaN and Infinity, which RFC 8259 does not."""
    raise ValueError(f"not RFC 8259 JSON: {token}")


def json_document(data: bytes) -> bytes | None:
    """`data` if it is one RFC 8259 JSON document, else None."""
    try:
        json.loads(data.decode("utf-8"), parse_constant=_non_json_constant)
    except ValueError:
        return None
    return data


def checksummed_json(data: bytes) -> bytes | None:
    """The JSON after an 8-byte checksum (unchecked: xxHash3-64 is not stdlib), or None without that layout."""
    return json_document(data[8:]) if len(data) > 8 else None


def checksummed_arrow(data: bytes) -> bytes | None:
    """The Arrow IPC file after an 8-byte checksum (unchecked: xxHash3-64 is not stdlib), or None without that layout."""
    return data[8:] if data[8 : 8 + len(ARROW_MAGIC)] == ARROW_MAGIC else None


CONFORMING_READERS: dict[str, Callable[[bytes], bytes | None]] = {
    "plain_msgpack": one_document,
    "interop": one_document,
    "bytestorage_envelope": envelope_value,
    "arrow_checksummed": checksummed_arrow,
    "orjson_checksummed": checksummed_json,
}

# Plausible wrong readers, one per mistake a container note names: each returns the bytes of the value it would return,
# or None for none, and must return a value its row's outcome forbids; it lists a row only if that row's note names it.
WRONG_CONTAINER_READERS: dict[str, tuple[Callable[[bytes], bytes | None], tuple[str, ...]]] = {
    "a sniffing reader, which unwraps a plaintext that parses as a ByteStorage envelope and reads any other as plain "
    "MessagePack, whatever it is configured for": (
        lambda d: envelope_value(d) or one_document(d),
        ("container_envelope_to_plain_reader", "container_plain_to_envelope_reader"),
    ),
    "an interop reader that ignores bytes after the first document": (
        first_document,
        ("container_trailing_byte_to_interop_reader", "container_incomplete_tail_to_interop_reader"),
    ),
    "an interop reader that refuses only a second complete document": (
        second_document_complete,
        ("container_incomplete_tail_to_interop_reader",),
    ),
    "an interop reader that strips trailing NUL bytes before a strict decode": (
        lambda d: one_document(d.rstrip(b"\0")),
        ("container_trailing_byte_to_interop_reader",),
    ),
    "an Arrow reader that accepts Arrow IPC with no checksum prefix": (
        lambda d: d if d.startswith(ARROW_MAGIC) else checksummed_arrow(d),
        ("container_bare_arrow_to_arrow_reader",),
    ),
    "an orjson reader that falls back to plain JSON when the checksum layout does not parse": (
        lambda d: checksummed_json(d) or json_document(d),
        ("container_plain_json_to_orjson_reader",),
    ),
}


def verify_decrypted_containers(doc: dict, key: bytes, *, seal: bool) -> int:
    """Return the number of failed post-decryption container checks (spec/encryption.md ENC-2 and ENC-3).

    Each row must be sealed under its reader's AAD (rebuilt, and with `cryptography` decrypted), hold the plaintext its
    name pins, and a conforming reader of that container must give what `outcome` says: `error`, nothing, or
    `not_unwrapped`, anything but the value inside the plaintext's envelope (the plaintext as one MessagePack document,
    or nothing). Then each wrong reader must return a value its row's outcome forbids.
    """
    block = doc.get("decrypted_container")
    vectors = block.get("vectors") if isinstance(block, dict) else None
    if not isinstance(vectors, list) or not all(isinstance(row, dict) and isinstance(row.get("name"), str) for row in vectors):
        print("FAIL decrypted_container rows missing, or a row that is not an object with a string name")
        return 1
    failures = 0
    if not isinstance(block.get("note"), str) or not block["note"].strip():
        print("FAIL decrypted_container: note must be a non-empty string")
        failures += 1
    missing = set(FROZEN_CONTAINER_VECTORS) - {row.get("name") for row in block["vectors"]}
    if missing:
        print(f"FAIL frozen decrypted_container rows missing (append-only, never rename): {sorted(missing)}")
        failures += 1
    if moved := frozen_order_failure("decrypted_container.vectors", vectors, tuple(FROZEN_CONTAINER_VECTORS)):
        print(moved)
        failures += 1
    interop_keys = {v.get("expected_key") for v in json.loads(INTEROP_VECTORS_PATH.read_text()).get("key_vectors", [])}
    rows: dict[str, dict] = {}
    for row in block["vectors"]:
        name = row.get("name")
        label = f"decrypted_container {name}"
        if set(row) - {"original_type"} != CONTAINER_FIELDS:
            print(f"FAIL {label}: fields {sorted(row)} != {sorted(CONTAINER_FIELDS)} (original_type optional)")
            failures += 1
            continue
        if name in rows:
            print(f"FAIL {label}: duplicate name")
            failures += 1
            continue
        if not isinstance(row["note"], str) or not row["note"].strip():
            print(f"FAIL {label}: note must be a non-empty string")
            failures += 1
            continue
        reader, outcome, pin = FROZEN_CONTAINER_VECTORS.get(name, (row["reader"], row["outcome"], None))
        if (row["reader"], row["outcome"]) != (reader, outcome) or reader not in READER_AAD or outcome not in CONTAINER_OUTCOMES:
            print(f"FAIL {label}: reader must be one of {sorted(READER_AAD)}, outcome one of {list(CONTAINER_OUTCOMES)}, as its frozen name declares")
            failures += 1
            continue
        fmt, compressed, original_type = READER_AAD[reader]
        if (row["format"], row["compressed"], row.get("original_type")) != (fmt, compressed, original_type):
            print(f"FAIL {label}: the {reader} reader builds its AAD with format {fmt}, compressed {compressed} and original_type {original_type}")
            failures += 1
            continue
        if reader == "interop" and row["cache_key"] not in interop_keys:
            print(f"FAIL {label}: an interop row's cache_key must be one of interop-mode.json's keys, so a test can read it as an interop operation")
            failures += 1
            continue
        if verify_sealed_vector(label, row, doc["tenant_id"], [key], seal=seal, original_type=row.get("original_type")) is None:
            failures += 1
            continue
        plaintext = bytes.fromhex(row["plaintext_hex"])
        got = CONFORMING_READERS[reader](plaintext)
        inner = envelope_value(plaintext)
        if outcome == "not_unwrapped" and (inner is None or got == inner):
            print(f"FAIL {label}: holds no envelope whose value a conforming reader declines, so not_unwrapped pins nothing")
            failures += 1
            continue
        if outcome == "error" and got is not None:
            print(f"FAIL {label}: a conforming {reader} reader returns a value from it")
            failures += 1
            continue
        rows[name] = row
        # Checked last, and without dropping the row, so the wrong readers still run on an edited plaintext.
        if pin is not None and hashlib.sha256(plaintext).hexdigest() != pin:
            print(f"FAIL {label}: plaintext differs from the bytes its frozen name pins")
            failures += 1
            continue
        print(f"ok  {label} ({row['reader']}: {row['outcome']})")
    listed: set[str] = set()
    for label, (read, targets) in WRONG_CONTAINER_READERS.items():
        for target in targets:
            listed.add(target)
            if target not in FROZEN_CONTAINER_VECTORS:
                print(f"FAIL wrong container reader {label!r} lists {target}, which is not a frozen row of its table")
                failures += 1
                continue
            row = rows.get(target)
            if row is None:
                continue  # the frozen-name or row guards report it
            plaintext = bytes.fromhex(row["plaintext_hex"])
            got = read(plaintext)
            forbidden = got == envelope_value(plaintext) if row["outcome"] == "not_unwrapped" else got is not None
            if not forbidden:
                print(f"FAIL wrong container reader {label!r} returns what {target}'s outcome allows, so the row no longer shows the mistake its note names")
                failures += 1
    unshown = sorted((set(FROZEN_CONTAINER_VECTORS) | set(rows)) - listed)
    if unshown:
        print(f"FAIL no wrong container reader shows why these rows exist: {unshown}")
        failures += 1
    return failures


def verify_keyring(keyring: dict | None, *, seal: bool) -> int:
    """Return the number of failed keyring checks (spec/encryption.md § Key Rotation).

    Entry derivation, metadata, AAD reconstruction and fingerprint selection are
    stdlib and always run; only the decrypt attempts need `cryptography` (`seal`).
    """
    if keyring is None:
        print("FAIL keyring vectors missing")
        return 1
    failures = 0

    entries = keyring.get("entries", [])
    ids = [entry.get("id") for entry in entries]
    if len(set(ids)) != len(ids) or not set(KEYRING_ORDER) <= set(ids):
        print(f"FAIL keyring entries must have unique ids including {sorted(KEYRING_ORDER)}; got {ids}")
        return failures + 1
    derived_keys: dict[str, bytes] = {}
    for entry in entries:
        derived = derive_encryption_key(bytes.fromhex(entry["master_key_hex"]), keyring["tenant_id"])
        derived_keys[entry["id"]] = derived
        if key_fingerprint(derived) != entry["derived_key_fingerprint_hex"]:
            print(f"FAIL keyring {entry['id']}: derived-key fingerprint mismatch")
            failures += 1
    # Selection table for the per-entry-identity path: fingerprints of the
    # HKDF-DERIVED per-tenant encryption keys only — a master-key fingerprint
    # is deliberately not in here, so a vector carrying one cannot select.
    derived_fingerprints = {key_fingerprint(derived): key_id for key_id, derived in derived_keys.items()}

    vectors = keyring.get("vectors", [])
    if moved := frozen_order_failure("keyring.vectors", vectors, tuple(FROZEN_KEYRING_VECTORS)):
        print(moved)
        failures += 1
    if not seal:
        print("note: keyring decrypt checks require cryptography — AAD, metadata and fingerprint selection only")

    full_keyring = [derived_keys[key_id] for key_id in KEYRING_ORDER]
    current_only = [derived_keys[KEYRING_ORDER[0]]]
    for vec in vectors:
        name = vec["name"]
        encrypted_with = vec.get("encrypted_with")
        if encrypted_with not in KEYRING_ORDER or FROZEN_KEYRING_VECTORS.get(name, encrypted_with) != encrypted_with:
            print(
                f"FAIL keyring {name}: encrypted_with must be the entry the frozen name declares (one of {list(KEYRING_ORDER)}); got {encrypted_with!r}"
            )
            failures += 1
            continue
        if derived_fingerprints.get(vec.get("key_fingerprint_hex")) != encrypted_with:
            print(
                f"FAIL keyring {name}: stored key fingerprint must select the HKDF-derived key of {encrypted_with} (never a master key)"
            )
            failures += 1
            continue
        checked = verify_sealed_vector(f"keyring {name}", vec, keyring["tenant_id"], full_keyring, seal=seal)
        if checked is None:
            failures += 1
            continue
        if not seal:
            print(f"ok  keyring {name} (AAD + fingerprint selection only)")
            continue

        aad, index = checked
        if index != KEYRING_ORDER.index(encrypted_with):
            print(f"FAIL keyring {name}: decrypted with keyring entry {KEYRING_ORDER[index]}, expected {encrypted_with}")
            failures += 1
            continue
        ciphertext = bytes.fromhex(vec["ciphertext_hex"])
        if encrypted_with != KEYRING_ORDER[0] and decrypt_with_keyring(current_only, ciphertext, aad) is not None:
            print(f"FAIL keyring {name}: [{KEYRING_ORDER[0]}] alone accepted the {encrypted_with} entry")
            failures += 1
            continue
        print(f"ok  keyring {name}")
    return failures


def verify_default_tenant(block: dict | None, master_key: bytes, *, seal: bool) -> int:
    """Return the number of failed default-tenant checks (intent-presets.md rule 5).

    The block pins tenant "default" under the main master key: fingerprint of the
    HKDF-derived key, AAD reconstruction with "default" as component 1, and (with
    `cryptography`) the seal. An SDK that decrypts these through its preset with NO
    tenant configured has demonstrated the cross-SDK default.
    """
    if block is None:
        print("FAIL default_tenant vectors missing")
        return 1
    failures = 0
    if block.get("tenant_id") != DEFAULT_TENANT_ID:
        print(f"FAIL default_tenant: tenant_id must be the literal {DEFAULT_TENANT_ID!r}; got {block.get('tenant_id')!r}")
        return 1
    key = derive_encryption_key(master_key, DEFAULT_TENANT_ID)
    if key_fingerprint(key) != block.get("derived_key_fingerprint_hex"):
        print(f"FAIL default_tenant: derived-key fingerprint mismatch (derived {key_fingerprint(key)})")
        return 1
    vectors = block.get("vectors", [])
    if moved := frozen_order_failure("default_tenant.vectors", vectors, FROZEN_DEFAULT_TENANT_VECTOR_NAMES):
        print(moved)
        failures += 1
    for vec in vectors:
        name = vec["name"]
        if verify_sealed_vector(f"default_tenant {name}", vec, DEFAULT_TENANT_ID, [key], seal=seal) is None:
            failures += 1
            continue
        if not seal:
            print(f"ok  default_tenant {name} (AAD + fingerprint only)")
            continue
        print(f"ok  default_tenant {name}")
    return failures


def read_hex_key(text: str, *, lenient: bool = False) -> bytes | None:
    """hex_decode(text) for a row under one reading of what rule 1 leaves open, or None for a refusal.

    The strict reading refuses an uppercase digit, white space and a 0x prefix. The lenient one drops ASCII white
    space, then a leading 0x, and reads uppercase as lowercase. A row must get one verdict under both, so no row
    settles the question; this judges rows only.
    """
    if lenient:
        text = "".join(c for c in text if c not in ASCII_WHITE_SPACE)
        text = (text[2:] if text[:2] in ("0x", "0X") else text).lower()
    if len(text) % 2 or not set(text) <= LOWER_HEX:
        return None
    return bytes.fromhex(text)


def vector_tables(node: object, path: str = "") -> Iterator[str]:
    """The path of every list under a key ending in "vectors", at any depth, as tools/conformance.py finds them."""
    if isinstance(node, dict):
        for key, value in node.items():
            where = f"{path}.{key}" if path else key
            if key.endswith("vectors") and isinstance(value, list):
                yield where
            else:
                yield from vector_tables(value, where)


# Plausible wrong hex and raw-bytes entry points, one per mistake a master_key_input note names. Each returns the key
# bytes it would use, or None for a refusal (one that cannot parse its input refuses it), and must misjudge every row
# it lists; it lists a row only if that row's note names its mistake, so the notes and this table say the same thing.
# A decoding mistake sits behind a conformant length rule, so its row must catch the mistake itself, not a
# length check that happens to; where only one of the two rules lets the mistake through, the entry point uses that one.
HEX_DIGITS = frozenset(string.hexdigits)
# The row every other row comes from, which the notes call the accept row, and the one accept row whose key's first
# byte is 80 or above: one key cannot hold both a leading 00 byte and a first byte at 80 or above.
ACCEPT_ROW = "master_key_every_hex_digit"
FIRST_BYTE_80_ROW = "master_key_first_byte_80"
EXACTLY_32, AT_LEAST_32 = HEX_LENGTH_RULES[EXACTLY], HEX_LENGTH_RULES[OR_MORE]


def behind(accepts: Callable[[int], bool], key: bytes | None) -> bytes | None:
    """`key` if a length rule that `accepts` its length lets it through, else None."""
    return key if key is not None and accepts(len(key)) else None


def buffer_from_hex(text: str) -> bytes:
    """Node's Buffer.from(text, "hex"): byte pairs up to the first that is not hex; an odd last digit is dropped."""
    out = bytearray()
    for i in range(0, len(text) - 1, 2):
        if not set(text[i : i + 2]) <= HEX_DIGITS:
            break
        out.append(int(text[i : i + 2], 16))
    return bytes(out)


def big_integer(text: str) -> bytes:
    """int(text, 16) back to bytes at its minimal length: a leading 00 byte disappears."""
    value = int(text, 16)
    return value.to_bytes((value.bit_length() + 7) // 8, "big")


def twos_complement(text: str) -> bytes:
    """Java's new BigInteger(text, 16).toByteArray() (num-bigint's to_signed_bytes_be): the minimal bytes plus a 00
    sign byte when the top bit is set, which restores a leading 00 only when the byte after it is 80 or above."""
    value = int(text, 16)
    return value.to_bytes(value.bit_length() // 8 + 1, "big")


def padded_twos_complement(text: str) -> bytes | None:
    """int(text, 16).to_bytes(32, "big", signed=True) behind a strict hex check: right for a key whose first byte is
    below 80, refused for one at 80 or above, whose sign needs a 33rd byte (where Java's toByteArray() returns 33)."""
    if read_hex_key(text) is None:
        return None
    try:
        return int(text, 16).to_bytes(KEY_BYTES, "big", signed=True)
    except OverflowError:
        return None


def java_padded(text: str) -> bytes | None:
    """Java's new BigInteger(text, 16).toByteArray() left-padded to 32 bytes behind a strict 64-character hex check: a key
    whose first byte is below 80 comes back right, one whose first byte is 80 or above as 33 bytes (a 00 sign byte)."""
    if len(text) != 2 * KEY_BYTES or read_hex_key(text) is None:
        return None
    return twos_complement(text).rjust(KEY_BYTES, b"\0")


def digits_swapped(text: str) -> bytes | None:
    """Each byte read with its two digits swapped."""
    return None if len(text) % 2 else bytes.fromhex("".join(text[i + 1] + text[i] for i in range(0, len(text), 2)))


def digits_only_decoder(text: str) -> bytes:
    """Each digit's value taken as ord(c) - ord("0") in four bits: right for 0-9, wrong for every letter."""
    nibbles = [(ord(c) - ord("0")) & 0x0F for c in text]
    return bytes(hi << 4 | lo for hi, lo in zip(nibbles[::2], nibbles[1::2], strict=True))


def first_digit_decimal(text: str) -> bytes | None:
    """A decoder whose table for a byte's first digit holds only 0-9, so a letter there is refused."""
    return None if any(c not in string.digits for c in text[0::2]) else bytes.fromhex(text)


def signed_pairs(text: str) -> bytes | None:
    """Each pair parsed as a signed byte (Rust's i8::from_str_radix, Go's ParseInt(pair, 16, 8)): above 7f is refused."""
    key = bytes.fromhex(text)
    return None if any(b > 0x7F for b in key) else key


def through_text(key: bytes) -> bytes:
    """Key bytes passed through a text string at a str-typed boundary: each byte above 7f becomes two in UTF-8."""
    return key.decode("latin-1").encode("utf-8")


def sign_tolerant_pairs(text: str) -> bytes | None:
    """Pairs parsed one at a time by an integer parser that takes a sign, behind a 64-character check."""
    if len(text) != 2 * KEY_BYTES:
        return None
    try:
        return bytes(int(text[i : i + 2], 16) for i in range(0, len(text), 2))
    except ValueError:
        return None


def one_integer(text: str) -> bytes | None:
    """The string read as one integer (int(key, 16) takes a sign and a 0x prefix) back to 32 bytes, behind a 64-character check."""
    if len(text) != 2 * KEY_BYTES:
        return None
    try:
        return int(text, 16).to_bytes(KEY_BYTES, "big")
    except (ValueError, OverflowError):
        return None


def white_space_skipped(text: str) -> bytes | None:
    """A check for 64 characters or more, then Python's bytes.fromhex, which skips white space between pairs."""
    if len(text) < 2 * KEY_BYTES:
        return None
    try:
        return bytes.fromhex(text)
    except ValueError:
        return None


def prefix_stripped(text: str) -> bytes | None:
    """A 64-character check, then a 0x prefix stripped and the rest decoded with no check on the key's length."""
    if len(text) != 2 * KEY_BYTES:
        return None
    return read_hex_key(text[2:] if text[:2] in ("0x", "0X") else text)


def hex_decoded_first(raw: bytes) -> bytes:
    """A raw-bytes entry point that hex-decodes 64 ASCII hex digits before its length check."""
    text = raw.decode("latin-1")
    return bytes.fromhex(text) if len(text) == 2 * KEY_BYTES and set(text) <= HEX_DIGITS else raw


SHORT_ROWS = ("master_key_31_bytes", "master_key_24_bytes", "master_key_16_bytes")

# Wrong length rules, shared by both kinds of entry point: each predicate, then the hex rows and the raw rows that
# show it. A hex entry point decodes strictly before applying the rule.
WRONG_LENGTH_RULES: dict[str, tuple[Callable[[int], bool], tuple[str, ...], tuple[str, ...]]] = {
    "no length check": (lambda n: True, SHORT_ROWS, ("raw_key_31_bytes",)),
    "off by one (31 bytes or more)": (lambda n: n >= KEY_BYTES - 1, ("master_key_31_bytes",), ("raw_key_31_bytes",)),
    # No hex row: no hex reject row decodes to 32 bytes or more, so on hex rows this is off by one.
    "31 or 32 bytes": (lambda n: n in (KEY_BYTES - 1, KEY_BYTES), (), ("raw_key_31_bytes",)),
    "16 bytes or more, the HKDF floor encryption.md once listed": (lambda n: n >= 16, SHORT_ROWS, ()),
    "AES key sizes (16, 24 or 32 bytes)": (lambda n: n in (16, 24, 32), ("master_key_24_bytes",), ("raw_key_24_bytes",)),
    "AES-192 and AES-256 key sizes (24 or 32 bytes)": (lambda n: n in (24, 32), ("master_key_24_bytes",), ("raw_key_24_bytes",)),
    "AES-128 and AES-256 key sizes (16 or 32 bytes)": (lambda n: n in (16, 32), ("master_key_16_bytes",), ("raw_key_16_bytes",)),
}

WRONG_HEX_ENTRY_POINTS: dict[str, tuple[Callable[[str], bytes | None], tuple[str, ...]]] = {
    "digits only, a pattern tested only on all-digit keys": (
        lambda t: read_hex_key(t) if set(t) <= set(string.digits) else None,
        (ACCEPT_ROW,),
    ),
    "uppercase hex digits only (^[0-9A-F]{64}$)": (lambda t: bytes.fromhex(t) if re.fullmatch("[0-9A-F]{64}", t) else None, (ACCEPT_ROW,)),
    "big-integer decode, which drops a leading 00 byte": (lambda t: behind(AT_LEAST_32, big_integer(t)), (ACCEPT_ROW,)),
    "a two's-complement big-integer decoder (BigInteger.toByteArray(), to_signed_bytes_be)": (
        lambda t: behind(AT_LEAST_32, twos_complement(t)),
        (ACCEPT_ROW,),
    ),
    "a two's-complement big-integer decoder padded to 32 bytes (int(key, 16).to_bytes(32, 'big', signed=True))": (
        padded_twos_complement,
        (FIRST_BYTE_80_ROW,),
    ),
    "Java's BigInteger.toByteArray() left-padded to 32 bytes, then a check that the key is exactly 32 bytes": (
        lambda t: behind(EXACTLY_32, java_padded(t)),
        (FIRST_BYTE_80_ROW,),
    ),
    "Java's BigInteger.toByteArray() left-padded to 32 bytes, then a check for 32 bytes or more": (
        lambda t: behind(AT_LEAST_32, java_padded(t)),
        (FIRST_BYTE_80_ROW,),
    ),
    "bytes reversed (a little-endian integer)": (lambda t: behind(AT_LEAST_32, bytes.fromhex(t)[::-1]), (ACCEPT_ROW,)),
    "the two digits of each byte swapped": (lambda t: behind(AT_LEAST_32, digits_swapped(t)), (ACCEPT_ROW,)),
    "a letter read as ord(c) - ord('0')": (lambda t: behind(AT_LEAST_32, digits_only_decoder(t)), (ACCEPT_ROW,)),
    "a byte's first digit read as decimal": (lambda t: behind(AT_LEAST_32, first_digit_decimal(t)), (ACCEPT_ROW,)),
    "a signed-byte pair parser, which refuses a pair above 7f": (lambda t: behind(AT_LEAST_32, signed_pairs(t)), (ACCEPT_ROW,)),
    "the key bytes passed through a text string (latin-1 in, UTF-8 out)": (
        lambda t: behind(AT_LEAST_32, through_text(bytes.fromhex(t))),
        (ACCEPT_ROW,),
    ),
    "Node's Buffer.from(key, 'hex'), then a check that the key is 32 bytes": (
        lambda t: behind(EXACTLY_32, buffer_from_hex(t)),
        ("master_key_odd_65_digits", "master_key_trailing_non_hex"),
    ),
    "a check that the length is even, then Node's Buffer.from(key, 'hex') and a check that the key is 32 bytes": (
        lambda t: behind(EXACTLY_32, buffer_from_hex(t)) if len(t) % 2 == 0 else None,
        ("master_key_trailing_non_hex",),
    ),
    "an odd string padded with a leading 0, then a check that the key is exactly 32 bytes": (
        lambda t: behind(EXACTLY_32, bytes.fromhex(t if len(t) % 2 == 0 else "0" + t)),
        ("master_key_odd_63_digits",),
    ),
    "a character that is not a hex digit read as 0": (
        lambda t: behind(EXACTLY_32, bytes.fromhex("".join(c if c in HEX_DIGITS else "0" for c in t))),
        ("master_key_non_hex_digit",),
    ),
    "Node's Buffer.from(key, 'hex'), with only the string's length checked": (
        lambda t: buffer_from_hex(t) if len(t) == 2 * KEY_BYTES else None,
        ("master_key_non_hex_digit",),
    ),
    "a pattern anchored only at the start (re.match) and a 64-character check, then Buffer.from": (
        lambda t: buffer_from_hex(t) if len(t) == 2 * KEY_BYTES and re.match("[0-9a-fA-F]+", t) else None,
        ("master_key_non_hex_digit",),
    ),
    "pairs parsed one at a time by an integer parser that takes a sign (u8::from_str_radix, int(pair, 16))": (
        sign_tolerant_pairs,
        ("master_key_plus_sign",),
    ),
    "the string read as one integer, int(key, 16), back to 32 bytes": (one_integer, ("master_key_plus_sign",)),
    "a 64-character check, then a 0x prefix stripped and the rest decoded": (prefix_stripped, ("master_key_0x_and_31_bytes",)),
    "a 64-character check on the string as given, then a trim and a strict decode": (
        lambda t: read_hex_key(t.strip()) if len(t) == 2 * KEY_BYTES else None,
        ("master_key_31_bytes_and_crlf",),
    ),
    "the string's ends stripped and its length checked, then bytes.fromhex, which skips white space between pairs": (
        lambda t: white_space_skipped(t.strip()),
        ("master_key_31_bytes_with_spaces",),
    ),
    "a short key padded to 32 bytes": (
        lambda t: key.ljust(KEY_BYTES, b"\0") if (key := read_hex_key(t)) is not None else None,
        SHORT_ROWS,
    ),
    **{
        label: (lambda t, accepts=accepts: behind(accepts, read_hex_key(t)), rows)
        for label, (accepts, rows, _) in WRONG_LENGTH_RULES.items()
        if rows
    },
}

WRONG_RAW_ENTRY_POINTS: dict[str, tuple[Callable[[bytes], bytes | None], tuple[str, ...]]] = {
    "32 bytes or more, as a hex entry point may accept": (
        lambda k: behind(AT_LEAST_32, k),
        ("raw_key_33_bytes", "raw_key_ascii_hex_string"),
    ),
    "64 hex digits hex-decoded first": (
        lambda k: behind(EXACTLY_32, hex_decoded_first(k)),
        ("raw_key_ascii_hex_string",),
    ),
    "a short key padded to 32 bytes": (lambda k: k.ljust(KEY_BYTES, b"\0") if len(k) <= KEY_BYTES else None, ("raw_key_31_bytes",)),
    # Fed the accept row's key as bytes, as a test drives a raw-bytes entry point with a decoded hex key.
    "the key bytes passed through a text string, then a check that they are 32 bytes": (
        lambda k: behind(EXACTLY_32, through_text(k)),
        (ACCEPT_ROW,),
    ),
    **{label: (lambda k, accepts=accepts: behind(accepts, k), rows) for label, (accepts, _, rows) in WRONG_LENGTH_RULES.items() if rows},
}


def verdict(key: bytes | None) -> str | None:
    """What an entry point's answer pins: None for a refusal, else the fingerprint of the key it derives for "default"."""
    return None if key is None else key_fingerprint(derive_encryption_key(key, DEFAULT_TENANT_ID))


def verify_wrong_entry_points(rows: dict[str, tuple[str, dict]]) -> int:
    """Return the number of wrong entry points that judge a row they list correctly (or name a row of the wrong kind).

    A raw-bytes entry point may list an accept row, which it is fed as decoded bytes. A missing row is skipped: the
    frozen-name guard reports it.
    """
    failures = 0
    accept_rows = set(FROZEN_MASTER_KEY_INPUT_VECTORS["accept_vectors"])
    raw_rows = set(FROZEN_MASTER_KEY_INPUT_VECTORS["raw_reject_vectors"])
    hex_rows = accept_rows | set(FROZEN_MASTER_KEY_INPUT_VECTORS["reject_vectors"])
    listed: set[str] = set()
    for entry_points, kind in ((WRONG_HEX_ENTRY_POINTS, hex_rows), (WRONG_RAW_ENTRY_POINTS, raw_rows | accept_rows)):
        for label, (entry_point, targets) in entry_points.items():
            for target in targets:
                listed.add(target)
                if target not in kind:
                    print(f"FAIL wrong entry point {label!r} lists {target}, which is not a frozen row of its kind")
                    failures += 1
                    continue
                if target not in rows:
                    continue
                table, row = rows[target]
                try:
                    if table == "raw_reject_vectors":
                        given: str | bytes = bytes.fromhex(row["raw_key_hex"])
                    elif entry_points is WRONG_RAW_ENTRY_POINTS:
                        given = bytes.fromhex(row["master_key_hex"])
                    else:
                        given = row["master_key_hex"]
                    got = verdict(entry_point(given))
                except (ValueError, OverflowError) as exc:
                    print(f"FAIL wrong entry point {label!r} raised on {target}: {exc}")
                    failures += 1
                    continue
                if got == row.get("derived_key_fingerprint_hex"):
                    print(
                        f"FAIL wrong entry point {label!r} judges {target} correctly, so the row no longer shows the "
                        "mistake its note names"
                    )
                    failures += 1
    # A row a later version adds needs a wrong entry point too, or its note's claims go unchecked.
    unshown = sorted((hex_rows | raw_rows | set(rows)) - listed)
    if unshown:
        print(f"FAIL no wrong entry point shows why these rows exist: {unshown}")
        failures += 1
    return failures


# Keyring configurations (spec/encryption.md § Key Rotation (Keyring), ENC-7 and ENC-9): a current master key and the
# decrypt-only keys a keyring is loaded from, and whether a conforming SDK accepts it at load. Names are frozen and a row
# has exactly these fields.
FROZEN_KEYRING_CONFIGURATIONS = {
    "keyring_three_decrypt_only_keys": "accept",
    "keyring_four_decrypt_only_keys": "reject",
    "keyring_current_key_decrypt_only": "reject",
    "keyring_current_key_decrypt_only_uppercase": "reject",
}
KEYRING_CONFIGURATION_FIELDS = frozenset({"name", "current_master_key_hex", "decrypt_only_master_keys_hex", "verdict", "note"})
DECRYPT_ONLY_CAP = 3


def keyring_loads(current: str, decrypt_only: list[str], *, lenient: bool, cap: int = DECRYPT_ONLY_CAP, compare: bool = True) -> bool:
    """Whether an SDK accepts the configuration at load, under one reading of rule 1 (`read_hex_key`).

    A conforming SDK refuses a key it cannot read, more than `cap` decrypt-only keys, and the current key among the
    decrypt-only keys, compared as key bytes. `cap` and `compare` let a wrong entry point loosen one of those rules.
    """
    keys = [read_hex_key(text, lenient=lenient) for text in (current, *decrypt_only)]
    if any(key is None or len(key) != KEY_BYTES for key in keys):
        return False
    return len(decrypt_only) <= cap and not (compare and keys[0] in keys[1:])


# Plausible wrong keyring loaders, one per mistake a configuration note names: each returns whether it accepts the
# configuration at load and must misjudge every row it lists; it lists a row only if that row's note names its mistake.
# Each reads uppercase hex as lowercase, the reading under which every mistake shows.
WRONG_KEYRING_LOADS: dict[str, tuple[Callable[[str, list[str]], bool], tuple[str, ...]]] = {
    "no cap on decrypt-only keys": (
        lambda c, d: keyring_loads(c, d, lenient=True, cap=len(d)),
        ("keyring_four_decrypt_only_keys",),
    ),
    "the first three decrypt-only keys kept and the rest dropped": (
        lambda c, d: keyring_loads(c, d[:DECRYPT_ONLY_CAP], lenient=True),
        ("keyring_four_decrypt_only_keys",),
    ),
    "a cap of two decrypt-only keys": (
        lambda c, d: keyring_loads(c, d, lenient=True, cap=DECRYPT_ONLY_CAP - 1),
        ("keyring_three_decrypt_only_keys",),
    ),
    "no check that the current key is not a decrypt-only key": (
        lambda c, d: keyring_loads(c, d, lenient=True, compare=False),
        ("keyring_current_key_decrypt_only", "keyring_current_key_decrypt_only_uppercase"),
    ),
    "the current key compared with each decrypt-only key as a string": (
        lambda c, d: keyring_loads(c, d, lenient=True, compare=False) and c not in d,
        ("keyring_current_key_decrypt_only_uppercase",),
    ),
    "the current key compared with the first decrypt-only key only": (
        lambda c, d: keyring_loads(c, d, lenient=True, compare=False) and keyring_loads(c, d[:1], lenient=True),
        ("keyring_current_key_decrypt_only",),
    ),
    "the current key compared with the last decrypt-only key only": (
        lambda c, d: keyring_loads(c, d, lenient=True, compare=False) and keyring_loads(c, d[-1:], lenient=True),
        ("keyring_current_key_decrypt_only",),
    ),
}


def verify_keyring_configurations(keyring: dict | None) -> int:
    """Return the number of failed keyring configuration checks (spec/encryption.md ENC-7 and ENC-9).

    Each row's keys must each be a valid 32-byte key once uppercase is read as lowercase, with no key twice in the
    decrypt-only list, and only a repeat of the current key in another case may hold uppercase, so a row decides only
    the keyring rule it targets. Its verdict must be what a conforming load gives under each reading of rule 1, so no
    row settles uppercase handling; then each wrong loader must misjudge the rows it lists.
    """
    block = keyring.get("configuration") if isinstance(keyring, dict) else None
    vectors = block.get("vectors") if isinstance(block, dict) else None
    if not isinstance(vectors, list) or not all(isinstance(row, dict) and isinstance(row.get("name"), str) for row in vectors):
        print("FAIL keyring configuration rows missing, or a row that is not an object with a string name")
        return 1
    failures = 0
    if not isinstance(block.get("note"), str) or not block["note"].strip():
        print("FAIL keyring configuration: note must be a non-empty string")
        failures += 1
    missing = set(FROZEN_KEYRING_CONFIGURATIONS) - {row["name"] for row in vectors}
    if missing:
        print(f"FAIL frozen keyring configuration rows missing (append-only, never rename): {sorted(missing)}")
        failures += 1
    if moved := frozen_order_failure("keyring.configuration.vectors", vectors, tuple(FROZEN_KEYRING_CONFIGURATIONS)):
        print(moved)
        failures += 1
    rows: dict[str, dict] = {}
    for row in vectors:
        name = row.get("name")
        label = f"keyring configuration {name}"
        if set(row) != KEYRING_CONFIGURATION_FIELDS:
            print(f"FAIL {label}: fields {sorted(row)} != {sorted(KEYRING_CONFIGURATION_FIELDS)}")
            failures += 1
            continue
        if name in rows:
            print(f"FAIL {label}: duplicate name")
            failures += 1
            continue
        current, decrypt_only = row["current_master_key_hex"], row["decrypt_only_master_keys_hex"]
        if not (
            isinstance(row["note"], str) and row["note"].strip() and isinstance(current, str) and isinstance(decrypt_only, list)
            and all(isinstance(k, str) and set(k) <= ROW_CHARACTERS for k in decrypt_only) and set(current) <= ROW_CHARACTERS
        ):
            print(f"FAIL {label}: needs a non-empty note, a key string and a list of key strings of printable ASCII")
            failures += 1
            continue
        if row["verdict"] != FROZEN_KEYRING_CONFIGURATIONS.get(name, row["verdict"]) or row["verdict"] not in ("accept", "reject"):
            print(f"FAIL {label}: verdict must be accept or reject, and the one its frozen name declares")
            failures += 1
            continue
        read = [read_hex_key(text, lenient=True) for text in (current, *decrypt_only)]
        if any(key is None or len(key) != KEY_BYTES for key in read):
            print(f"FAIL {label}: every key must be a valid {KEY_BYTES}-byte key once uppercase is read, so only the keyring rules decide the row")
            failures += 1
            continue
        if any(read_hex_key(text) is None and (text == current or text.lower() != current) for text in (current, *decrypt_only)):
            print(f"FAIL {label}: only a repeat of the current key in another case may need the lenient reading of rule 1")
            failures += 1
            continue
        if len(set(read[1:])) != len(read) - 1:
            print(f"FAIL {label}: a key appears twice in the decrypt-only list, which the spec leaves open")
            failures += 1
            continue
        rows[name] = row
        wrong = [r for r, lenient in READINGS.items() if ("accept" if keyring_loads(current, decrypt_only, lenient=lenient) else "reject") != row["verdict"]]
        if wrong:
            print(f"FAIL {label}: a conforming load that {wrong[0]} does not {row['verdict']} it")
            failures += 1
            continue
        print(f"ok  {label} ({row['verdict']})")
    listed: set[str] = set()
    for label, (loads, targets) in WRONG_KEYRING_LOADS.items():
        for target in targets:
            listed.add(target)
            if target not in FROZEN_KEYRING_CONFIGURATIONS:
                print(f"FAIL wrong keyring loader {label!r} lists {target}, which is not a frozen row of its table")
                failures += 1
                continue
            row = rows.get(target)
            if row is None:
                continue  # the frozen-name or row guards report it
            if ("accept" if loads(row["current_master_key_hex"], row["decrypt_only_master_keys_hex"]) else "reject") == row["verdict"]:
                print(f"FAIL wrong keyring loader {label!r} judges {target} correctly, so the row no longer shows the mistake its note names")
                failures += 1
    unshown = sorted((set(FROZEN_KEYRING_CONFIGURATIONS) | set(rows)) - listed)
    if unshown:
        print(f"FAIL no wrong keyring loader shows why these rows exist: {unshown}")
        failures += 1
    return failures


def verify_master_key_input(block: dict | None, default_tenant: dict | None, main_master_key_hex: str, *, seal: bool) -> int:
    """Return the number of failed master key input checks (spec/intent-presets.md § Master Key Input).

    Accept rows must be accepted, and reject rows refused, under every conformant length rule and both readings of
    what rule 1 leaves open; raw reject rows must not be 32 bytes. An accept row shares neither its master key nor
    its cache_key or plaintext with a default_tenant entry or another accept row, so a test can read them under
    different keys (PRE-51). Each accept row's fingerprint, AAD and (with `cryptography`) seal are checked under the
    key its own master key derives, then each wrong entry point must misjudge the rows it lists.
    """
    if block is None:
        print("FAIL master_key_input rows missing")
        return 1
    if block.get("tenant_id") != DEFAULT_TENANT_ID:
        print(f"FAIL master_key_input: tenant_id must be the literal {DEFAULT_TENANT_ID!r}; got {block.get('tenant_id')!r}")
        return 1
    failures = 0
    # A row joins `rows`, and so the wrong-entry-point check, once its fields, name, note and characters pass, so a row
    # whose verdict is wrong is still checked against the models. A model that cannot parse such a row (an odd-length
    # accept row, say) raises, and verify_wrong_entry_points reports that as a failure, not a traceback.
    dt_vectors = (default_tenant or {}).get("vectors", [])
    accept_vectors = block.get("accept_vectors", [])
    rows: dict[str, tuple[str, dict]] = {}
    seen: set[str] = set()
    for table, frozen in FROZEN_MASTER_KEY_INPUT_VECTORS.items():
        if moved := frozen_order_failure(f"master_key_input.{table}", block.get(table, []), frozen):
            print(moved)
            failures += 1
        for row in block.get(table, []):
            name = row.get("name")
            label = f"master_key_input {name}"
            if set(row) != MASTER_KEY_INPUT_FIELDS[table]:
                print(f"FAIL {label}: fields {sorted(row)} != {sorted(MASTER_KEY_INPUT_FIELDS[table])}")
                failures += 1
                continue
            if name in seen:
                print(f"FAIL {label}: duplicate name")
                failures += 1
                continue
            seen.add(name)
            if not isinstance(row["note"], str) or not row["note"].strip():
                print(f"FAIL {label}: note must be a non-empty string")
                failures += 1
                continue
            if table == "raw_reject_vectors":
                raw_hex = row["raw_key_hex"]
                if len(raw_hex) % 2 or not set(raw_hex) <= LOWER_HEX:
                    print(f"FAIL {label}: raw_key_hex must be lowercase hex")
                    failures += 1
                    continue
                rows[name] = (table, row)
                if len(bytes.fromhex(raw_hex)) == KEY_BYTES:
                    print(f"FAIL {label}: a raw-bytes entry point takes exactly {KEY_BYTES} bytes, so this row is no reject")
                    failures += 1
                else:
                    print(f"ok  {label}")
                continue
            text = row["master_key_hex"]
            if not set(text) <= ROW_CHARACTERS:
                print(f"FAIL {label}: holds a character other than printable ASCII and ASCII white space")
                failures += 1
                continue
            rows[name] = (table, row)
            wanted = table == "accept_vectors"
            others = [v for v in accept_vectors if v is not row]
            if wanted and (
                text in [main_master_key_hex, *(v.get("master_key_hex") for v in others)]
                or any(
                    row["cache_key"] == v.get("cache_key") or row["plaintext_hex"] == v.get("plaintext_hex")
                    for v in dt_vectors + others
                )
            ):
                print(
                    f"FAIL {label}: shares its master key, cache_key or plaintext with a default_tenant entry or another "
                    "accept row, so a test cannot read them under different keys"
                )
                failures += 1
                continue
            wrong = [
                f"an entry point that takes {rule} and {reading}"
                for reading, lenient in READINGS.items()
                for rule, accepts in HEX_LENGTH_RULES.items()
                if ((key := read_hex_key(text, lenient=lenient)) is not None and accepts(len(key))) != wanted
            ]
            if wrong:
                print(f"FAIL {label}: {wrong[0]} {'refuses' if wanted else 'accepts'} it, so the row decides what the spec leaves open")
                failures += 1
                continue
            if not wanted:
                print(f"ok  {label}")
                continue
            derived = derive_encryption_key(bytes.fromhex(text), block["tenant_id"])
            if key_fingerprint(derived) != row["derived_key_fingerprint_hex"]:
                print(f"FAIL {label}: derived-key fingerprint mismatch (derived {key_fingerprint(derived)})")
                failures += 1
                continue
            if verify_sealed_vector(label, row, block["tenant_id"], [derived], seal=seal) is None:
                failures += 1
                continue
            print(f"ok  {label}" if seal else f"ok  {label} (AAD + fingerprint only)")
    return failures + verify_wrong_entry_points(rows)


def verify(doc: dict, *, require_seal: bool) -> int:
    failures = 0

    unknown = sorted(set(vector_tables(doc)) - VECTOR_TABLES)
    if unknown:
        print(f"FAIL unknown vector table(s) {unknown}: tools/conformance.py would index rows this verifier skips")
        return 1

    missing = set(FROZEN_VECTOR_NAMES) - {v["name"] for v in doc["vectors"]}
    if missing:
        print(f"FAIL frozen vectors missing (append-only file — never remove/rename): {sorted(missing)}")
        return 1
    if moved := frozen_order_failure("vectors", doc["vectors"], FROZEN_VECTOR_NAMES):
        print(moved)
        failures += 1

    key = derive_encryption_key(bytes.fromhex(doc["master_key_hex"]), doc["tenant_id"])
    if key_fingerprint(key) != doc["derived_key_fingerprint_hex"]:
        print(f"FAIL key fingerprint: derived {key_fingerprint(key)}, pinned {doc['derived_key_fingerprint_hex']}")
        return 1
    print(f"ok  key fingerprint {doc['derived_key_fingerprint_hex']}")

    try:
        # Probe only: decrypt_with_keyring imports these again where it uses them.
        from cryptography.exceptions import InvalidTag  # noqa: F401, PLC0415
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: F401, PLC0415

        seal = True
    except ImportError:
        if require_seal:
            print("FAIL --require-seal set but `cryptography` is not installed")
            return 1
        seal = False
        print("note: `cryptography` not installed — AAD reconstruction only, AES-GCM seal NOT verified")

    for vec in doc["vectors"]:
        name = vec["name"]
        if verify_sealed_vector(name, vec, doc["tenant_id"], [key], seal=seal, original_type=vec.get("original_type")) is None:
            failures += 1
            continue
        if name in WRITER_SHAPES and (why := writer_shape_failure(vec)):
            print(f"FAIL {name}: {why}")
            failures += 1
            continue
        print(f"ok  {name}")

    failures += verify_aad_rejects(doc, key, seal=seal)
    failures += verify_decrypted_containers(doc, key, seal=seal)
    failures += verify_keyring(doc.get("keyring"), seal=seal)
    failures += verify_keyring_configurations(doc.get("keyring"))
    failures += verify_default_tenant(doc.get("default_tenant"), bytes.fromhex(doc["master_key_hex"]), seal=seal)
    failures += verify_master_key_input(doc.get("master_key_input"), doc.get("default_tenant"), doc["master_key_hex"], seal=seal)

    if failures:
        print(f"{failures} vector(s) FAILED")
        return 1
    mode = "AAD + AES-GCM seal" if seal else "AAD-only"
    keyring_count = len(doc.get("keyring", {}).get("vectors", []))
    default_count = len(doc.get("default_tenant", {}).get("vectors", []))
    master_key_count = sum(len(doc["master_key_input"][table]) for table in FROZEN_MASTER_KEY_INPUT_VECTORS)
    print(
        f"all {len(doc['vectors'])} encryption vectors plus {len(doc['aad_reject_vectors'])} AAD reject, "
        f"{len(doc['decrypted_container']['vectors'])} post-decryption container, {keyring_count} "
        f"keyring, {len(doc['keyring']['configuration']['vectors'])} keyring configuration, {default_count} default-tenant "
        f"and {master_key_count} master key input vectors verified ({mode})"
    )
    return 0


def main() -> int:
    require_seal = "--require-seal" in sys.argv[1:]
    return verify(json.loads(VECTORS_PATH.read_text()), require_seal=require_seal)


if __name__ == "__main__":
    sys.exit(main())
