#!/usr/bin/env python3
"""Verify test-vectors/encryption.json against spec/encryption.md.

Stdlib-only checks (always run):
  - HKDF-SHA256 key derivation reproduces the pinned key fingerprint
    (ground-truth continuity with the published vectors and with
    tools/interop-reference.py, which pins the same fingerprint).
  - Every vector's `aad_hex` reconstructs byte-for-byte from its fields
    (tenant_id, cache_key, format, compressed, optional original_type),
    including the frozen ASCII boolean tokens `True` / `False`.
  - Keyring vectors: entry derivation, metadata, AAD, and fingerprint selection
    pinned to the HKDF-derived per-tenant encryption key, never the master key.
  - Master key input rows (spec/intent-presets.md § Master Key Input): each accept
    row is accepted, and each reject row refused, by a conformant hex entry point
    whether it takes exactly 32 bytes or 32 and more, and under both readings of
    what rule 1 leaves open (an uppercase digit, white space, a 0x prefix); each raw
    reject row is not 32 bytes; an accept row shares neither its master key nor its
    cache_key or plaintext with a default_tenant entry or the other accept row; each accept
    row's fingerprint and AAD. Each mistake a
    row's note names is modelled in WRONG_HEX_ENTRY_POINTS or WRONG_RAW_ENTRY_POINTS
    and must misjudge the rows it lists, so editing a row until it no longer shows
    the mistake goes red.
  - AAD reject rows (spec/encryption.md, ENC-1): each presents a published vector's
    ciphertext under AAD inputs that differ from its own in exactly one component, and
    with `cryptography` the ciphertext fails authentication under them, so a reader
    that does not retry with an alternative AAD input refuses every row.
  - No vector table outside the ones verified here: tools/conformance.py indexes
    every list under a key ending in "vectors".
  - The vector count never drops below the frozen floor — vectors are
    ground truth and may be added, never removed.

Seal check (runs when `cryptography` is installed; `--require-seal` makes
its absence a hard failure — CI passes the flag in the optional-deps step):
  - Every vector's `ciphertext_hex` decrypts under the derived key + AAD to
    `plaintext_hex`. (No re-seal comparison: AES-GCM is deterministic per
    (key, nonce, aad, plaintext), so a successful decrypt + plaintext match
    already proves the seal.)
  - Keyring vectors decrypt under [k2, k1] at the declared entry, and the k1 entry
    is rejected under [k2] alone (sequential-attempt path).
  - Each master key input accept row decrypts under the key its own master key
    derives for tenant "default".

Exit status is non-zero on any mismatch. Vectors are frozen ground truth and
are never regenerated by this tool.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
import string
import sys
from collections.abc import Callable, Iterator
from pathlib import Path

VECTORS_PATH = Path(__file__).resolve().parent.parent / "test-vectors" / "encryption.json"

# Frozen protocol constants (spec/encryption.md, "compressed tokens").
TOKEN_TRUE = b"True"
TOKEN_FALSE = b"False"

# Vectors are append-only ground truth: published names may never disappear.
# Removal or rename (even with a same-count replacement) must go red in CI.
FROZEN_VECTOR_NAMES = frozenset(
    {
        "basic_bytes",
        "special_cache_key",
        "compressed_basic",
        "arrow_uncompressed",
        "arrow_compressed",
        "orjson_uncompressed",
        "original_type_numpy",
        "standard_serializer_default",
        "standard_serializer_integrity_off",
    }
)

# format registry per spec/encryption.md — vectors must not invent tokens.
FORMAT_REGISTRY = frozenset({"msgpack", "orjson", "arrow"})

# Keyring conformance vectors: frozen name -> the entry that sealed it. The
# conformance keyring is current=k2 with decrypt-only k1 (KEYRING_ORDER).
FROZEN_KEYRING_VECTORS = {"encrypted_with_k1": "k1", "encrypted_with_k2": "k2"}
FROZEN_KEYRING_VECTOR_NAMES = frozenset(FROZEN_KEYRING_VECTORS)
KEYRING_ORDER = ("k2", "k1")

# Default-tenant conformance (spec/intent-presets.md § Master Key Input rule 5): the
# tenant MUST be the literal "default" and the vector names are frozen like the rest.
DEFAULT_TENANT_ID = "default"
FROZEN_DEFAULT_TENANT_VECTOR_NAMES = frozenset({"default_tenant_interop"})

# Master key input (spec/intent-presets.md § Master Key Input): hex keys an entry point must accept or refuse, and raw
# keys a raw-bytes entry point must refuse. Names are frozen per table, and each table's rows have exactly its fields.
FROZEN_MASTER_KEY_INPUT_VECTORS = {
    "accept_vectors": frozenset({"master_key_every_hex_digit", "master_key_first_byte_80"}),
    "reject_vectors": frozenset(
        {
            "master_key_odd_65_digits",
            "master_key_odd_63_digits",
            "master_key_non_hex_digit",
            "master_key_trailing_non_hex",
            "master_key_plus_sign",
            "master_key_31_bytes",
            "master_key_24_bytes",
            "master_key_16_bytes",
            "master_key_31_bytes_and_crlf",
            "master_key_31_bytes_with_spaces",
            "master_key_0x_and_31_bytes",
        }
    ),
    "raw_reject_vectors": frozenset(
        {"raw_key_31_bytes", "raw_key_24_bytes", "raw_key_16_bytes", "raw_key_33_bytes", "raw_key_ascii_hex_string"}
    ),
}
MASTER_KEY_INPUT_FIELDS = {
    "accept_vectors": frozenset(
        {
            "name",
            "master_key_hex",
            "derived_key_fingerprint_hex",
            "plaintext_hex",
            "cache_key",
            "format",
            "compressed",
            "aad_hex",
            "ciphertext_hex",
            "note",
        }
    ),
    "reject_vectors": frozenset({"name", "master_key_hex", "note"}),
    "raw_reject_vectors": frozenset({"name", "raw_key_hex", "note"}),
}
KEY_BYTES = 32
# Rule 3 lets a hex entry point accept exactly 32 bytes or 32 and more, so every row must get one verdict under both.
EXACTLY, OR_MORE = "exactly 32 bytes", "32 bytes or more"
HEX_LENGTH_RULES: dict[str, Callable[[int], bool]] = {
    EXACTLY: lambda n: n == KEY_BYTES,
    OR_MORE: lambda n: n >= KEY_BYTES,
}
LOWER_HEX = frozenset("0123456789abcdef")
# Rule 1 does not say whether a key may hold uppercase hex digits, white space or a 0x prefix, so every row must get
# one verdict under both readings of it: each reading, and whether read_hex_key reads leniently under it. The white
# space is the ASCII set Python's bytes.fromhex skips, which JavaScript's trim() strips too.
READINGS = {
    "refuses uppercase digits, white space and a 0x prefix": False,
    "drops white space and a 0x prefix and reads uppercase as lowercase": True,
}
ASCII_WHITE_SPACE = frozenset(" \t\n\r\x0b\x0c")
# Rows hold printable ASCII and that white space only, so none turns on how a parser treats any other character
# (trim() also strips non-ASCII white space and U+FEFF).
ROW_CHARACTERS = frozenset(string.printable)

# AAD reject rows (spec/encryption.md § AAD v0x03 Format, ENC-1): a vector's ciphertext presented under AAD inputs that
# differ from its own in one component. A reader that retries with an alternative AAD input decrypts a row; a reader
# that does not fails authentication. Names are frozen, and a row has exactly these fields, original_type optional.
FROZEN_AAD_REJECT_VECTOR_NAMES = frozenset(
    {
        "aad_compressed_false_sealed_true",
        "aad_compressed_true_sealed_false",
        "aad_format_msgpack_sealed_arrow",
        "aad_without_original_type_sealed_with",
        "aad_with_original_type_sealed_without",
        "aad_key_with_prefix_sealed_without",
    }
)
AAD_REJECT_FIELDS = frozenset({"name", "sealed_as", "cache_key", "format", "compressed", "aad_hex", "ciphertext_hex", "note"})
AAD_INPUTS = ("cache_key", "format", "compressed", "original_type")

# Every vector table this file may hold. tools/conformance.py indexes each list under a key ending in "vectors", so a
# table missing here would publish rows that nothing verifies.
VECTOR_TABLES = frozenset(
    {"vectors", "aad_reject_vectors", "keyring.vectors", "default_tenant.vectors"}
    | {f"master_key_input.{t}" for t in FROZEN_MASTER_KEY_INPUT_VECTORS}
)


def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int = 32) -> bytes:
    """RFC 5869 HKDF-Extract + Expand with SHA-256."""
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
        i += 1
    return okm[:length]


def construct_salt(domain: str, tenant_salt: str) -> bytes:
    d, t = domain.encode("utf-8"), tenant_salt.encode("utf-8")
    return b"cachekit_v1_" + bytes([len(d)]) + d + len(t).to_bytes(2, "big") + t


def derive_encryption_key(master_key: bytes, tenant_id: str) -> bytes:
    return hkdf_sha256(master_key, construct_salt("encryption", tenant_id), b"encryption")


def key_fingerprint(key: bytes) -> str:
    return hashlib.sha256(b"key_fingerprint_v1" + key).digest()[:16].hex()


def decrypt_with_keyring(keys: list[bytes], ciphertext: bytes, aad: bytes) -> tuple[int, bytes] | None:
    """Try each key once, in keyring order, with identical authenticated data."""
    from cryptography.exceptions import InvalidTag  # noqa: PLC0415
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: PLC0415

    nonce, sealed = ciphertext[:12], ciphertext[12:]
    for index, key in enumerate(keys):
        try:
            return index, AESGCM(key).decrypt(nonce, sealed, aad)
        except InvalidTag:
            continue
    return None


def aad_v3(tenant_id: str, cache_key: str, *, fmt: str, compressed: bool, original_type: str | None = None) -> bytes:
    """AAD v0x03 per spec/encryption.md — 4-byte BE length-prefixed components.

    Unlike interop-reference.py's aad_v3, this supports the optional fifth
    original_type component. The interop copy omits it DELIBERATELY — interop
    AAD is exactly four components; do not "harmonize" the two.
    """
    components = [
        tenant_id.encode("utf-8"),
        cache_key.encode("utf-8"),
        fmt.encode("utf-8"),
        TOKEN_TRUE if compressed else TOKEN_FALSE,
    ]
    if original_type is not None:
        components.append(original_type.encode("utf-8"))
    aad = bytearray([0x03])
    for component in components:
        aad += len(component).to_bytes(4, "big") + component
    return bytes(aad)


def verify_sealed_vector(
    label: str, vec: dict, tenant_id: str, keys: list[bytes], *, seal: bool, original_type: str | None = None
) -> tuple[bytes, int | None] | None:
    """Per-vector conformance body shared by every block: metadata, AAD rebuild, then decrypt + plaintext.

    Prints a FAIL line and returns None on the first mismatch. Otherwise returns the
    rebuilt AAD and the index of the key in `keys` that decrypted (None when `seal`
    is off). The caller prints the ok-line, so block-specific guards run first.
    """
    if not isinstance(vec["compressed"], bool) or vec["format"] not in FORMAT_REGISTRY:
        print(f"FAIL {label}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})")
        return None
    aad = aad_v3(tenant_id, vec["cache_key"], fmt=vec["format"], compressed=vec["compressed"], original_type=original_type)
    if aad.hex() != vec["aad_hex"]:
        print(f"FAIL {label}: AAD mismatch\n  expected {vec['aad_hex']}\n  rebuilt  {aad.hex()}")
        return None
    if not seal:
        return aad, None
    result = decrypt_with_keyring(keys, bytes.fromhex(vec["ciphertext_hex"]), aad)
    if result is None:
        print(f"FAIL {label}: decrypt failed (InvalidTag — AAD/key/ciphertext mismatch)")
        return None
    index, plaintext = result
    if plaintext.hex() != vec["plaintext_hex"]:
        print(f"FAIL {label}: plaintext mismatch\n  expected {vec['plaintext_hex']}\n  got      {plaintext.hex()}")
        return None
    return aad, index


def verify_aad_rejects(doc: dict, key: bytes, *, seal: bool) -> int:
    """Return the number of failed AAD reject rows (spec/encryption.md ENC-1: readers never retry with another AAD input).

    Each row names the vector in `vectors` whose ciphertext it carries (`sealed_as`) and presents AAD inputs that differ
    from that vector's in exactly one of cache_key, format, compressed and original_type (present or absent). Its
    aad_hex must rebuild from what it presents. With `cryptography`, the ciphertext must fail authentication under the
    presented AAD, which the one-input rule already implies; the check shows the row's claim with the cipher itself.
    """
    rows = doc.get("aad_reject_vectors")
    if not isinstance(rows, list):
        print("FAIL aad_reject_vectors missing")
        return 1
    failures = 0
    missing = FROZEN_AAD_REJECT_VECTOR_NAMES - {row.get("name") for row in rows}
    if missing:
        print(f"FAIL frozen aad_reject_vectors missing (append-only, never rename): {sorted(missing)}")
        failures += 1
    sealed = {v["name"]: v for v in doc["vectors"]}
    seen: set[str] = set()
    for row in rows:
        name = row.get("name")
        label = f"aad_reject {name}"
        if set(row) - {"original_type"} != AAD_REJECT_FIELDS:
            print(f"FAIL {label}: fields {sorted(row)} != {sorted(AAD_REJECT_FIELDS)} (original_type optional)")
            failures += 1
            continue
        if name in seen:
            print(f"FAIL {label}: duplicate name")
            failures += 1
            continue
        seen.add(name)
        if not isinstance(row["note"], str) or not row["note"].strip():
            print(f"FAIL {label}: note must be a non-empty string")
            failures += 1
            continue
        if not isinstance(row["compressed"], bool) or row["format"] not in FORMAT_REGISTRY:
            print(f"FAIL {label}: invalid metadata (compressed must be a JSON boolean, format must be in {sorted(FORMAT_REGISTRY)})")
            failures += 1
            continue
        base = sealed.get(row["sealed_as"])
        if base is None:
            print(f"FAIL {label}: sealed_as names no vector in `vectors`: {row['sealed_as']!r}")
            failures += 1
            continue
        if row["ciphertext_hex"] != base["ciphertext_hex"]:
            print(f"FAIL {label}: ciphertext is not {row['sealed_as']}'s")
            failures += 1
            continue
        aad = aad_v3(doc["tenant_id"], row["cache_key"], fmt=row["format"], compressed=row["compressed"], original_type=row.get("original_type"))
        if aad.hex() != row["aad_hex"]:
            print(f"FAIL {label}: AAD mismatch\n  expected {row['aad_hex']}\n  rebuilt  {aad.hex()}")
            failures += 1
            continue
        differs = [f for f in AAD_INPUTS if (f in row) != (f in base) or row.get(f) != base.get(f)]
        if len(differs) != 1:
            print(f"FAIL {label}: differs from {row['sealed_as']} in {differs or 'no'} AAD input(s); a row presents exactly one alternative")
            failures += 1
            continue
        if seal and decrypt_with_keyring([key], bytes.fromhex(row["ciphertext_hex"]), aad) is not None:
            print(f"FAIL {label}: decrypts under the AAD it presents, so a reader that never retries returns a value")
            failures += 1
            continue
        print(f"ok  {label} ({differs[0]} differs{'; authentication fails' if seal else ''})")
    return failures


def verify_keyring(keyring: dict | None, *, seal: bool) -> int:
    """Return the number of failed keyring checks (spec/encryption.md § Key Rotation).

    Entry derivation, metadata, AAD reconstruction and fingerprint selection are
    stdlib and always run; only the decrypt attempts need `cryptography` (`seal`).
    """
    if keyring is None:
        print("FAIL keyring vectors missing")
        return 1
    failures = 0

    entries = keyring.get("entries", [])
    ids = [entry.get("id") for entry in entries]
    if len(set(ids)) != len(ids) or not set(KEYRING_ORDER) <= set(ids):
        print(f"FAIL keyring entries must have unique ids including {sorted(KEYRING_ORDER)}; got {ids}")
        return failures + 1
    derived_keys: dict[str, bytes] = {}
    for entry in entries:
        derived = derive_encryption_key(bytes.fromhex(entry["master_key_hex"]), keyring["tenant_id"])
        derived_keys[entry["id"]] = derived
        if key_fingerprint(derived) != entry["derived_key_fingerprint_hex"]:
            print(f"FAIL keyring {entry['id']}: derived-key fingerprint mismatch")
            failures += 1
    # Selection table for the per-entry-identity path: fingerprints of the
    # HKDF-DERIVED per-tenant encryption keys only — a master-key fingerprint
    # is deliberately not in here, so a vector carrying one cannot select.
    derived_fingerprints = {key_fingerprint(derived): key_id for key_id, derived in derived_keys.items()}

    vectors = keyring.get("vectors", [])
    missing = FROZEN_KEYRING_VECTOR_NAMES - {vec.get("name") for vec in vectors}
    if missing:
        print(f"FAIL frozen keyring vectors missing: {sorted(missing)}")
        failures += 1
    if not seal:
        print("note: keyring decrypt checks require cryptography — AAD, metadata and fingerprint selection only")

    full_keyring = [derived_keys[key_id] for key_id in KEYRING_ORDER]
    current_only = [derived_keys[KEYRING_ORDER[0]]]
    for vec in vectors:
        name = vec["name"]
        encrypted_with = vec.get("encrypted_with")
        if encrypted_with not in KEYRING_ORDER or FROZEN_KEYRING_VECTORS.get(name, encrypted_with) != encrypted_with:
            print(
                f"FAIL keyring {name}: encrypted_with must be the entry the frozen name declares (one of {list(KEYRING_ORDER)}); got {encrypted_with!r}"
            )
            failures += 1
            continue
        if derived_fingerprints.get(vec.get("key_fingerprint_hex")) != encrypted_with:
            print(
                f"FAIL keyring {name}: stored key fingerprint must select the HKDF-derived key of {encrypted_with} (never a master key)"
            )
            failures += 1
            continue
        checked = verify_sealed_vector(f"keyring {name}", vec, keyring["tenant_id"], full_keyring, seal=seal)
        if checked is None:
            failures += 1
            continue
        if not seal:
            print(f"ok  keyring {name} (AAD + fingerprint selection only)")
            continue

        aad, index = checked
        if index != KEYRING_ORDER.index(encrypted_with):
            print(f"FAIL keyring {name}: decrypted with keyring entry {KEYRING_ORDER[index]}, expected {encrypted_with}")
            failures += 1
            continue
        ciphertext = bytes.fromhex(vec["ciphertext_hex"])
        if encrypted_with != KEYRING_ORDER[0] and decrypt_with_keyring(current_only, ciphertext, aad) is not None:
            print(f"FAIL keyring {name}: [{KEYRING_ORDER[0]}] alone accepted the {encrypted_with} entry")
            failures += 1
            continue
        print(f"ok  keyring {name}")
    return failures


def verify_default_tenant(block: dict | None, master_key: bytes, *, seal: bool) -> int:
    """Return the number of failed default-tenant checks (intent-presets.md rule 5).

    The block pins tenant "default" under the main master key: fingerprint of the
    HKDF-derived key, AAD reconstruction with "default" as component 1, and (with
    `cryptography`) the seal. An SDK that decrypts these through its preset with NO
    tenant configured has demonstrated the cross-SDK default.
    """
    if block is None:
        print("FAIL default_tenant vectors missing")
        return 1
    failures = 0
    if block.get("tenant_id") != DEFAULT_TENANT_ID:
        print(f"FAIL default_tenant: tenant_id must be the literal {DEFAULT_TENANT_ID!r}; got {block.get('tenant_id')!r}")
        return 1
    key = derive_encryption_key(master_key, DEFAULT_TENANT_ID)
    if key_fingerprint(key) != block.get("derived_key_fingerprint_hex"):
        print(f"FAIL default_tenant: derived-key fingerprint mismatch (derived {key_fingerprint(key)})")
        return 1
    vectors = block.get("vectors", [])
    missing = FROZEN_DEFAULT_TENANT_VECTOR_NAMES - {vec.get("name") for vec in vectors}
    if missing:
        print(f"FAIL frozen default_tenant vectors missing: {sorted(missing)}")
        failures += 1
    for vec in vectors:
        name = vec["name"]
        if verify_sealed_vector(f"default_tenant {name}", vec, DEFAULT_TENANT_ID, [key], seal=seal) is None:
            failures += 1
            continue
        if not seal:
            print(f"ok  default_tenant {name} (AAD + fingerprint only)")
            continue
        print(f"ok  default_tenant {name}")
    return failures


def read_hex_key(text: str, *, lenient: bool = False) -> bytes | None:
    """hex_decode(text) for a row under one reading of what rule 1 leaves open, or None for a refusal.

    The strict reading refuses an uppercase digit, white space and a 0x prefix. The lenient one drops ASCII white
    space, then a leading 0x, and reads uppercase as lowercase. A row must get one verdict under both, so no row
    settles the question; this judges rows only.
    """
    if lenient:
        text = "".join(c for c in text if c not in ASCII_WHITE_SPACE)
        text = (text[2:] if text[:2] in ("0x", "0X") else text).lower()
    if len(text) % 2 or not set(text) <= LOWER_HEX:
        return None
    return bytes.fromhex(text)


def vector_tables(node: object, path: str = "") -> Iterator[str]:
    """The path of every list under a key ending in "vectors", at any depth, as tools/conformance.py finds them."""
    if isinstance(node, dict):
        for key, value in node.items():
            where = f"{path}.{key}" if path else key
            if key.endswith("vectors") and isinstance(value, list):
                yield where
            else:
                yield from vector_tables(value, where)


# Plausible wrong hex and raw-bytes entry points, one per mistake a master_key_input note names. Each returns the key
# bytes it would use, or None for a refusal (one that cannot parse its input refuses it), and must misjudge every row
# it lists; it lists a row only if that row's note names its mistake, so the notes and this table say the same thing.
# A decoding mistake sits behind a conformant length rule, so its row must catch the mistake itself, not a
# length check that happens to; where only one of the two rules lets the mistake through, the entry point uses that one.
HEX_DIGITS = frozenset(string.hexdigits)
# The row every other row comes from, which the notes call the accept row, and the one accept row whose key's first
# byte is 80 or above: one key cannot hold both a leading 00 byte and a first byte at 80 or above.
ACCEPT_ROW = "master_key_every_hex_digit"
FIRST_BYTE_80_ROW = "master_key_first_byte_80"
EXACTLY_32, AT_LEAST_32 = HEX_LENGTH_RULES[EXACTLY], HEX_LENGTH_RULES[OR_MORE]


def behind(accepts: Callable[[int], bool], key: bytes | None) -> bytes | None:
    """`key` if a length rule that `accepts` its length lets it through, else None."""
    return key if key is not None and accepts(len(key)) else None


def buffer_from_hex(text: str) -> bytes:
    """Node's Buffer.from(text, "hex"): byte pairs up to the first that is not hex; an odd last digit is dropped."""
    out = bytearray()
    for i in range(0, len(text) - 1, 2):
        if not set(text[i : i + 2]) <= HEX_DIGITS:
            break
        out.append(int(text[i : i + 2], 16))
    return bytes(out)


def big_integer(text: str) -> bytes:
    """int(text, 16) back to bytes at its minimal length: a leading 00 byte disappears."""
    value = int(text, 16)
    return value.to_bytes((value.bit_length() + 7) // 8, "big")


def twos_complement(text: str) -> bytes:
    """Java's new BigInteger(text, 16).toByteArray() (num-bigint's to_signed_bytes_be): the minimal bytes plus a 00
    sign byte when the top bit is set, which restores a leading 00 only when the byte after it is 80 or above."""
    value = int(text, 16)
    return value.to_bytes(value.bit_length() // 8 + 1, "big")


def padded_twos_complement(text: str) -> bytes | None:
    """int(text, 16).to_bytes(32, "big", signed=True) behind a strict hex check: right for a key whose first byte is
    below 80, refused for one at 80 or above, whose sign needs a 33rd byte (where Java's toByteArray() returns 33)."""
    if read_hex_key(text) is None:
        return None
    try:
        return int(text, 16).to_bytes(KEY_BYTES, "big", signed=True)
    except OverflowError:
        return None


def digits_swapped(text: str) -> bytes | None:
    """Each byte read with its two digits swapped."""
    return None if len(text) % 2 else bytes.fromhex("".join(text[i + 1] + text[i] for i in range(0, len(text), 2)))


def digits_only_decoder(text: str) -> bytes:
    """Each digit's value taken as ord(c) - ord("0") in four bits: right for 0-9, wrong for every letter."""
    nibbles = [(ord(c) - ord("0")) & 0x0F for c in text]
    return bytes(hi << 4 | lo for hi, lo in zip(nibbles[::2], nibbles[1::2], strict=True))


def first_digit_decimal(text: str) -> bytes | None:
    """A decoder whose table for a byte's first digit holds only 0-9, so a letter there is refused."""
    return None if any(c not in string.digits for c in text[0::2]) else bytes.fromhex(text)


def signed_pairs(text: str) -> bytes | None:
    """Each pair parsed as a signed byte (Rust's i8::from_str_radix, Go's ParseInt(pair, 16, 8)): above 7f is refused."""
    key = bytes.fromhex(text)
    return None if any(b > 0x7F for b in key) else key


def through_text(key: bytes) -> bytes:
    """Key bytes passed through a text string at a str-typed boundary: each byte above 7f becomes two in UTF-8."""
    return key.decode("latin-1").encode("utf-8")


def sign_tolerant_pairs(text: str) -> bytes | None:
    """Pairs parsed one at a time by an integer parser that takes a sign, behind a 64-character check."""
    if len(text) != 2 * KEY_BYTES:
        return None
    try:
        return bytes(int(text[i : i + 2], 16) for i in range(0, len(text), 2))
    except ValueError:
        return None


def one_integer(text: str) -> bytes | None:
    """The string read as one integer (int(key, 16) takes a sign and a 0x prefix) back to 32 bytes, behind a 64-character check."""
    if len(text) != 2 * KEY_BYTES:
        return None
    try:
        return int(text, 16).to_bytes(KEY_BYTES, "big")
    except (ValueError, OverflowError):
        return None


def white_space_skipped(text: str) -> bytes | None:
    """A check for 64 characters or more, then Python's bytes.fromhex, which skips white space between pairs."""
    if len(text) < 2 * KEY_BYTES:
        return None
    try:
        return bytes.fromhex(text)
    except ValueError:
        return None


def prefix_stripped(text: str) -> bytes | None:
    """A 64-character check, then a 0x prefix stripped and the rest decoded with no check on the key's length."""
    if len(text) != 2 * KEY_BYTES:
        return None
    return read_hex_key(text[2:] if text[:2] in ("0x", "0X") else text)


def hex_decoded_first(raw: bytes) -> bytes:
    """A raw-bytes entry point that hex-decodes 64 ASCII hex digits before its length check."""
    text = raw.decode("latin-1")
    return bytes.fromhex(text) if len(text) == 2 * KEY_BYTES and set(text) <= HEX_DIGITS else raw


SHORT_ROWS = ("master_key_31_bytes", "master_key_24_bytes", "master_key_16_bytes")

# Wrong length rules, shared by both kinds of entry point: each predicate, then the hex rows and the raw rows that
# show it. A hex entry point decodes strictly before applying the rule.
WRONG_LENGTH_RULES: dict[str, tuple[Callable[[int], bool], tuple[str, ...], tuple[str, ...]]] = {
    "no length check": (lambda n: True, SHORT_ROWS, ("raw_key_31_bytes",)),
    "off by one (31 bytes or more)": (lambda n: n >= KEY_BYTES - 1, ("master_key_31_bytes",), ("raw_key_31_bytes",)),
    # No hex row: no hex reject row decodes to 32 bytes or more, so on hex rows this is off by one.
    "31 or 32 bytes": (lambda n: n in (KEY_BYTES - 1, KEY_BYTES), (), ("raw_key_31_bytes",)),
    "16 bytes or more, the HKDF floor encryption.md once listed": (lambda n: n >= 16, SHORT_ROWS, ()),
    "AES key sizes (16, 24 or 32 bytes)": (lambda n: n in (16, 24, 32), ("master_key_24_bytes",), ("raw_key_24_bytes",)),
    "AES-192 and AES-256 key sizes (24 or 32 bytes)": (lambda n: n in (24, 32), ("master_key_24_bytes",), ("raw_key_24_bytes",)),
    "AES-128 and AES-256 key sizes (16 or 32 bytes)": (lambda n: n in (16, 32), ("master_key_16_bytes",), ("raw_key_16_bytes",)),
}

WRONG_HEX_ENTRY_POINTS: dict[str, tuple[Callable[[str], bytes | None], tuple[str, ...]]] = {
    "digits only, a pattern tested only on all-digit keys": (
        lambda t: read_hex_key(t) if set(t) <= set(string.digits) else None,
        (ACCEPT_ROW,),
    ),
    "uppercase hex digits only (^[0-9A-F]{64}$)": (lambda t: bytes.fromhex(t) if re.fullmatch("[0-9A-F]{64}", t) else None, (ACCEPT_ROW,)),
    "big-integer decode, which drops a leading 00 byte": (lambda t: behind(AT_LEAST_32, big_integer(t)), (ACCEPT_ROW,)),
    "a two's-complement big-integer decoder (BigInteger.toByteArray(), to_signed_bytes_be)": (
        lambda t: behind(AT_LEAST_32, twos_complement(t)),
        (ACCEPT_ROW,),
    ),
    "a two's-complement big-integer decoder padded to 32 bytes (int(key, 16).to_bytes(32, 'big', signed=True))": (
        padded_twos_complement,
        (FIRST_BYTE_80_ROW,),
    ),
    "bytes reversed (a little-endian integer)": (lambda t: behind(AT_LEAST_32, bytes.fromhex(t)[::-1]), (ACCEPT_ROW,)),
    "the two digits of each byte swapped": (lambda t: behind(AT_LEAST_32, digits_swapped(t)), (ACCEPT_ROW,)),
    "a letter read as ord(c) - ord('0')": (lambda t: behind(AT_LEAST_32, digits_only_decoder(t)), (ACCEPT_ROW,)),
    "a byte's first digit read as decimal": (lambda t: behind(AT_LEAST_32, first_digit_decimal(t)), (ACCEPT_ROW,)),
    "a signed-byte pair parser, which refuses a pair above 7f": (lambda t: behind(AT_LEAST_32, signed_pairs(t)), (ACCEPT_ROW,)),
    "the key bytes passed through a text string (latin-1 in, UTF-8 out)": (
        lambda t: behind(AT_LEAST_32, through_text(bytes.fromhex(t))),
        (ACCEPT_ROW,),
    ),
    "Node's Buffer.from(key, 'hex'), then a check that the key is 32 bytes": (
        lambda t: behind(EXACTLY_32, buffer_from_hex(t)),
        ("master_key_odd_65_digits", "master_key_trailing_non_hex"),
    ),
    "a check that the length is even, then Node's Buffer.from(key, 'hex') and a check that the key is 32 bytes": (
        lambda t: behind(EXACTLY_32, buffer_from_hex(t)) if len(t) % 2 == 0 else None,
        ("master_key_trailing_non_hex",),
    ),
    "an odd string padded with a leading 0, then a check that the key is exactly 32 bytes": (
        lambda t: behind(EXACTLY_32, bytes.fromhex(t if len(t) % 2 == 0 else "0" + t)),
        ("master_key_odd_63_digits",),
    ),
    "a character that is not a hex digit read as 0": (
        lambda t: behind(EXACTLY_32, bytes.fromhex("".join(c if c in HEX_DIGITS else "0" for c in t))),
        ("master_key_non_hex_digit",),
    ),
    "Node's Buffer.from(key, 'hex'), with only the string's length checked": (
        lambda t: buffer_from_hex(t) if len(t) == 2 * KEY_BYTES else None,
        ("master_key_non_hex_digit",),
    ),
    "a pattern anchored only at the start (re.match) and a 64-character check, then Buffer.from": (
        lambda t: buffer_from_hex(t) if len(t) == 2 * KEY_BYTES and re.match("[0-9a-fA-F]+", t) else None,
        ("master_key_non_hex_digit",),
    ),
    "pairs parsed one at a time by an integer parser that takes a sign (u8::from_str_radix, int(pair, 16))": (
        sign_tolerant_pairs,
        ("master_key_plus_sign",),
    ),
    "the string read as one integer, int(key, 16), back to 32 bytes": (one_integer, ("master_key_plus_sign",)),
    "a 64-character check, then a 0x prefix stripped and the rest decoded": (prefix_stripped, ("master_key_0x_and_31_bytes",)),
    "a 64-character check on the string as given, then a trim and a strict decode": (
        lambda t: read_hex_key(t.strip()) if len(t) == 2 * KEY_BYTES else None,
        ("master_key_31_bytes_and_crlf",),
    ),
    "the string's ends stripped and its length checked, then bytes.fromhex, which skips white space between pairs": (
        lambda t: white_space_skipped(t.strip()),
        ("master_key_31_bytes_with_spaces",),
    ),
    "a short key padded to 32 bytes": (
        lambda t: key.ljust(KEY_BYTES, b"\0") if (key := read_hex_key(t)) is not None else None,
        SHORT_ROWS,
    ),
    **{
        label: (lambda t, accepts=accepts: behind(accepts, read_hex_key(t)), rows)
        for label, (accepts, rows, _) in WRONG_LENGTH_RULES.items()
        if rows
    },
}

WRONG_RAW_ENTRY_POINTS: dict[str, tuple[Callable[[bytes], bytes | None], tuple[str, ...]]] = {
    "32 bytes or more, as a hex entry point may accept": (
        lambda k: behind(AT_LEAST_32, k),
        ("raw_key_33_bytes", "raw_key_ascii_hex_string"),
    ),
    "64 hex digits hex-decoded first": (
        lambda k: behind(EXACTLY_32, hex_decoded_first(k)),
        ("raw_key_ascii_hex_string",),
    ),
    "a short key padded to 32 bytes": (lambda k: k.ljust(KEY_BYTES, b"\0") if len(k) <= KEY_BYTES else None, ("raw_key_31_bytes",)),
    # Fed the accept row's key as bytes, as a test drives a raw-bytes entry point with a decoded hex key.
    "the key bytes passed through a text string, then a check that they are 32 bytes": (
        lambda k: behind(EXACTLY_32, through_text(k)),
        (ACCEPT_ROW,),
    ),
    **{label: (lambda k, accepts=accepts: behind(accepts, k), rows) for label, (accepts, _, rows) in WRONG_LENGTH_RULES.items() if rows},
}


def verdict(key: bytes | None) -> str | None:
    """What an entry point's answer pins: None for a refusal, else the fingerprint of the key it derives for "default"."""
    return None if key is None else key_fingerprint(derive_encryption_key(key, DEFAULT_TENANT_ID))


def verify_wrong_entry_points(rows: dict[str, tuple[str, dict]]) -> int:
    """Return the number of wrong entry points that judge a row they list correctly (or name a row of the wrong kind).

    A raw-bytes entry point may list an accept row, which it is fed as decoded bytes. A missing row is skipped: the
    frozen-name guard reports it.
    """
    failures = 0
    accept_rows = FROZEN_MASTER_KEY_INPUT_VECTORS["accept_vectors"]
    raw_rows = FROZEN_MASTER_KEY_INPUT_VECTORS["raw_reject_vectors"]
    hex_rows = accept_rows | FROZEN_MASTER_KEY_INPUT_VECTORS["reject_vectors"]
    listed: set[str] = set()
    for entry_points, kind in ((WRONG_HEX_ENTRY_POINTS, hex_rows), (WRONG_RAW_ENTRY_POINTS, raw_rows | accept_rows)):
        for label, (entry_point, targets) in entry_points.items():
            for target in targets:
                listed.add(target)
                if target not in kind:
                    print(f"FAIL wrong entry point {label!r} lists {target}, which is not a frozen row of its kind")
                    failures += 1
                    continue
                if target not in rows:
                    continue
                table, row = rows[target]
                try:
                    if table == "raw_reject_vectors":
                        given: str | bytes = bytes.fromhex(row["raw_key_hex"])
                    elif entry_points is WRONG_RAW_ENTRY_POINTS:
                        given = bytes.fromhex(row["master_key_hex"])
                    else:
                        given = row["master_key_hex"]
                    got = verdict(entry_point(given))
                except (ValueError, OverflowError) as exc:
                    print(f"FAIL wrong entry point {label!r} raised on {target}: {exc}")
                    failures += 1
                    continue
                if got == row.get("derived_key_fingerprint_hex"):
                    print(
                        f"FAIL wrong entry point {label!r} judges {target} correctly, so the row no longer shows the "
                        "mistake its note names"
                    )
                    failures += 1
    # A row a later version adds needs a wrong entry point too, or its note's claims go unchecked.
    unshown = sorted((hex_rows | raw_rows | set(rows)) - listed)
    if unshown:
        print(f"FAIL no wrong entry point shows why these rows exist: {unshown}")
        failures += 1
    return failures


def verify_master_key_input(block: dict | None, default_tenant: dict | None, main_master_key_hex: str, *, seal: bool) -> int:
    """Return the number of failed master key input checks (spec/intent-presets.md § Master Key Input).

    Accept rows must be accepted, and reject rows refused, under every conformant length rule and both readings of
    what rule 1 leaves open; raw reject rows must not be 32 bytes. An accept row shares neither its master key nor
    its cache_key or plaintext with a default_tenant entry or another accept row, so a test can read them under
    different keys (PRE-51). Each accept row's fingerprint, AAD and (with `cryptography`) seal are checked under the
    key its own master key derives, then each wrong entry point must misjudge the rows it lists.
    """
    if block is None:
        print("FAIL master_key_input rows missing")
        return 1
    if block.get("tenant_id") != DEFAULT_TENANT_ID:
        print(f"FAIL master_key_input: tenant_id must be the literal {DEFAULT_TENANT_ID!r}; got {block.get('tenant_id')!r}")
        return 1
    failures = 0
    # A row joins `rows`, and so the wrong-entry-point check, once its fields, name, note and characters pass, so a row
    # whose verdict is wrong is still checked against the models. A model that cannot parse such a row (an odd-length
    # accept row, say) raises, and verify_wrong_entry_points reports that as a failure, not a traceback.
    dt_vectors = (default_tenant or {}).get("vectors", [])
    accept_vectors = block.get("accept_vectors", [])
    rows: dict[str, tuple[str, dict]] = {}
    seen: set[str] = set()
    for table, frozen in FROZEN_MASTER_KEY_INPUT_VECTORS.items():
        missing = frozen - {row.get("name") for row in block.get(table, [])}
        if missing:
            print(f"FAIL frozen master_key_input {table} missing (append-only, never rename or move): {sorted(missing)}")
            failures += 1
        for row in block.get(table, []):
            name = row.get("name")
            label = f"master_key_input {name}"
            if set(row) != MASTER_KEY_INPUT_FIELDS[table]:
                print(f"FAIL {label}: fields {sorted(row)} != {sorted(MASTER_KEY_INPUT_FIELDS[table])}")
                failures += 1
                continue
            if name in seen:
                print(f"FAIL {label}: duplicate name")
                failures += 1
                continue
            seen.add(name)
            if not isinstance(row["note"], str) or not row["note"].strip():
                print(f"FAIL {label}: note must be a non-empty string")
                failures += 1
                continue
            if table == "raw_reject_vectors":
                raw_hex = row["raw_key_hex"]
                if len(raw_hex) % 2 or not set(raw_hex) <= LOWER_HEX:
                    print(f"FAIL {label}: raw_key_hex must be lowercase hex")
                    failures += 1
                    continue
                rows[name] = (table, row)
                if len(bytes.fromhex(raw_hex)) == KEY_BYTES:
                    print(f"FAIL {label}: a raw-bytes entry point takes exactly {KEY_BYTES} bytes, so this row is no reject")
                    failures += 1
                else:
                    print(f"ok  {label}")
                continue
            text = row["master_key_hex"]
            if not set(text) <= ROW_CHARACTERS:
                print(f"FAIL {label}: holds a character other than printable ASCII and ASCII white space")
                failures += 1
                continue
            rows[name] = (table, row)
            wanted = table == "accept_vectors"
            others = [v for v in accept_vectors if v is not row]
            if wanted and (
                text in [main_master_key_hex, *(v.get("master_key_hex") for v in others)]
                or any(
                    row["cache_key"] == v.get("cache_key") or row["plaintext_hex"] == v.get("plaintext_hex")
                    for v in dt_vectors + others
                )
            ):
                print(
                    f"FAIL {label}: shares its master key, cache_key or plaintext with a default_tenant entry or another "
                    "accept row, so a test cannot read them under different keys"
                )
                failures += 1
                continue
            wrong = [
                f"an entry point that takes {rule} and {reading}"
                for reading, lenient in READINGS.items()
                for rule, accepts in HEX_LENGTH_RULES.items()
                if ((key := read_hex_key(text, lenient=lenient)) is not None and accepts(len(key))) != wanted
            ]
            if wrong:
                print(f"FAIL {label}: {wrong[0]} {'refuses' if wanted else 'accepts'} it, so the row decides what the spec leaves open")
                failures += 1
                continue
            if not wanted:
                print(f"ok  {label}")
                continue
            derived = derive_encryption_key(bytes.fromhex(text), block["tenant_id"])
            if key_fingerprint(derived) != row["derived_key_fingerprint_hex"]:
                print(f"FAIL {label}: derived-key fingerprint mismatch (derived {key_fingerprint(derived)})")
                failures += 1
                continue
            if verify_sealed_vector(label, row, block["tenant_id"], [derived], seal=seal) is None:
                failures += 1
                continue
            print(f"ok  {label}" if seal else f"ok  {label} (AAD + fingerprint only)")
    return failures + verify_wrong_entry_points(rows)


def verify(doc: dict, *, require_seal: bool) -> int:
    failures = 0

    unknown = sorted(set(vector_tables(doc)) - VECTOR_TABLES)
    if unknown:
        print(f"FAIL unknown vector table(s) {unknown}: tools/conformance.py would index rows this verifier skips")
        return 1

    missing = FROZEN_VECTOR_NAMES - {v["name"] for v in doc["vectors"]}
    if missing:
        print(f"FAIL frozen vectors missing (append-only file — never remove/rename): {sorted(missing)}")
        return 1

    key = derive_encryption_key(bytes.fromhex(doc["master_key_hex"]), doc["tenant_id"])
    if key_fingerprint(key) != doc["derived_key_fingerprint_hex"]:
        print(f"FAIL key fingerprint: derived {key_fingerprint(key)}, pinned {doc['derived_key_fingerprint_hex']}")
        return 1
    print(f"ok  key fingerprint {doc['derived_key_fingerprint_hex']}")

    try:
        # Probe only: decrypt_with_keyring imports these again where it uses them.
        from cryptography.exceptions import InvalidTag  # noqa: F401, PLC0415
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: F401, PLC0415

        seal = True
    except ImportError:
        if require_seal:
            print("FAIL --require-seal set but `cryptography` is not installed")
            return 1
        seal = False
        print("note: `cryptography` not installed — AAD reconstruction only, AES-GCM seal NOT verified")

    for vec in doc["vectors"]:
        name = vec["name"]
        if verify_sealed_vector(name, vec, doc["tenant_id"], [key], seal=seal, original_type=vec.get("original_type")) is None:
            failures += 1
            continue
        print(f"ok  {name}")

    failures += verify_aad_rejects(doc, key, seal=seal)
    failures += verify_keyring(doc.get("keyring"), seal=seal)
    failures += verify_default_tenant(doc.get("default_tenant"), bytes.fromhex(doc["master_key_hex"]), seal=seal)
    failures += verify_master_key_input(doc.get("master_key_input"), doc.get("default_tenant"), doc["master_key_hex"], seal=seal)

    if failures:
        print(f"{failures} vector(s) FAILED")
        return 1
    mode = "AAD + AES-GCM seal" if seal else "AAD-only"
    keyring_count = len(doc.get("keyring", {}).get("vectors", []))
    default_count = len(doc.get("default_tenant", {}).get("vectors", []))
    master_key_count = sum(len(doc["master_key_input"][table]) for table in FROZEN_MASTER_KEY_INPUT_VECTORS)
    print(
        f"all {len(doc['vectors'])} encryption vectors plus {len(doc['aad_reject_vectors'])} AAD reject, {keyring_count} "
        f"keyring, {default_count} default-tenant and {master_key_count} master key input vectors verified ({mode})"
    )
    return 0


def main() -> int:
    require_seal = "--require-seal" in sys.argv[1:]
    return verify(json.loads(VECTORS_PATH.read_text()), require_seal=require_seal)


if __name__ == "__main__":
    sys.exit(main())
