#!/usr/bin/env python3
"""Reference encoder/verifier for the ByteStorage envelope (spec/wire-format.md).

Stdlib-only (one optional extra, see below). Scope: the **MessagePack encoding**
of the StorageEnvelope positional array — both the legacy element[0] encoding
(array of integers, pre-1.1 writers) and the canonical one (msgpack `bin`,
protocol 1.1+ writers). LZ4 decompression and xxHash3-64 recomputation are NOT
verified here (neither is stdlib); that enforcement lives in cachekit-core's CI
(`tests/wire_format_vectors.rs`, LAB-423).

What `verify` proves, for every vector pair in ../test-vectors/wire-format.json:
  1. Codec fidelity — decoding a legacy vector and re-encoding it in legacy form
     reproduces the pinned bytes exactly. The legacy bytes were generated by
     `rmp_serde::to_vec` (cachekit-core v0.2.0), so byte-identity here proves
     this codec makes the same shortest-form header choices as rmp — which is
     what makes the derived `bin` encoding trustworthy.
  2. Twin equivalence — each `*_bin` vector decodes to field-identical contents
     as its legacy base, its element[0] carries a bin marker (0xc4/0xc5/0xc6),
     the outer fixarray(4) is preserved, and re-encoding the base's fields in
     bin form reproduces the `*_bin` bytes exactly.
  3. Documented size bound — a bin envelope is never more than 1 byte larger
     than its legacy twin (the header-arithmetic bound stated in the spec).

Usage:
    python3 tools/wire-format-reference.py verify     # default
    python3 tools/wire-format-reference.py generate   # (re)derive *_bin vectors

One optional-dependency check deepens `verify` when importable (runs in CI):
  - `msgpack`: third-encoder conformance — msgpack-python re-encodes both forms
    from decoded fields and must reproduce the pinned bytes byte-identically.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

FIXTURE_PATH = Path(__file__).resolve().parent.parent / "test-vectors" / "wire-format.json"

FIXTURE_VERSION = "1.1.0"
ENVELOPE_FORMAT = (
    "MessagePack positional array (rmp_serde::to_vec): "
    "[compressed_data, checksum, original_size, format]. Vectors without an "
    "'envelope_encoding' field use the legacy array-of-integers encoding for "
    "compressed_data and are retained forever as legacy-read proof; their "
    "'*_bin' twins use msgpack bin (canonical for protocol 1.1+ writers). "
    "checksum always encodes as an array of 8 integers. Normative rules: "
    "spec/wire-format.md, 'Byte Layout' / 'Encoding compatibility'."
)
GENERATOR = (
    "legacy vectors: cachekit-core v0.2.0 (unchanged since); *_bin vectors: "
    "tools/wire-format-reference.py generate - deterministic re-encode of the "
    "legacy fields, byte-verified against rmp-serde 1.3.1 + serde_bytes 0.11.19 "
    "output (LAB-783)"
)

# --- minimal MessagePack codec ------------------------------------------------
# Deliberately scoped to the types a StorageEnvelope uses. The encoder emits
# shortest-form headers only — the same choices rmp_serde makes — and `verify`
# proves that equivalence against the pinned legacy bytes on every run.


class _Reader:
    def __init__(self, buf: bytes):
        self.buf = buf
        self.pos = 0

    def take(self, n: int) -> bytes:
        if self.pos + n > len(self.buf):
            raise ValueError("truncated msgpack document")
        out = self.buf[self.pos : self.pos + n]
        self.pos += n
        return out

    def u8(self) -> int:
        return self.take(1)[0]

    def be(self, n: int) -> int:
        return int.from_bytes(self.take(n), "big")


def _decode_uint(r: _Reader) -> int:
    m = r.u8()
    if m <= 0x7F:
        return m
    if m == 0xCC:
        return r.be(1)
    if m == 0xCD:
        return r.be(2)
    if m == 0xCE:
        return r.be(4)
    raise ValueError(f"expected msgpack uint, got marker 0x{m:02x}")


def _decode_array_header(r: _Reader) -> int:
    m = r.u8()
    if 0x90 <= m <= 0x9F:
        return m & 0x0F
    if m == 0xDC:
        return r.be(2)
    if m == 0xDD:
        return r.be(4)
    raise ValueError(f"expected msgpack array, got marker 0x{m:02x}")


def _decode_str(r: _Reader) -> str:
    m = r.u8()
    if not 0xA0 <= m <= 0xBF:
        # format is a bounded registry token (e.g. "msgpack"), always fixstr.
        raise ValueError(f"expected msgpack fixstr, got marker 0x{m:02x}")
    return r.take(m & 0x1F).decode("utf-8")


def _decode_bytes_field(r: _Reader) -> tuple[bytes, str]:
    """Decode element[0]: either legacy array-of-ints or bin. Returns (data, encoding)."""
    m = r.buf[r.pos]
    if m in (0xC4, 0xC5, 0xC6):
        r.u8()
        n = r.be({0xC4: 1, 0xC5: 2, 0xC6: 4}[m])
        return r.take(n), "bin"
    n = _decode_array_header(r)
    data = bytearray()
    for _ in range(n):
        v = _decode_uint(r)
        if v > 0xFF:
            raise ValueError(f"byte-array element out of range: {v}")
        data.append(v)
    return bytes(data), "int-array"


def _encode_uint(v: int) -> bytes:
    if v < 0:
        raise ValueError("negative uint")
    if v <= 0x7F:
        return bytes([v])
    if v <= 0xFF:
        return bytes([0xCC, v])
    if v <= 0xFFFF:
        return b"\xcd" + v.to_bytes(2, "big")
    if v <= 0xFFFFFFFF:
        return b"\xce" + v.to_bytes(4, "big")
    raise ValueError("uint too large for envelope fields")


def _encode_array_header(n: int) -> bytes:
    if n <= 0x0F:
        return bytes([0x90 | n])
    if n <= 0xFFFF:
        return b"\xdc" + n.to_bytes(2, "big")
    return b"\xdd" + n.to_bytes(4, "big")


def _encode_int_array(data: bytes) -> bytes:
    return _encode_array_header(len(data)) + b"".join(_encode_uint(b) for b in data)


def _encode_bin(data: bytes) -> bytes:
    n = len(data)
    if n <= 0xFF:
        return b"\xc4" + bytes([n]) + data
    if n <= 0xFFFF:
        return b"\xc5" + n.to_bytes(2, "big") + data
    return b"\xc6" + n.to_bytes(4, "big") + data


def _encode_str(s: str) -> bytes:
    raw = s.encode("utf-8")
    if len(raw) > 31:
        raise ValueError("format string too long for a fixstr registry token")
    return bytes([0xA0 | len(raw)]) + raw


# --- envelope <-> fields -------------------------------------------------------


def decode_envelope(env: bytes) -> tuple[bytes, bytes, int, str, str]:
    """Returns (compressed_data, checksum, original_size, format, element0_encoding)."""
    r = _Reader(env)
    if _decode_array_header(r) != 4:
        raise ValueError("StorageEnvelope must be a 4-element array")
    data, encoding = _decode_bytes_field(r)
    if _decode_array_header(r) != 8:
        raise ValueError("checksum must be an 8-element array")
    checksum = bytes(_decode_uint(r) for _ in range(8))
    original_size = _decode_uint(r)
    fmt = _decode_str(r)
    if r.pos != len(env):
        raise ValueError(f"{len(env) - r.pos} trailing bytes after envelope")
    return data, checksum, original_size, fmt, encoding


def encode_envelope(
    data: bytes, checksum: bytes, original_size: int, fmt: str, *, encoding: str
) -> bytes:
    element0 = _encode_bin(data) if encoding == "bin" else _encode_int_array(data)
    return (
        _encode_array_header(4)
        + element0
        + _encode_int_array(checksum)
        + _encode_uint(original_size)
        + _encode_str(fmt)
    )


# --- generate / verify ----------------------------------------------------------


def _load() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _split_vectors(fixture: dict) -> tuple[list[dict], dict[str, dict]]:
    legacy = [v for v in fixture["vectors"] if "envelope_encoding" not in v]
    bins = {v["name"]: v for v in fixture["vectors"] if v.get("envelope_encoding") == "bin"}
    # Fail closed: every vector must classify as exactly one of the two sets,
    # with no duplicate names — otherwise verify would silently skip it (and
    # generate would silently drop it from the append-only fixture).
    if len(legacy) + len(bins) != len(fixture["vectors"]) or len({v["name"] for v in legacy}) != len(legacy):
        raise ValueError("fixture contains unclassifiable or duplicate-named vectors")
    return legacy, bins


def _bin_twin(base: dict) -> dict:
    data, checksum, size, fmt, encoding = decode_envelope(bytes.fromhex(base["envelope_hex"]))
    assert encoding == "int-array", f"[{base['name']}] base vector is not legacy-encoded"
    env = encode_envelope(data, checksum, size, fmt, encoding="bin")
    twin = dict(base)  # preserves key order of the legacy vectors
    twin["name"] = base["name"] + "_bin"
    twin["description"] = (
        f"bin-encoded twin of '{base['name']}': identical fields, compressed_data "
        "as msgpack bin (canonical writer encoding, protocol 1.1+)"
    )
    twin["envelope_hex"] = env.hex()
    twin["envelope_size"] = len(env)
    twin["envelope_encoding"] = "bin"
    twin["derived_from"] = base["name"]
    return twin


def generate() -> int:
    fixture = _load()
    legacy, _ = _split_vectors(fixture)
    fixture["vectors"] = legacy + [_bin_twin(v) for v in legacy]
    fixture["envelope_format"] = ENVELOPE_FORMAT
    fixture["generator"] = GENERATOR
    fixture["version"] = FIXTURE_VERSION
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH.name}: {len(legacy)} legacy + {len(legacy)} bin vectors")
    return 0


def verify() -> int:
    fixture = _load()
    legacy, bins = _split_vectors(fixture)
    if not legacy:
        print("FAIL: no legacy vectors found", file=sys.stderr)
        return 1
    if fixture.get("version") != FIXTURE_VERSION:
        print(f"FAIL: fixture version {fixture.get('version')} != {FIXTURE_VERSION}", file=sys.stderr)
        return 1

    try:
        import msgpack  # type: ignore[import-untyped]
    except ImportError:
        msgpack = None

    failures = 0
    for base in legacy:
        name = base["name"]
        try:
            old_env = bytes.fromhex(base["envelope_hex"])
            data, checksum, size, fmt, encoding = decode_envelope(old_env)

            # 1. codec fidelity against the rmp_serde-generated legacy bytes
            assert encoding == "int-array", "legacy vector not array-of-ints encoded"
            assert encode_envelope(data, checksum, size, fmt, encoding="int-array") == old_env, (
                "legacy re-encode not byte-identical"
            )
            assert len(old_env) == base["envelope_size"], "envelope_size mismatch"
            assert fmt == base["format"], "format field mismatch"
            assert size == base["input_size"], "original_size != input_size"

            # 2. twin equivalence
            twin = bins.pop(name + "_bin", None)
            assert twin is not None, "missing bin twin vector"
            new_env = bytes.fromhex(twin["envelope_hex"])
            assert encode_envelope(data, checksum, size, fmt, encoding="bin") == new_env, (
                "bin re-encode not byte-identical to twin"
            )
            assert new_env[0] == 0x94, "outer fixarray(4) not preserved"
            assert new_env[1] in (0xC4, 0xC5, 0xC6), "element[0] not bin-encoded"
            t_data, t_checksum, t_size, t_fmt, t_encoding = decode_envelope(new_env)
            assert t_encoding == "bin"
            assert (t_data, t_checksum, t_size, t_fmt) == (data, checksum, size, fmt), (
                "twin decodes to different fields"
            )
            assert twin["input_hex"] == base["input_hex"], "twin input_hex drifted"
            assert twin["input_size"] == base["input_size"], "twin input_size drifted"
            assert twin["format"] == base["format"], "twin format drifted"
            assert len(new_env) == twin["envelope_size"], "twin envelope_size mismatch"

            # 3. documented size bound: the only pairing where bin loses is
            # bin8 (2 B) vs fixarray (1 B), i.e. compressed_data <= 15 bytes,
            # so a bin twin is never more than 1 byte larger than its legacy base.
            assert len(new_env) <= len(old_env) + 1, "bin twin exceeds +1 B header bound"

            # optional: third-encoder conformance via msgpack-python
            if msgpack is not None:
                obj = msgpack.unpackb(new_env, raw=False)
                assert obj == [data, list(checksum), size, fmt], "msgpack-python bin decode mismatch"
                assert msgpack.packb([data, list(checksum), size, fmt], use_bin_type=True) == new_env, (
                    "msgpack-python bin re-encode mismatch"
                )
                obj = msgpack.unpackb(old_env, raw=False)
                assert obj == [list(data), list(checksum), size, fmt], (
                    "msgpack-python legacy decode mismatch"
                )
                assert msgpack.packb([list(data), list(checksum), size, fmt]) == old_env, (
                    "msgpack-python legacy re-encode mismatch"
                )

            delta = len(new_env) - len(old_env)
            print(f"  ok {name}: legacy {len(old_env)} B -> bin {len(new_env)} B ({delta:+d} B)")
        except (AssertionError, ValueError) as e:
            failures += 1
            print(f"  FAIL {name}: {e}", file=sys.stderr)

    for orphan in bins:
        failures += 1
        print(f"  FAIL {orphan}: bin vector without a legacy base", file=sys.stderr)

    conformance = "with msgpack-python conformance" if msgpack else "stdlib-only"
    if failures:
        print(f"FAIL: {failures} failure(s) ({conformance})", file=sys.stderr)
        return 1
    print(f"all {len(legacy)} vector pairs verified ({conformance})")
    return 0


def main() -> int:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "verify"
    if cmd == "generate":
        return generate()
    if cmd == "verify":
        return verify()
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
