#!/usr/bin/env python3
"""Reference encoder/verifier/reader for the ByteStorage envelope (spec/wire-format.md).

Stdlib-only (optional extras, see below). Scope: the **MessagePack encoding**
of the StorageEnvelope positional array — both the legacy element[0] encoding
(array of integers, pre-1.1 writers) and the canonical one (msgpack `bin`,
protocol 1.1+ writers) — and a reader, `read_envelope`, that runs the spec's
Retrieve Flow with every size and ratio bound and step 2's decode-bounds pre-scan. The
LZ4 decoder and the segment-list `construct` are imported from
tools/interop-v2-reference.py, and the pre-scan's header walk from
tools/decode-bounds-reference.py, not copied. xxHash3-64 is verified only when the optional `xxhash` package is
importable: a stdlib xxh3 would be a second hand-written hash needing its own
verifier, and CI's optional-deps leg already pins third-party packages for this
tool. Byte-level enforcement for the canonical writer lives in cachekit-core's
CI (`tests/wire_format_vectors.rs`, LAB-423).

What `verify` proves, for every vector pair in ../test-vectors/wire-format.json:
  1. Codec fidelity — decoding a legacy vector and re-encoding it in legacy form
     reproduces the pinned bytes exactly. The legacy bytes were generated by
     `rmp_serde::to_vec` (cachekit-core v0.2.0), so byte-identity here proves
     this codec makes the same shortest-form header choices as rmp — which is
     what makes the derived `bin` encoding trustworthy.
  2. Twin equivalence — each `*_bin` vector decodes to field-identical contents
     as its legacy base, its element[0] carries a bin marker (0xc4/0xc5/0xc6),
     the outer fixarray(4) is preserved, and re-encoding the base's fields in
     bin form reproduces the `*_bin` bytes exactly.
  3. Documented size bound — a bin envelope is never more than 1 byte larger
     than its legacy twin (the header-arithmetic bound stated in the spec).
  4. Declared sizes match ground truth — `original_size` equals the real length
     of `input_hex`, not merely the co-located `input_size` field (both declared
     sizes live in the file under test, so they drift together).
  5. The base-vector set is exactly EXPECTED_BASE_VECTORS, each width-boundary
     base keeps the compressed_data length its name promises (WIDTH_BOUNDARIES), and
     the fixture's own declared `limits` block matches the spec's Security Limits
     table. All are whole-file properties: checks 1-4 iterate the fixture's vector
     list and so are structurally blind to a vector that is simply absent, or to a
     bound the fixture misdeclares to every SDK that reads it.
  6. The reader accepts every pinned vector, both encodings, and returns its input.
  7. Each `constructed_vectors` entry equals what its builder derives, byte for
     byte, and the reader decodes the constructed envelope to the constructed
     input. `envelope_ratio_product_wraps_32_bits` has a compressed_size of
     ceil(2**32 / 1000) B and an original larger than its compressed data, so a
     reader computing the ratio product in 32 bits rejects it, even one that skips
     the product when original_size <= compressed_size (mutation-tested by
     tools/test_wire_format_reference.py). The other three sit on the bin16/bin32
     edge: compressed_data of 65,535 and 65,536 B in bin, and 65,536 B as a legacy
     array32. Each checksum is the one field stdlib cannot derive: only the
     `xxhash` leg proves it is the true xxHash3-64 of the constructed input.
  8. The reject-vector set is exactly REJECT_BUILDERS, each `reject_vectors` entry
     equals what its builder derives from its legacy base, and the reader rejects
     it at its `reject_step` (step 8, the checksum, only on the `xxhash` leg), and
     at step 2 by the check its `reject_check` names: the decode-bounds pre-scan or
     the typed decode. Dropping any one of those bounds from the reader changes the
     outcome of that bound's vectors and of no other (mutation-tested by
     tools/test_wire_format_reference.py). On the lz4 leg it also pins the liblz4
     behaviour the spec cites: a short output for the length vector, and a refusal
     of the empty and undecodable blocks.
  9. The payload-reject set is exactly PAYLOAD_REJECT_BUILDERS. Each entry equals
     what its builder derives from its decode-bounds.json document, the reader
     accepts its envelope and returns that document, and the pre-scan rejects the
     document for the reasons decode-bounds.json records.
 10. The temporal-sentinel set is exactly TEMPORAL_SENTINELS, and each entry's
     payload is the canonical sentinel map whose `value` parses as its type.

Usage:
    python3 tools/wire-format-reference.py verify     # default
    python3 tools/wire-format-reference.py verify --require-extras
                                                      # fail if optional deps are
                                                      # missing (CI optional-deps leg)
    python3 tools/wire-format-reference.py generate   # (re)derive *_bin vectors

Three optional-dependency checks deepen `verify` when importable (all run in CI):
  - `xxhash`: the reader verifies every vector's checksum (Retrieve Flow steps
    7-8), pinned and constructed. `generate` needs it to add a constructed vector.
  - `msgpack`: third-encoder conformance — msgpack-python re-encodes both forms
    from decoded fields and must reproduce the pinned bytes byte-identically.
  - `lz4`: C-implementation (liblz4) decode conformance — liblz4 must decompress
    every vector's pinned compressed_data to the pinned input. Encoder agreement
    is a drift tripwire against LZ4_ENCODE_DIVERGENT, never a per-vector
    conformance rule (spec 'Compressed-byte reproducibility', LAB-1751): a vector
    liblz4 reproduces must keep reproducing, and a declared-divergent vector must
    keep the exact bytes mapped to its name — "differs from liblz4" alone is a
    one-bit check that any other valid LZ4 block would satisfy.

Both commands refuse to run under -O/PYTHONOPTIMIZE: every check in this file
is an `assert`, so an optimised `verify` would report a pass having tested
nothing, and an optimised `generate` would rewrite the fixture with its input
checks stripped. The guard is at module scope, so `import` cannot skip it
either; regression-tested by tools/test_wire_format_reference.py.
"""

from __future__ import annotations

import datetime
import importlib.util
import json
import sys
from collections.abc import Callable
from pathlib import Path
from types import ModuleType

_HERE = Path(__file__).resolve().parent
FIXTURE_PATH = _HERE.parent / "test-vectors" / "wire-format.json"


def _load_sibling(filename: str, module_name: str) -> ModuleType:
    """Import a sibling tool with a hyphenated filename."""
    spec = importlib.util.spec_from_file_location(module_name, _HERE / filename)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load tools/{filename}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


iv2 = _load_sibling("interop-v2-reference.py", "interop_v2_reference")  # LZ4 decoder, `construct`
db = _load_sibling("decode-bounds-reference.py", "decode_bounds_reference")  # the pre-scan's header walk

FIXTURE_VERSION = "1.4.0"
# The base vectors this fixture is pinned to contain. Checked as a SET, because every
# other integrity check here iterates the fixture's own vector list and therefore
# cannot see a vector that is simply absent: dropping a legacy base AND its `_bin`
# twin together left `generate`'s append-only diff empty and `verify` reporting "all 6
# vector pairs verified", exit 0. Same lesson as the
# original_size/input_size drift one level up — a name list derived from the artifact
# under test pins nothing, so the expected set has to live in code.
EXPECTED_BASE_VECTORS = frozenset(
    {
        "empty",
        "simple_string",
        "binary_data",
        "large_compressible",
        "json_like",
        "single_byte",
        "width_boundary_bin16",
        "width_boundary_bin8_max",
        "width_boundary_bin16_min",
    }
)
# compressed_data length each width-boundary base exists to pin. The twins' markers
# follow from it (<= 255 -> bin8, <= 65,535 -> bin16), so a re-pin that drifts the
# length off its edge would keep every other check green and silently stop testing
# the edge.
WIDTH_BOUNDARIES = {"width_boundary_bin8_max": 255, "width_boundary_bin16_min": 256, "width_boundary_bin16": 303}
# spec/wire-format.md 'Security Limits'. Pinned here so the fixture's own declared
# `limits` block cannot drift from the spec table: SDKs read their bounds from that
# block, so a fixture shipping max_uncompressed_size=1 with CI green would hand every
# downstream reader a wrong bound. `verify` compares the two. The per-vector check
# below additionally rejects an inflated declared original_size by name; note the
# ground-truth `original_size == len(input_hex)` assert would catch that case anyway,
# so this bound is about naming the spec limit that was breached, not about bounding
# an allocation. The compressed_data length cap and the 1000:1 bomb check are a
# reader's obligations, not this fixture verifier's.
SPEC_LIMITS = {
    "max_uncompressed_size": 512 * 1024 * 1024,
    "max_compressed_size": 512 * 1024 * 1024,
    "max_compression_ratio": 1000,
}
MAX_UNCOMPRESSED_SIZE = SPEC_LIMITS["max_uncompressed_size"]
MAX_COMPRESSED_SIZE = SPEC_LIMITS["max_compressed_size"]
MAX_RATIO = SPEC_LIMITS["max_compression_ratio"]
# The wrap helper reused from interop-v2 multiplies by its own constant.
assert MAX_RATIO == iv2.MAX_RATIO, "ratio limit differs from interop-v2-reference.py's"
# Smallest compressed_size whose ratio product overflows UNSIGNED 32 bits:
# ceil(2**32 / 1000) = 4,294,968. A signed 32-bit product overflows from 2,147,484 B;
# at this size both wrap to 704, so one vector catches both.
RATIO_WRAP_THRESHOLD = -(-(1 << 32) // MAX_RATIO)
# spec/wire-format.md 'Compressed-byte reproducibility' names WHICH vectors liblz4
# fails to reproduce on encode, and maps each to the bytes actually pinned. Encoder
# agreement is not a conformance rule, but the spec's claim about the set is a fact,
# so a change to it must fail CI and force the text to be re-read — otherwise the next
# `lz4==` bump rots the spec silently. The value is load-bearing: asserting only
# "these bytes differ from liblz4's output" is a one-bit check that ANY other valid
# LZ4 block satisfies, so a re-pin of the divergent vector to unrelated bytes passed.
# Byte-pinning the divergent vector is the only encode-side
# enforcement it has anywhere in the fleet.
# Base names only: twins carry the same compressed_data and are not iterated.
LZ4_ENCODE_DIVERGENT = {"large_compressible": "1f410100ffffffe960414141414141"}
if not LZ4_ENCODE_DIVERGENT.keys() <= EXPECTED_BASE_VECTORS:
    # A phantom name here is never compared against anything in the loop below, so it
    # would leave the spec's named set wrong with CI green.
    raise SystemExit(
        "BUG: LZ4_ENCODE_DIVERGENT names vectors not in EXPECTED_BASE_VECTORS: "
        f"{', '.join(sorted(LZ4_ENCODE_DIVERGENT.keys() - EXPECTED_BASE_VECTORS))}"
    )
ENVELOPE_FORMAT = (
    "MessagePack positional array (rmp_serde::to_vec): "
    "[compressed_data, checksum, original_size, format]. Vectors without an "
    "'envelope_encoding' field use the legacy array-of-integers encoding for "
    "compressed_data and are retained forever as legacy-read proof; their "
    "'*_bin' twins use msgpack bin (canonical for protocol 1.1+ writers). "
    "checksum always encodes as an array of 8 integers. Normative rules: "
    "spec/wire-format.md, 'Byte Layout' / 'Encoding compatibility'."
)
GENERATOR = (
    "six original legacy vectors: cachekit-core v0.2.0; width_boundary_bin16 "
    "legacy vector: cachekit-core v0.5.0 real writer; width_boundary_bin8_max and "
    "width_boundary_bin16_min legacy vectors: legacy re-encode of the fields cachekit "
    "0.22.0 (cachekit-core lz4_flex, identical to liblz4 1.9.4 here) writes for the "
    "first 253 and 254 bytes of width_boundary_bin16's input; *_bin vectors: "
    "tools/wire-format-reference.py generate - deterministic re-encode of the "
    "legacy fields, byte-verified against rmp-serde 1.3.1 + serde_bytes 0.11.19 "
    "output (LAB-783); constructed_vectors: tools/wire-format-reference.py "
    "generate - stdlib construction, checksum by xxhash 4.0.1 (xxHash 0.8.3); "
    "reject_vectors: tools/wire-format-reference.py generate - re-encode of legacy "
    "base fields with one check broken; payload_reject_vectors and "
    "temporal_sentinel_vectors: tools/wire-format-reference.py generate"
)
CONSTRUCTION_NOTE = (
    "constructed_vectors are too large to pin as hex. To build envelope or input "
    "bytes, repeat each segment's hex `count` times and concatenate the segments in "
    "order (the same list form as interop-v2.json). Readers MUST decode the "
    "constructed envelope to the constructed input."
)
WRAP_VECTOR = "envelope_ratio_product_wraps_32_bits"

# --- minimal MessagePack codec ------------------------------------------------
# Deliberately scoped to the types a StorageEnvelope uses. The encoder emits
# shortest-form headers only — the same choices rmp_serde makes — and `verify`
# proves that equivalence against the pinned legacy bytes on every run.


class _Reader:
    def __init__(self, buf: bytes):
        self.buf = buf
        self.pos = 0

    def take(self, n: int) -> bytes:
        if self.pos + n > len(self.buf):
            raise ValueError("truncated msgpack document")
        out = self.buf[self.pos : self.pos + n]
        self.pos += n
        return out

    def u8(self) -> int:
        return self.take(1)[0]

    def be(self, n: int) -> int:
        return int.from_bytes(self.take(n), "big")

    def peek(self) -> int:
        """Look at the next marker byte without consuming it (bounds-checked)."""
        if self.pos >= len(self.buf):
            raise ValueError("truncated msgpack document")
        return self.buf[self.pos]


def _decode_uint(r: _Reader) -> int:
    m = r.u8()
    if m <= 0x7F:
        return m
    if m == 0xCC:
        return r.be(1)
    if m == 0xCD:
        return r.be(2)
    if m == 0xCE:
        return r.be(4)
    if m == 0xCF:
        return r.be(8)
    raise ValueError(f"expected msgpack uint, got marker 0x{m:02x}")


def _decode_array_header(r: _Reader) -> int:
    m = r.u8()
    if 0x90 <= m <= 0x9F:
        return m & 0x0F
    if m == 0xDC:
        return r.be(2)
    if m == 0xDD:
        return r.be(4)
    raise ValueError(f"expected msgpack array, got marker 0x{m:02x}")


def _decode_str(r: _Reader) -> str:
    m = r.u8()
    if not 0xA0 <= m <= 0xBF:
        # format is a bounded registry token (e.g. "msgpack"), always fixstr.
        raise ValueError(f"expected msgpack fixstr, got marker 0x{m:02x}")
    return r.take(m & 0x1F).decode("utf-8")


def _decode_bytes_field(r: _Reader) -> tuple[bytes, str]:
    """Decode element[0]: either legacy array-of-ints or bin. Returns (data, encoding)."""
    m = r.peek()
    if m in (0xC4, 0xC5, 0xC6):
        r.u8()
        n = r.be({0xC4: 1, 0xC5: 2, 0xC6: 4}[m])
        return r.take(n), "bin"
    n = _decode_array_header(r)
    data = bytearray()
    for _ in range(n):
        v = _decode_uint(r)
        if v > 0xFF:
            raise ValueError(f"byte-array element out of range: {v}")
        data.append(v)
    return bytes(data), "int-array"


def _encode_uint(v: int) -> bytes:
    if v < 0:
        raise ValueError("negative uint")
    if v <= 0x7F:
        return bytes([v])
    if v <= 0xFF:
        return bytes([0xCC, v])
    if v <= 0xFFFF:
        return b"\xcd" + v.to_bytes(2, "big")
    if v <= 0xFFFFFFFF:
        return b"\xce" + v.to_bytes(4, "big")
    if v <= 0xFFFFFFFFFFFFFFFF:
        return b"\xcf" + v.to_bytes(8, "big")
    raise ValueError("uint too large for envelope fields")


def _encode_array_header(n: int) -> bytes:
    if n <= 0x0F:
        return bytes([0x90 | n])
    if n <= 0xFFFF:
        return b"\xdc" + n.to_bytes(2, "big")
    return b"\xdd" + n.to_bytes(4, "big")


def _encode_int_array(data: bytes) -> bytes:
    return _encode_array_header(len(data)) + b"".join(_encode_uint(b) for b in data)


def _encode_bin(data: bytes) -> bytes:
    n = len(data)
    if n <= 0xFF:
        return b"\xc4" + bytes([n]) + data
    if n <= 0xFFFF:
        return b"\xc5" + n.to_bytes(2, "big") + data
    return b"\xc6" + n.to_bytes(4, "big") + data


def _encode_str(s: str) -> bytes:
    raw = s.encode("utf-8")
    if len(raw) > 31:
        raise ValueError("format string too long for a fixstr registry token")
    return bytes([0xA0 | len(raw)]) + raw


# --- envelope <-> fields -------------------------------------------------------


def decode_envelope(env: bytes) -> tuple[bytes, bytes, int, str, str]:
    """Returns (compressed_data, checksum, original_size, format, element0_encoding)."""
    r = _Reader(env)
    if _decode_array_header(r) != 4:
        raise ValueError("StorageEnvelope must be a 4-element array")
    data, encoding = _decode_bytes_field(r)
    if _decode_array_header(r) != 8:
        raise ValueError("checksum must be an 8-element array")
    checksum = bytes(_decode_uint(r) for _ in range(8))
    original_size = _decode_uint(r)
    fmt = _decode_str(r)
    if r.pos != len(env):
        raise ValueError(f"{len(env) - r.pos} trailing bytes after envelope")
    return data, checksum, original_size, fmt, encoding


def encode_envelope(
    data: bytes, checksum: bytes, original_size: int, fmt: str, *, encoding: str
) -> bytes:
    element0 = _encode_bin(data) if encoding == "bin" else _encode_int_array(data)
    return (
        _encode_array_header(4)
        + element0
        + _encode_int_array(checksum)
        + _encode_uint(original_size)
        + _encode_str(fmt)
    )


# --- reader (spec/wire-format.md 'Retrieve Flow') ------------------------------


class EnvelopeReject(ValueError):
    """An envelope the Retrieve Flow must reject, tagged with the step that rejected it.

    The step is what `reject_vectors` pins: a verdict alone cannot tell a conforming
    reader from one missing a bound that a later step happens to cover.
    """

    def __init__(self, step: int, reason: str, check: str | None = None):
        super().__init__(f"step {step}: {reason}")
        self.step = step
        # Step 2 runs two checks, the pre-scan and the typed decode, and a vector that
        # breaks one is still rejected at step 2 by the other when the first is missing.
        self.check = check


# The reader's nesting bound. interop-mode.md's Decode bounds allow 32 to 1024; an
# envelope is 2 deep, so the floor costs nothing.
DEPTH_BOUND = db.MIN_DEPTH_FLOOR


def prescan(doc: bytes) -> str | None:
    """Step 2's structural pre-scan: the decode bound `doc` breaks, or None.

    The header-only walk of tools/decode-bounds-reference.py, so nothing is
    materialised: nesting past DEPTH_BOUND, or declared slots summed over the whole
    document past its length minus one. Truncation and trailing bytes are left to the
    typed decode, which rejects both. So is a type byte MessagePack never uses.
    """
    try:
        walked = db.walk(doc)
    except ValueError:
        return None
    if walked["nesting_depth"] > DEPTH_BOUND:
        return "depth"
    if walked["declared_slots"] > len(doc) - 1:
        return "overclaim"
    return None


def within_ratio(original_size: int, compressed_size: int) -> bool:
    """Retrieve Flow step 5's bound. Python ints never wrap, so this conforms by construction.

    A function rather than an inline comparison so tools/test_wire_format_reference.py
    can substitute 32-bit readers and show the published vectors catch them. It takes
    both sizes because one such reader skips the product when
    original_size <= compressed_size.
    """
    return original_size <= MAX_RATIO * compressed_size


def read_envelope(env: bytes, xxh3_64: Callable[[bytes], bytes] | None = None) -> bytes:
    """Retrieve Flow steps 1-9: envelope bytes -> original data, or EnvelopeReject.

    Step 2 pre-scans the envelope bytes before the typed decode. The payload this
    returns is a second untrusted document, which the caller decodes under the same
    bounds; `payload_reject_vectors` pins that. Steps 7-8 run only when `xxh3_64` is
    given (8 bytes, big-endian), because xxHash3-64 is not stdlib.
    """
    if len(env) > MAX_COMPRESSED_SIZE:
        raise EnvelopeReject(1, "envelope exceeds max compressed size")
    if (bound := prescan(env)) is not None:
        raise EnvelopeReject(2, f"decode bound exceeded ({bound})", "decode_bounds")
    try:
        data, checksum, original_size, _fmt, _encoding = decode_envelope(env)
    except ValueError as e:
        raise EnvelopeReject(2, f"malformed envelope: {e}", "typed_decode") from e
    # Step 3. Unreachable here, since compressed_data is a strict slice of the envelope
    # step 1 already bounded; kept so the reader reads as the spec's step list.
    if len(data) > MAX_COMPRESSED_SIZE:
        raise EnvelopeReject(3, "compressed_data exceeds max compressed size")
    if original_size > MAX_UNCOMPRESSED_SIZE:
        raise EnvelopeReject(4, "original_size exceeds max uncompressed size")
    if len(data) == 0:
        raise EnvelopeReject(5, "zero-length compressed_data")
    if not within_ratio(original_size, len(data)):
        raise EnvelopeReject(5, "compression ratio exceeds 1000:1 — decompression bomb")
    # Also step 9: the decoder rejects any output length other than original_size.
    try:
        out = iv2.lz4_block_decompress(data, original_size)
    except iv2.V2Error as e:
        raise EnvelopeReject(6, f"LZ4 decode failed: {e}") from e
    if xxh3_64 is not None and xxh3_64(out) != checksum:
        raise EnvelopeReject(8, "checksum mismatch — integrity failure")
    return out


# --- constructed vectors --------------------------------------------------------


def _expanding_envelope(compressed_size: int, encoding: str, checksum_of: Callable[[bytes], bytes]) -> dict:
    """The fields of an envelope whose compressed_data is exactly `compressed_size` bytes.

    The block is two sequences: a literal run followed by an offset-1 match of zeros,
    then the 5-literal final run LZ4's end-of-block rules require. So original_size is
    ~1.98 x compressed_size and larger than it. The input is a canonical msgpack bin32
    of zeros, so an SDK that deserialises the "msgpack" payload after unpacking still
    succeeds. Both encodings describe compressed_data as the same block segments; the
    legacy one writes each byte as a msgpack uint. `checksum_of` maps the input to its
    8-byte checksum: xxHash3-64 in `generate` and on the xxhash leg, the pinned value on
    the stdlib leg.
    """
    ext, last, literal_len, original_size = iv2.expanding_block_shape(compressed_size)
    input_header = b"\xc6" + (original_size - 5).to_bytes(4, "big")
    assert original_size - 5 > 0xFFFF, "the input must be a canonical bin32"
    input_construction = [
        {"hex": input_header.hex(), "count": 1},
        {"hex": "00", "count": original_size - len(input_header)},
    ]
    original = iv2.construct(input_construction)
    checksum = checksum_of(original)
    assert len(checksum) == 8, "checksum must be 8 bytes"
    # Everything before and after compressed_data's bytes: the outer fixarray(4) and
    # element[0]'s header; then the checksum array, original_size and format.
    if encoding == "bin":
        head = b"\x94" + _encode_bin(bytes(compressed_size))[:-compressed_size]
    else:
        head = b"\x94" + _encode_array_header(compressed_size)
    tail = encode_envelope(b"", checksum, original_size, "msgpack", encoding="bin")[3:]

    def raw(block: bytes) -> str:
        return (block if encoding == "bin" else b"".join(_encode_uint(b) for b in block)).hex()

    envelope_construction = [
        {"hex": head.hex() + raw(b"\xff"), "count": 1},
        {"hex": raw(b"\xff"), "count": ext},
        {"hex": raw(bytes([last]) + input_header), "count": 1},
        {"hex": raw(b"\x00"), "count": literal_len - len(input_header)},
        {"hex": raw(b"\x01\x00"), "count": 1},
        {"hex": raw(b"\xff"), "count": ext},
        {"hex": raw(bytes([last, 0x50]) + bytes(5)) + tail.hex(), "count": 1},
    ]
    env = iv2.construct(envelope_construction)
    block = iv2.construct([{"hex": "ff", "count": ext + 1}]) + bytes([last]) + input_header
    block += bytes(literal_len - len(input_header)) + b"\x01\x00" + b"\xff" * ext + bytes([last, 0x50]) + bytes(5)
    assert len(block) == compressed_size, "block is not compressed_size bytes"
    assert env == encode_envelope(block, checksum, original_size, "msgpack", encoding=encoding), (
        f"construction is not the canonical {encoding} envelope"
    )
    assert iv2.lz4_block_decompress(block, original_size) == original, "block does not decompress to the input"
    return {
        "format": "msgpack",
        "envelope_encoding": encoding,
        "original_size": original_size,
        "compressed_size": compressed_size,
        "envelope_size": len(env),
        "checksum_hex": checksum.hex(),
        "envelope_construction": envelope_construction,
        "input_construction": input_construction,
    }


def build_wrap_threshold_vector(checksum_of: Callable[[bytes], bytes]) -> dict:
    """Canonical bin envelope whose compressed_data is exactly RATIO_WRAP_THRESHOLD bytes.

    original_size is far inside the 1000:1 bound, far above the 704 B a 32-bit product
    yields, and larger than compressed_size, so a reader that skips the product when
    original_size <= compressed_size still has to compute it.
    """
    compressed_size = RATIO_WRAP_THRESHOLD
    fields = _expanding_envelope(compressed_size, "bin", checksum_of)
    wrapped = iv2.ratio_bound_u32_wrapped(compressed_size)
    return {
        "name": WRAP_VECTOR,
        "description": (
            f"canonical bin envelope whose compressed_data is {compressed_size} B = ceil(2^32/1000), the "
            "first size at which 1000 * compressed_size overflows unsigned 32 bits. original_size is larger "
            "than compressed_size and well inside the 1000:1 bound, so readers MUST accept it and return the "
            f"constructed input. A reader that computes the product in 32-bit width gets {wrapped} instead "
            "(signed or unsigned wrap alike) and rejects it as a ratio bomb; so does one that rejects on "
            "32-bit overflow, and a 32-bit one that skips the product when original_size <= compressed_size. A "
            "pointer-width product passes it on a 64-bit host, so a pass there proves nothing about a "
            "32-bit target. spec/wire-format.md#decompression-bomb-detection says which implementations "
            "must run it and on which targets."
        ),
        **fields,
    }


# The bin16/bin32 edge. A fixture pair there would need ~260 KB of incompressible hex
# (spec 'Encoding compatibility'), so these carry the expanding zeros block instead. No
# compressor emits that block for its input, so a writer test reaches them only through
# an encoder given the fields, never through a write path that compresses the input.
BIN16_MAX = "envelope_bin16_max"
BIN32_MIN = "envelope_bin32_min"
ARRAY32_MIN = "envelope_legacy_array32_min"


def build_bin16_max(checksum_of: Callable[[bytes], bytes]) -> dict:
    return {
        "name": BIN16_MAX,
        "description": (
            "canonical bin envelope whose compressed_data is 65535 B, the longest a bin16 holds, so the "
            "shortest-form marker is 0xc5 with length ffff. Readers MUST accept it and return the "
            "constructed input. A writer whose bin16 limit sits below 65535 B encodes these fields as bin32. "
            "The block is not compressor output, so a writer test feeds the fields to its envelope encoder."
        ),
        **_expanding_envelope(0xFFFF, "bin", checksum_of),
    }


def build_bin32_min(checksum_of: Callable[[bytes], bytes]) -> dict:
    return {
        "name": BIN32_MIN,
        "description": (
            "canonical bin envelope whose compressed_data is 65536 B, one past the bin16 maximum, so the "
            "shortest-form marker is 0xc6 with length 00010000. Readers MUST accept it and return the "
            "constructed input. It is the only bin32 envelope in the file below the multi-megabyte "
            f"{WRAP_VECTOR}. The block is not compressor output, so a writer test feeds the fields to its "
            "envelope encoder."
        ),
        **_expanding_envelope(0x10000, "bin", checksum_of),
    }


def build_array32_min(checksum_of: Callable[[bytes], bytes]) -> dict:
    return {
        "name": ARRAY32_MIN,
        "description": (
            f"the fields of {BIN32_MIN} in the legacy encoding: compressed_data is an array32 (0xdd) of 65536 "
            "integers, each byte its shortest msgpack uint. Readers MUST accept it and return the constructed "
            "input; no legacy vector in the vectors group passes array16."
        ),
        **_expanding_envelope(0x10000, "int-array", checksum_of),
    }


# name -> builder. The expected constructed-vector set lives in code, for the same
# reason as EXPECTED_BASE_VECTORS: a set read from the fixture pins nothing.
CONSTRUCTED_BUILDERS: dict[str, Callable[[Callable[[bytes], bytes]], dict]] = {
    WRAP_VECTOR: build_wrap_threshold_vector,
    BIN16_MAX: build_bin16_max,
    BIN32_MIN: build_bin32_min,
    ARRAY32_MIN: build_array32_min,
}


# --- reject vectors --------------------------------------------------------------
# Each is derived from a legacy base vector, so `generate` needs no xxhash: a canonical
# bin envelope, except the step-2 vectors, whose break is in the encoding itself. Step-2
# vectors name the check that rejects them (`reject_check`). Each breaks one Retrieve Flow check, and dropping that check alone
# changes the outcome of that check's vectors and no other vector's (mutation-tested by
# tools/test_wire_format_reference.py). `reject_step` is the step at which the reference
# reader rejects it; spec/wire-format.md 'Reject vectors' says what an SDK asserts.
# Steps 1 and 3 have none: step 1 needs a 512 MiB + 1 B envelope, and step 3 cannot
# fire once step 1 has passed.

# A literal-length extension that never ends, carried by the size-cap and ratio vectors.
# Strict decoders (liblz4, lz4_flex) refuse it. spec/wire-format.md 'Reject vectors' says
# which late-check readers it detects and which it does not.
UNDECODABLE_BLOCK = b"\xf0" + b"\xff" * 999
RATIO_REJECT = "reject_ratio_bomb"


def _reject_vector(
    name: str, step: int, base: dict, data: bytes, checksum: bytes, original_size: int, description: str,
    *, env: bytes | None = None, encoding: str = "bin", check: str | None = None,
) -> dict:
    """A reject vector: the canonical envelope of these fields, or `env` where the break is in the encoding."""
    if env is None:
        env = encode_envelope(data, checksum, original_size, base["format"], encoding=encoding)
    vec = {"name": name, "description": description, "reject_step": step}
    if check is not None:
        vec["reject_check"] = check
    return {
        **vec,
        "derived_from": base["name"],
        "format": base["format"],
        "envelope_encoding": encoding,
        "original_size": original_size,
        "compressed_size": len(data),
        "envelope_hex": env.hex(),
        "envelope_size": len(env),
    }


def _base_fields(bases: dict[str, dict], name: str) -> tuple[dict, bytes, bytes, bytes]:
    """(base vector, compressed_data, checksum, input) of a legacy base vector."""
    base = bases[name]
    data, checksum, _size, _fmt, _encoding = decode_envelope(bytes.fromhex(base["envelope_hex"]))
    return base, data, checksum, bytes.fromhex(base["input_hex"])


def build_reject_size_cap(bases: dict[str, dict]) -> dict:
    base, _data, checksum, _inp = _base_fields(bases, "simple_string")
    size = MAX_UNCOMPRESSED_SIZE + 1
    return _reject_vector(
        "reject_original_size_over_cap", 4, base, UNDECODABLE_BLOCK, checksum, size,
        f"original_size {size} B, one byte over the 512 MiB max_uncompressed_size, with a "
        f"{len(UNDECODABLE_BLOCK)} B compressed_data that is not a valid LZ4 block (a literal-length "
        "extension that never ends). Readers MUST reject it. An SDK test asserts the size-cap error, and that "
        "the read's allocation high-water stayed below original_size (spec/wire-format.md#reject-vectors). The "
        "reference reader rejects it at Retrieve Flow step 4. A reader without step 4 rejects it at step 5, "
        "by the ratio bound. One that decompresses first with a strict decoder and lets its error propagate "
        "never raises the size-cap error, and one that allocates an output sized from original_size first "
        "fails the allocation bound.",
    )


def build_reject_size_wraps_u32(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    size = (1 << 32) + len(inp)
    return _reject_vector(
        "reject_original_size_wraps_u32", 4, base, data, checksum, size,
        f"simple_string's compressed_data and checksum with original_size 2^32 + {len(inp)} = {size} B, "
        "encoded as msgpack uint64. Readers MUST reject it before decompression. An SDK test asserts the "
        "size-cap error, or a Retrieve Flow step-2 error from a range-checked decode into a narrower type; "
        "never a length or checksum error. The reference reader rejects it at step 4. A reader that truncates "
        f"original_size to its low 32 bits reads {len(inp)} and accepts it; one that joins the two 32-bit "
        f"halves reads {len(inp) + 1} and rejects it only with a length error.",
    )


def build_reject_zero_length(bases: dict[str, dict]) -> dict:
    base, _data, checksum, _inp = _base_fields(bases, "empty")
    return _reject_vector(
        "reject_zero_length_compressed_data", 5, base, b"", checksum, 0,
        "empty compressed_data with original_size 0 and the checksum of the empty input. Readers MUST reject "
        "it. An SDK test asserts the zero-length error; the ratio bound cannot raise it, because 0 <= 1000 * 0. "
        "The reference reader rejects it at Retrieve Flow step 5. A reader without the zero-length check hands "
        "an empty block to its LZ4 decoder, which rejects it at step 6 if it refuses an empty block, as liblz4 "
        "does, and accepts it if it decodes one to empty output.",
    )


def build_reject_ratio_bomb(bases: dict[str, dict]) -> dict:
    base, _data, checksum, _inp = _base_fields(bases, "simple_string")
    n = len(UNDECODABLE_BLOCK)
    size = MAX_RATIO * n + 1
    return _reject_vector(
        RATIO_REJECT, 5, base, UNDECODABLE_BLOCK, checksum, size,
        f"original_size {size} B = 1000 * {n} + 1, one byte past the 1000:1 bound, with a {n} B "
        "compressed_data that is not a valid LZ4 block. Readers MUST reject it. An SDK test asserts the ratio "
        "error, and that the read's allocation high-water stayed below original_size "
        "(spec/wire-format.md#reject-vectors). The reference reader rejects it at Retrieve Flow step 5. A "
        "reader without the ratio check, or one that decompresses first with a strict decoder and lets its "
        "error propagate, never raises "
        "the ratio error, and one that allocates an output sized from original_size first fails the allocation "
        "bound.",
    )


def build_reject_length_mismatch(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    size = len(inp) + 1
    return _reject_vector(
        "reject_decompressed_length_mismatch", 6, base, data, checksum, size,
        f"simple_string's compressed_data and checksum with original_size {size} B, one more than the "
        f"{len(inp)} B the block decodes to, and inside every size and ratio bound. Readers MUST reject it. "
        "An SDK test asserts a length error, at Retrieve Flow step 6 or step 9, and not a checksum error. The "
        "reference reader's decoder (tools/wire-format-reference.py) rejects any output length other than "
        "original_size, at step 6. A reader whose decoder returns a shorter output without error, as liblz4 "
        "does, rejects it at step 9; both conform. A reader with neither check accepts it, because the checksum "
        "matches the decoded bytes. A reader that zero-pads the output to original_size fails the checksum, or "
        "accepts it if it checksums before padding; neither is a length error.",
    )


def build_reject_checksum(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    # First and last bytes, so a reader comparing only either 32-bit half still rejects it.
    flipped = bytes([checksum[0] ^ 0x01]) + checksum[1:7] + bytes([checksum[7] ^ 0x01])
    return _reject_vector(
        "reject_checksum_mismatch", 8, base, data, flipped, len(inp),
        "simple_string's envelope with the first and last checksum bytes flipped (xor 0x01). Readers MUST "
        "reject it; an SDK test asserts the rejection. The reference reader rejects it at Retrieve Flow step 8. "
        "A reader without step 8 accepts it.",
    )


def build_reject_arity(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    env = b"\x95" + encode_envelope(data, checksum, len(inp), base["format"], encoding="bin")[1:] + b"\xc0"
    return _reject_vector(
        "reject_envelope_arity_5", 2, base, data, checksum, len(inp),
        "simple_string_bin's four fields followed by a fifth element, nil, in a fixarray(5). Readers MUST "
        "reject it at Retrieve Flow step 2's typed decode. An SDK test asserts that typed-decode error. A reader "
        "that takes the first four elements of whatever array it decodes accepts it and returns simple_string's "
        "input, because every field and the checksum are intact.",
        env=env, check="typed_decode",
    )


def build_reject_checksum_arity(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    env = (
        b"\x94" + _encode_bin(data) + _encode_int_array(checksum + b"\x00")
        + _encode_uint(len(inp)) + _encode_str(base["format"])
    )
    return _reject_vector(
        "reject_checksum_nine_elements", 2, base, data, checksum, len(inp),
        "simple_string_bin with a ninth integer, 0, appended to the checksum array. Readers MUST reject it at "
        "Retrieve Flow step 2's typed decode: checksum is exactly 8 integers. An SDK test asserts that "
        "typed-decode error. A reader that compares the first 8 checksum bytes accepts it, because they are "
        "the true checksum.",
        env=env, check="typed_decode",
    )


def build_reject_element_range(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    i = 2  # the first literal, 'h' (0x68)
    elements = [_encode_uint(b) for b in data]
    elements[i] = _encode_uint(0x100 | data[i])
    env = (
        b"\x94" + _encode_array_header(len(data)) + b"".join(elements) + _encode_int_array(checksum)
        + _encode_uint(len(inp)) + _encode_str(base["format"])
    )
    return _reject_vector(
        "reject_legacy_element_above_255", 2, base, data, checksum, len(inp),
        f"simple_string's legacy envelope with compressed_data element {i} written as uint16 "
        f"{0x100 | data[i]} (cd {0x100 | data[i]:04x}) instead of {data[i]}. Readers MUST reject it at "
        "Retrieve Flow step 2's typed decode: each element is a byte. An SDK test asserts that typed-decode "
        f"error. A reader that keeps an element's low 8 bits (JavaScript's Uint8Array.from) reads {data[i]} "
        "and accepts it, because the block and checksum then match simple_string's input.",
        env=env, encoding="int-array", check="typed_decode",
    )


def build_reject_overclaim(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    env = bytearray(encode_envelope(data, checksum, len(inp), base["format"], encoding="bin"))
    env[2] = len(env) - 3  # bin8 claims every byte after its header
    env = bytes(env)
    walked = db.walk(env)
    assert walked["per_header_fits"] and walked["declared_slots"] > len(env) - 1, "not a whole-document overclaim"
    return _reject_vector(
        "reject_envelope_slots_overclaim", 2, base, env[3:], checksum, len(inp),
        f"simple_string_bin with compressed_data's bin8 length raised from {len(data)} to {len(env) - 3}, every "
        f"byte after its header. Each header fits the input that follows it, but the declared slots, summed over "
        f"the document, are {walked['declared_slots']}, past the input length minus one ({len(env) - 1}). Readers "
        "MUST reject it at Retrieve Flow step 2's pre-scan, before anything is materialised. An SDK test asserts "
        "the pre-scan's own error (spec/interop-mode.md#decode-bounds). Every decoder also rejects it as "
        "truncated, so only that assertion catches a reader without the pre-scan, or with per-header checks only.",
        env=env, check="decode_bounds",
    )


def build_reject_size_sign_bit(bases: dict[str, dict]) -> dict:
    base, data, checksum, inp = _base_fields(bases, "simple_string")
    size = (1 << 63) + len(inp)
    return _reject_vector(
        "reject_original_size_sign_bit", 4, base, data, checksum, size,
        f"simple_string's compressed_data and checksum with original_size 2^63 + {len(inp)} = {size} B, encoded "
        "as msgpack uint64. Readers MUST reject it before decompression. An SDK test asserts the size-cap error, "
        "or a Retrieve Flow step-2 error from a range-checked decode into a narrower type; never a length, "
        "allocation or checksum error. The reference reader rejects it at step 4. A reader that reinterprets "
        f"the uint64 as a signed i64 reads {size - (1 << 64)}, which passes the size cap and the ratio bound, "
        f"and fails later or crashes. One that truncates to 32 bits reads {len(inp)} and accepts it.",
    )


def build_reject_ratio_float32(bases: dict[str, dict]) -> dict:
    base, _data, checksum, _inp = _base_fields(bases, "simple_string")
    n = FLOAT32_RATIO_SIZE
    size = MAX_RATIO * n + 1
    return _reject_vector(
        FLOAT32_REJECT, 5, base, b"\xf0" + b"\xff" * (n - 1), checksum, size,
        f"original_size {size} B = 1000 * {n} + 1, one byte past the 1000:1 bound, with a {n} B compressed_data "
        f"that is not a valid LZ4 block. Readers MUST reject it. An SDK test asserts the ratio error. The "
        "reference reader rejects it at Retrieve Flow step 5. A ratio taken in float32 reads exactly 1000 here, "
        f"whether both operands are rounded ({size} becomes {MAX_RATIO * n}) or only the quotient, so it never "
        "raises the ratio error; neither does a truncating division. reject_ratio_bomb, at 1000.001, catches "
        "the division but neither float32 ratio.",
    )


FLOAT32_RATIO_SIZE = 1 << 15  # the smallest size where a float32 quotient also drops a one-byte excess
FLOAT32_REJECT = "reject_ratio_float32_rounds"

# name -> builder, in fixture order. The expected reject-vector set lives in code for
# the same reason as EXPECTED_BASE_VECTORS: a set read from the fixture pins nothing.
REJECT_BUILDERS: dict[str, Callable[[dict[str, dict]], dict]] = {
    "reject_original_size_over_cap": build_reject_size_cap,
    "reject_original_size_wraps_u32": build_reject_size_wraps_u32,
    "reject_zero_length_compressed_data": build_reject_zero_length,
    RATIO_REJECT: build_reject_ratio_bomb,
    "reject_decompressed_length_mismatch": build_reject_length_mismatch,
    "reject_checksum_mismatch": build_reject_checksum,
    "reject_envelope_arity_5": build_reject_arity,
    "reject_checksum_nine_elements": build_reject_checksum_arity,
    "reject_legacy_element_above_255": build_reject_element_range,
    "reject_envelope_slots_overclaim": build_reject_overclaim,
    "reject_original_size_sign_bit": build_reject_size_sign_bit,
    FLOAT32_REJECT: build_reject_ratio_float32,
}
LENGTH_REJECT = "reject_decompressed_length_mismatch"
ZERO_LENGTH_REJECT = "reject_zero_length_compressed_data"
UNDECODABLE_REJECTS = ("reject_original_size_over_cap", RATIO_REJECT)


# --- payload reject vectors ------------------------------------------------------
# The payload an envelope returns is untrusted MessagePack too (spec 'Security Limits').
# Each vector is a valid envelope, accepted by the Retrieve Flow, whose payload is a
# decode-bounds.json reject document; the SDK's payload decode must reject it. The block
# is literals-only, which every LZ4 decoder reads; a compressor may emit other bytes.
DECODE_BOUNDS_PATH = _HERE.parent / "test-vectors" / "decode-bounds.json"
PAYLOAD_REJECT_SOURCES = ("array32_max_claim_alone", "nested_array16_each_header_fits_sum_overclaims")


def _literal_block(data: bytes) -> bytes:
    """A literals-only LZ4 block: one sequence, no match."""
    n = len(data)
    if n < 15:
        return bytes([n << 4]) + data
    rest, ext = n - 15, bytearray()
    while rest >= 255:
        ext.append(255)
        rest -= 255
    return b"\xf0" + bytes(ext) + bytes([rest]) + data


def _payload_reject_builder(source: str) -> Callable[[Callable[[bytes], bytes]], dict]:
    def build(checksum_of: Callable[[bytes], bytes]) -> dict:
        doc = json.loads(DECODE_BOUNDS_PATH.read_text(encoding="utf-8"))
        vec = next(v for v in doc["reject_vectors"] if v["name"] == source)
        payload = bytes.fromhex(vec["input_hex"])
        block = _literal_block(payload)
        checksum = checksum_of(payload)
        assert len(checksum) == 8, "checksum must be 8 bytes"
        env = encode_envelope(block, checksum, len(payload), "msgpack", encoding="bin")
        return {
            "name": f"payload_{source}",
            "description": (
                f"canonical bin envelope that every Retrieve Flow check accepts, whose payload is "
                f"decode-bounds.json's {source} ({len(payload)} B, reject reasons: "
                f"{', '.join(vec['reject_reasons'])}). The SDK's decode of that payload MUST reject it before "
                "materialising it; an SDK test drives the envelope through its read path and asserts its "
                "pre-scan's own error (spec/interop-mode.md#decode-bounds). A reader that pre-scans the "
                "envelope's bytes but decodes the payload unguarded passes every reject vector and fails this. "
                "compressed_data is a literals-only block."
            ),
            "derived_from": f"decode-bounds.json:{source}",
            "reject_reasons": vec["reject_reasons"],
            "format": "msgpack",
            "envelope_encoding": "bin",
            "original_size": len(payload),
            "compressed_size": len(block),
            "checksum_hex": checksum.hex(),
            "envelope_hex": env.hex(),
            "envelope_size": len(env),
            "input_hex": payload.hex(),
        }

    return build


PAYLOAD_REJECT_BUILDERS: dict[str, Callable[[Callable[[bytes], bytes]], dict]] = {
    f"payload_{s}": _payload_reject_builder(s) for s in PAYLOAD_REJECT_SOURCES
}


# --- temporal sentinel vectors ---------------------------------------------------
# spec 'Datetime Extension Format': the maps every SDK revives as a temporal type, the
# spec's own three examples. type -> (sentinel key, value).
TEMPORAL_SENTINELS = {
    "datetime": ("__datetime__", "2025-11-14T10:30:00+00:00"),
    "date": ("__date__", "2025-11-14"),
    "time": ("__time__", "10:30:00"),
}


def build_temporal_sentinel(kind: str) -> dict:
    key, value = TEMPORAL_SENTINELS[kind]
    payload = b"\x82" + _encode_str(key) + b"\xc3" + _encode_str("value") + _encode_str(value)
    return {
        "name": f"temporal_sentinel_{kind}",
        "description": (
            f"the MessagePack map {{\"{key}\": true, \"value\": \"{value}\"}}, as a payload. An SDK's "
            f"deserialization MUST revive it as its temporal type for a {kind}, equal to {value}, not "
            "return the map."
        ),
        "payload_hex": payload.hex(),
        "revives_to": {"type": kind, "iso": value},
    }


def _load_xxh3() -> Callable[[bytes], bytes] | None:
    try:
        import xxhash  # type: ignore[import-untyped]
    except ImportError:
        return None
    return lambda data: xxhash.xxh3_64(data).digest()  # digest() is big-endian


# --- generate / verify ----------------------------------------------------------


def _load() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _split_vectors(fixture: dict) -> tuple[list[dict], dict[str, dict]]:
    legacy = [v for v in fixture["vectors"] if "envelope_encoding" not in v]
    bins = {v["name"]: v for v in fixture["vectors"] if v.get("envelope_encoding") == "bin"}
    # Fail closed: every vector must classify as exactly one of the two sets,
    # with no duplicate names — otherwise verify would silently skip it (and
    # generate would silently drop it from the append-only fixture). Named
    # separately, and caught by both callers, so the failure says WHICH vector
    # is unusable instead of exiting via a bare traceback.
    if len(legacy) + len(bins) != len(fixture["vectors"]):
        classified = {v["name"] for v in legacy} | set(bins)
        stray = [v["name"] for v in fixture["vectors"] if v["name"] not in classified]
        raise ValueError(
            "fixture vector(s) classify as neither legacy nor bin (envelope_encoding "
            f"must be absent or 'bin'): {', '.join(sorted(stray))}"
        )
    names = [v["name"] for v in legacy]
    if len(set(names)) != len(names):
        dupes = sorted({n for n in names if names.count(n) > 1})
        raise ValueError(f"fixture contains duplicate-named legacy vector(s): {', '.join(dupes)}")
    return legacy, bins


def _base_set_error(legacy: list[dict]) -> str | None:
    """Compare the fixture's base-vector set against EXPECTED_BASE_VECTORS.

    Absence is the one drift class every per-vector check is blind to, because they
    all iterate the fixture's own list. Returns a message, or None when the set is
    exactly as pinned.
    """
    present = {v["name"] for v in legacy}
    missing = EXPECTED_BASE_VECTORS - present
    unexpected = present - EXPECTED_BASE_VECTORS
    if not missing and not unexpected:
        return None
    parts = []
    if missing:
        parts.append(f"missing base vector(s): {', '.join(sorted(missing))}")
    if unexpected:
        parts.append(f"unexpected base vector(s): {', '.join(sorted(unexpected))}")
    return (
        f"fixture base-vector set drifted — {'; '.join(parts)}. A dropped base and its "
        "'_bin' twin are invisible to every per-vector check; add a genuinely new "
        "vector to EXPECTED_BASE_VECTORS deliberately, and never remove one."
    )


def _bin_twin(base: dict) -> dict:
    data, checksum, size, fmt, encoding = decode_envelope(bytes.fromhex(base["envelope_hex"]))
    assert encoding == "int-array", f"[{base['name']}] base vector is not legacy-encoded"
    env = encode_envelope(data, checksum, size, fmt, encoding="bin")
    twin = dict(base)  # preserves key order of the legacy vectors
    twin["name"] = base["name"] + "_bin"
    twin["description"] = (
        f"bin-encoded twin of '{base['name']}': identical fields, compressed_data "
        "as msgpack bin (canonical writer encoding, protocol 1.1+)"
    )
    twin["envelope_hex"] = env.hex()
    twin["envelope_size"] = len(env)
    twin["envelope_encoding"] = "bin"
    twin["derived_from"] = base["name"]
    return twin


def generate() -> int:
    try:
        fixture = _load()
        legacy, _ = _split_vectors(fixture)
    except ValueError as e:
        print(f"REFUSED: unusable fixture: {e}", file=sys.stderr)
        return 1
    # Refuse before the write if the base set itself has drifted. The `lost` diff below
    # is derived from the fixture on both sides, so dropping a base AND its twin
    # together nets to zero there and `generate` would happily write the shrunken
    # fixture.
    set_error = _base_set_error(legacy)
    if set_error:
        print(f"REFUSED: {set_error}", file=sys.stderr)
        return 1
    rebuilt = legacy + [_bin_twin(v) for v in legacy]
    # Append-only, as the fixture's own contract requires (LAB-783), and the same
    # refusal the sibling python-frame-reference.py uses for its whole-fixture rebuild
    # (its upsert-by-name applies only to the single-vector append mode, LAB-1203 — do
    # not "align" this to an upsert). Rebuilding from the legacy set alone silently
    # drops any committed vector that is not a derived twin, and `verify`'s orphan FAIL
    # names `generate` as the remedy — so the repair step completes the data loss.
    # Refuse instead: this file is vendored and sha256-pinned downstream, and a
    # deletion here is invisible until an SDK's conformance coverage has already shrunk.
    lost = {v["name"] for v in fixture["vectors"]} - {v["name"] for v in rebuilt}
    if lost:
        print(
            f"REFUSED: generate would drop committed vector(s): {', '.join(sorted(lost))}. "
            "A bin vector with no legacy base is not regenerable from the legacy set — "
            "restore the missing base vector rather than regenerating.",
            file=sys.stderr,
        )
        return 1
    # Constructed and payload-reject vectors are append-only too: a committed one is kept
    # as it is (verify compares it to its builder), and only a missing one is built.
    # Building needs the true xxHash3-64 of the input, which stdlib cannot compute.
    checksummed = {}
    for group, builders in (("constructed_vectors", CONSTRUCTED_BUILDERS), ("payload_reject_vectors", PAYLOAD_REJECT_BUILDERS)):
        vecs = list(fixture.get(group, []))
        missing = [n for n in builders if n not in {v.get("name") for v in vecs}]
        if missing:
            xxh3_64 = _load_xxh3()
            if xxh3_64 is None:
                print(
                    f"REFUSED: building {group} {', '.join(missing)} needs the `xxhash` package for the checksum",
                    file=sys.stderr,
                )
                return 1
            vecs += [builders[n](xxh3_64) for n in missing]
        checksummed[group] = vecs
    constructed = checksummed["constructed_vectors"]
    temporal = list(fixture.get("temporal_sentinel_vectors", []))
    present = {v.get("name") for v in temporal}
    temporal += [build_temporal_sentinel(k) for k in TEMPORAL_SENTINELS if f"temporal_sentinel_{k}" not in present]
    # Reject vectors: append-only on the same terms. They derive from the legacy
    # bases alone, so building one needs no optional package.
    bases = {v["name"]: v for v in legacy}
    rejects = list(fixture.get("reject_vectors", []))
    present = {v.get("name") for v in rejects}
    rejects += [build(bases) for n, build in REJECT_BUILDERS.items() if n not in present]
    fixture["vectors"] = rebuilt
    fixture["constructed_vectors"] = constructed
    fixture["reject_vectors"] = rejects
    fixture["payload_reject_vectors"] = checksummed["payload_reject_vectors"]
    fixture["temporal_sentinel_vectors"] = temporal
    fixture["construction_note"] = CONSTRUCTION_NOTE
    fixture["envelope_format"] = ENVELOPE_FORMAT
    fixture["generator"] = GENERATOR
    fixture["version"] = FIXTURE_VERSION
    fixture = dict(sorted(fixture.items()))  # top level only: vector key order is pinned
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(
        f"wrote {FIXTURE_PATH.name}: {len(legacy)} legacy + {len(legacy)} bin + "
        f"{len(constructed)} constructed + {len(rejects)} reject + "
        f"{len(checksummed['payload_reject_vectors'])} payload-reject + {len(temporal)} temporal-sentinel vectors"
    )
    return 0


def _verify_constructed(vec: dict, xxh3_64, msgpack, lz4_block) -> str:
    """Validate one constructed vector: builder equality, then a full read.

    Returns a one-line summary, or raises like _verify_vector.
    """
    builder = CONSTRUCTED_BUILDERS[vec["name"]]
    pinned = bytes.fromhex(vec["checksum_hex"])
    # The builder derives every field from stdlib except the checksum. On the xxhash
    # leg it computes the checksum too, so equality proves the pinned one is the true
    # xxHash3-64 of the input; on the stdlib leg it takes the pinned value on trust.
    expected = builder(xxh3_64 if xxh3_64 is not None else lambda _original: pinned)
    for key in sorted(expected.keys() | vec.keys()):
        assert vec.get(key) == expected.get(key), f"field {key!r} differs from what the builder derives"
    env = iv2.construct(vec["envelope_construction"])
    original = iv2.construct(vec["input_construction"])
    assert read_envelope(env, xxh3_64) == original, "reader does not return the constructed input"

    if msgpack is not None:
        data, checksum, size, fmt, encoding = decode_envelope(env)
        element0 = data if encoding == "bin" else list(data)
        assert msgpack.unpackb(env, raw=False) == [element0, list(checksum), size, fmt], "msgpack-python decode mismatch"
        assert msgpack.packb([element0, list(checksum), size, fmt], use_bin_type=True) == env, (
            "msgpack-python re-encode mismatch"
        )
    if lz4_block is not None:
        data = decode_envelope(env)[0]
        try:
            got = lz4_block.decompress(data, uncompressed_size=vec["original_size"])
        except (lz4_block.LZ4BlockError, OverflowError) as e:
            raise AssertionError(f"liblz4 rejects the constructed compressed_data: {e}") from e
        assert got == original, "liblz4 does not decompress the constructed compressed_data to the input"
    checked = "checksum verified" if xxh3_64 is not None else "checksum NOT verified (no xxhash)"
    return f"compressed_size {vec['compressed_size']} B, original_size {vec['original_size']} B, {checked}"


def _verify_payload_reject(vec: dict, xxh3_64, msgpack) -> str:
    """Validate one payload-reject vector: builder equality, a full read, then the payload's rejection.

    Returns a one-line summary, or raises like _verify_vector.
    """
    pinned = bytes.fromhex(vec["checksum_hex"])
    expected = PAYLOAD_REJECT_BUILDERS[vec["name"]](xxh3_64 if xxh3_64 is not None else lambda _payload: pinned)
    for key in sorted(expected.keys() | vec.keys()):
        assert vec.get(key) == expected.get(key), f"field {key!r} differs from what the builder derives"
    payload = bytes.fromhex(vec["input_hex"])
    assert read_envelope(bytes.fromhex(vec["envelope_hex"]), xxh3_64) == payload, "reader does not return the payload"
    reasons = set(vec["reject_reasons"]) & {"depth", "overclaim"}
    assert prescan(payload) in reasons, f"pre-scan gives {prescan(payload)!r}, not one of {sorted(reasons)}"
    if msgpack is not None:
        try:
            msgpack.unpackb(payload)
        except ValueError:
            pass
        else:
            raise AssertionError("msgpack-python decodes the payload")
    checked = "checksum verified" if xxh3_64 is not None else "checksum NOT verified (no xxhash)"
    return f"envelope accepted, payload rejected by the pre-scan ({prescan(payload)}), {checked}"


def _verify_temporal(vec: dict) -> str:
    """Validate one temporal-sentinel vector: builder equality, and a value that parses as its type."""
    kind = vec["name"].removeprefix("temporal_sentinel_")
    assert kind in TEMPORAL_SENTINELS, f"no temporal sentinel named {kind!r}"
    expected = build_temporal_sentinel(kind)
    for key in sorted(expected.keys() | vec.keys()):
        assert vec.get(key) == expected.get(key), f"field {key!r} differs from what the builder derives"
    parse = {"datetime": datetime.datetime, "date": datetime.date, "time": datetime.time}[kind].fromisoformat
    parse(vec["revives_to"]["iso"])  # raises ValueError if the value is not that type's ISO form
    return f"{TEMPORAL_SENTINELS[kind][0]} -> {kind} {vec['revives_to']['iso']}"


def _verify_reject(vec: dict, bases: dict[str, dict], xxh3_64, msgpack, lz4_block) -> str:
    """Validate one reject vector: builder equality, then rejection at its named step.

    Returns a one-line summary, or raises like _verify_vector.
    """
    expected = REJECT_BUILDERS[vec["name"]](bases)
    for key in sorted(expected.keys() | vec.keys()):
        assert vec.get(key) == expected.get(key), f"field {key!r} differs from what the builder derives"
    env = bytes.fromhex(vec["envelope_hex"])
    step = vec["reject_step"]
    check = vec.get("reject_check")
    if msgpack is not None and check is None:
        # A third decoder reads it as a well-formed envelope, so the rejection is the
        # bound's and not an encoding artefact of this codec.
        data, checksum, size, fmt, _encoding = decode_envelope(env)
        assert msgpack.unpackb(env, raw=False) == [data, list(checksum), size, fmt], "msgpack-python decode mismatch"
    elif msgpack is not None:
        # A typed-decode vector is well-formed MessagePack, so only the envelope's types
        # reject it; a decode-bounds vector is not, so a stock decoder rejects it too.
        try:
            msgpack.unpackb(env, raw=False)
            well_formed = True
        except ValueError:
            well_formed = False
        assert well_formed == (check == "typed_decode"), f"msgpack-python {'accepts' if well_formed else 'rejects'} it"
    lz4_note = ""
    if lz4_block is not None and vec["name"] == LENGTH_REJECT:
        # The step-9 check is not academic: liblz4 returns the short output without error.
        data = decode_envelope(env)[0]
        try:
            got = lz4_block.decompress(data, uncompressed_size=vec["original_size"])
        except (lz4_block.LZ4BlockError, OverflowError) as e:
            raise AssertionError(f"liblz4 raises on this vector instead of returning a short output: {e!r}") from e
        assert len(got) < vec["original_size"], "liblz4 no longer returns a short output for this vector"
        lz4_note = f"; liblz4 returns {len(got)} B without error"
    elif lz4_block is not None and vec["name"] in (ZERO_LENGTH_REJECT, RATIO_REJECT):
        # The spec says liblz4 refuses these blocks, so a decode-first reader fails rather than decodes.
        # Each at its own original_size, so an undersized destination cannot be the reason. The
        # size-cap vector carries the same block but would need a 512 MiB destination.
        data = decode_envelope(env)[0]
        try:
            lz4_block.decompress(data, uncompressed_size=vec["original_size"])
        except lz4_block.LZ4BlockError:
            lz4_note = "; liblz4 refuses the block"
        except OverflowError as e:
            raise AssertionError(f"liblz4 cannot take this vector's original_size: {e}") from e
        else:
            raise AssertionError("liblz4 now decodes this vector's compressed_data")
    if step == 8 and xxh3_64 is None:
        return "step 8 NOT verified (no xxhash)"
    try:
        read_envelope(env, xxh3_64)
    except EnvelopeReject as e:
        assert e.step == step, f"reader rejects at step {e.step}, not step {step}: {e}"
        # Step 2's pre-scan or typed decode; later steps name no check, and neither do their vectors.
        assert e.check == check, f"reader rejects by {e.check}, not {check}: {e}"
        return f"{e}{lz4_note}"
    raise AssertionError(f"reader accepts a vector it must reject at step {step}")


def _verify_vector(base: dict, bins: dict, msgpack, lz4_block, xxh3_64=None) -> str:
    """Validate one legacy vector against its bin twin (popped from `bins`).

    Returns the one-line size-delta summary on success, or raises
    AssertionError/ValueError (and, on a malformed fixture entry,
    IndexError/KeyError) which verify()'s per-vector guard isolates.
    """
    old_env = bytes.fromhex(base["envelope_hex"])
    data, checksum, size, fmt, encoding = decode_envelope(old_env)

    # 1. codec fidelity against the rmp_serde-generated legacy bytes
    assert encoding == "int-array", "legacy vector not array-of-ints encoded"
    assert encode_envelope(data, checksum, size, fmt, encoding="int-array") == old_env, (
        "legacy re-encode not byte-identical"
    )
    assert len(old_env) == base["envelope_size"], "envelope_size mismatch"
    assert fmt == base["format"], "format field mismatch"
    assert size == base["input_size"], "original_size != input_size"
    # ...and against ground truth. original_size and input_size both live IN the
    # file under test, so a regeneration bug that inflates them drifts them
    # together and the line above still passes (LAB-903's lesson). input_hex is
    # the only field the pinned bytes are actually derived from, so it is the
    # one to measure against. Stdlib, and outside the optional-deps gate below,
    # so fixture self-consistency holds on both CI legs. This is NOT spec decode
    # step 9 (data.length == original_size after decompression) — that compares
    # decompressed output and only runs on the lz4 leg, as `got == inp` below.
    if size > MAX_UNCOMPRESSED_SIZE:
        # Before the compare, and before any decompression: an inflated declared
        # size must fail by name on both legs, not be sized into RAM downstream.
        raise ValueError(
            f"original_size {size} exceeds the spec's {MAX_UNCOMPRESSED_SIZE} B limit"
        )
    assert size == len(bytes.fromhex(base["input_hex"])), (
        "original_size != len(input_hex)"
    )
    edge = WIDTH_BOUNDARIES.get(base["name"])
    assert edge is None or len(data) == edge, f"compressed_data is {len(data)} B, off its {edge} B width boundary"
    # A vector the spec declares encode-divergent keeps the exact bytes mapped to its
    # name. Stdlib, and deliberately OUTSIDE the optional-deps gate below (same reason
    # as the ground-truth compare above): the set-level tripwire on the lz4 leg only
    # asserts "these bytes differ from liblz4's output", which ANY other valid LZ4
    # block satisfies — so a re-pin to unrelated bytes passed both legs. This is the
    # only encode-side enforcement the divergent vector has anywhere in the fleet;
    # cachekit-core re-encodes via lz4_flex and so cannot check it either.
    pinned_hex = LZ4_ENCODE_DIVERGENT.get(base["name"])
    assert pinned_hex is None or data.hex() == pinned_hex, (
        f"declared-divergent vector {base['name']} no longer carries its pinned "
        f"compressed_data ({data.hex()} != {pinned_hex}) — re-pin deliberately in "
        "LZ4_ENCODE_DIVERGENT and re-read spec/wire-format.md 'Compressed-byte "
        "reproducibility'"
    )

    # 2. twin equivalence
    twin = bins.pop(base["name"] + "_bin", None)
    assert twin is not None, "missing bin twin vector"
    new_env = bytes.fromhex(twin["envelope_hex"])
    assert encode_envelope(data, checksum, size, fmt, encoding="bin") == new_env, (
        "bin re-encode not byte-identical to twin"
    )
    assert new_env[0] == 0x94, "outer fixarray(4) not preserved"
    assert new_env[1] in (0xC4, 0xC5, 0xC6), "element[0] not bin-encoded"
    t_data, t_checksum, t_size, t_fmt, _t_encoding = decode_envelope(new_env)
    assert (t_data, t_checksum, t_size, t_fmt) == (data, checksum, size, fmt), (
        "twin decodes to different fields"
    )
    assert twin["input_hex"] == base["input_hex"], "twin input_hex drifted"
    assert twin["input_size"] == base["input_size"], "twin input_size drifted"
    assert twin["format"] == base["format"], "twin format drifted"
    assert len(new_env) == twin["envelope_size"], "twin envelope_size mismatch"

    # 3. documented size bound: the only pairing where bin loses is
    # bin8 (2 B) vs fixarray (1 B), i.e. compressed_data <= 15 bytes,
    # so a bin twin is never more than 1 byte larger than its legacy base.
    assert len(new_env) <= len(old_env) + 1, "bin twin exceeds +1 B header bound"

    # 4. the reader accepts both encodings and returns the input (checksum on the xxhash leg)
    inp = bytes.fromhex(base["input_hex"])
    assert read_envelope(old_env, xxh3_64) == inp, "reader does not return the legacy vector's input"
    assert read_envelope(new_env, xxh3_64) == inp, "reader does not return the bin twin's input"

    # optional: third-encoder conformance via msgpack-python
    if msgpack is not None:
        obj = msgpack.unpackb(new_env, raw=False)
        assert obj == [data, list(checksum), size, fmt], "msgpack-python bin decode mismatch"
        assert msgpack.packb([data, list(checksum), size, fmt], use_bin_type=True) == new_env, (
            "msgpack-python bin re-encode mismatch"
        )
        obj = msgpack.unpackb(old_env, raw=False)
        assert obj == [list(data), list(checksum), size, fmt], (
            "msgpack-python legacy decode mismatch"
        )
        assert msgpack.packb([list(data), list(checksum), size, fmt]) == old_env, (
            "msgpack-python legacy re-encode mismatch"
        )

    # optional: liblz4 decode conformance. Encode agreement is asserted only against
    # the declared LZ4_ENCODE_DIVERGENT set — a drift tripwire, never a per-vector
    # conformance rule; see spec 'Compressed-byte reproducibility' (LAB-1751).
    lz4_note = ""
    if lz4_block is not None:
        inp = bytes.fromhex(base["input_hex"])
        try:
            got = lz4_block.decompress(data, uncompressed_size=size)
        except (lz4_block.LZ4BlockError, OverflowError) as e:
            # convert to the guarded type so a corrupt stream fails itself, not the
            # run. MemoryError is deliberately NOT caught: it is a host signal, and
            # relabelling it as a per-vector conformance failure would hide an OOM.
            raise AssertionError(f"liblz4 rejects pinned compressed_data: {e}") from e
        assert got == inp, "liblz4 does not decompress pinned compressed_data to the input"
        theirs = lz4_block.compress(inp, store_size=False)
        diverges = theirs != data
        # Set-level half of the tripwire: WHICH vectors liblz4 fails to reproduce is a
        # spec fact, so a change either direction must fail CI. The byte-level half
        # (the pinned bytes themselves) is asserted above on both legs.
        assert diverges == (pinned_hex is not None), (
            f"liblz4 encode-divergence set changed: {base['name']} "
            f"{'now diverges from' if diverges else 'now reproduces'} the pin — "
            "update spec/wire-format.md 'Compressed-byte reproducibility' and "
            "LZ4_ENCODE_DIVERGENT together"
        )
        lz4_note = (
            f"; liblz4 decode ok, encode diverges ({len(theirs)} B vs {len(data)} B pinned — decode-verified only)"
            if diverges
            else "; liblz4 decode ok, encode reproduces pin"
        )

    delta = len(new_env) - len(old_env)
    return f"legacy {len(old_env)} B -> bin {len(new_env)} B ({delta:+d} B){lz4_note}"


def verify(require_extras: bool = False) -> int:
    fixture = _load()
    try:
        legacy, bins = _split_vectors(fixture)
    except ValueError as e:
        print(f"FAIL: unusable fixture: {e}", file=sys.stderr)
        return 1
    if not legacy:
        print("FAIL: no legacy vectors found", file=sys.stderr)
        return 1
    if fixture.get("version") != FIXTURE_VERSION:
        print(f"FAIL: fixture version {fixture.get('version')} != {FIXTURE_VERSION}", file=sys.stderr)
        return 1
    set_error = _base_set_error(legacy)
    if set_error:
        print(f"FAIL: {set_error}", file=sys.stderr)
        return 1
    # The fixture declares the bounds SDKs read; the spec table is normative. Neither
    # pinned the other, so a fixture rewriting max_uncompressed_size to 1 verified
    # green.
    declared = fixture.get("limits", {})
    drifted = sorted(k for k, v in SPEC_LIMITS.items() if declared.get(k) != v)
    if drifted:
        detail = ", ".join(f"{k}: fixture {declared.get(k)!r} != spec {SPEC_LIMITS[k]}" for k in drifted)
        print(
            f"FAIL: fixture 'limits' drifted from spec/wire-format.md 'Security Limits' — {detail}",
            file=sys.stderr,
        )
        return 1

    try:
        import msgpack  # type: ignore[import-untyped]
    except ImportError:
        msgpack = None
    try:
        import lz4.block as lz4_block  # type: ignore[import-untyped]
    except ImportError:
        lz4_block = None
    xxh3_64 = _load_xxh3()
    if require_extras and (msgpack is None or lz4_block is None or xxh3_64 is None):
        # CI's optional-deps leg passes --require-extras so a dependency drift
        # cannot silently turn the deeper conformance checks off (exit-0 with
        # a "stdlib-only" banner would be an unflagged loss of coverage).
        missing = [
            n for n, mod in (("msgpack", msgpack), ("lz4", lz4_block), ("xxhash", xxh3_64)) if mod is None
        ]
        print(f"FAIL: --require-extras set but not importable: {', '.join(missing)}", file=sys.stderr)
        return 1
    # Same whole-file doctrine as the base set: a dropped constructed vector is
    # invisible to the per-vector loop below.
    constructed = fixture.get("constructed_vectors", [])
    names = [v.get("name") for v in constructed]
    if sorted(names, key=str) != sorted(CONSTRUCTED_BUILDERS):
        print(
            f"FAIL: fixture constructed-vector set drifted — fixture {sorted(names, key=str)} != "
            f"expected {sorted(CONSTRUCTED_BUILDERS)}",
            file=sys.stderr,
        )
        return 1
    if fixture.get("construction_note") != CONSTRUCTION_NOTE:
        print("FAIL: fixture construction_note drifted from CONSTRUCTION_NOTE", file=sys.stderr)
        return 1
    rejects = fixture.get("reject_vectors", [])
    payload_rejects = fixture.get("payload_reject_vectors", [])
    temporal = fixture.get("temporal_sentinel_vectors", [])
    for label, vecs, expected in (
        ("reject", rejects, REJECT_BUILDERS),
        ("payload-reject", payload_rejects, PAYLOAD_REJECT_BUILDERS),
        ("temporal-sentinel", temporal, [f"temporal_sentinel_{k}" for k in TEMPORAL_SENTINELS]),
    ):
        got = sorted((v.get("name") for v in vecs), key=str)
        if got != sorted(expected):
            print(f"FAIL: fixture {label}-vector set drifted — fixture {got} != expected {sorted(expected)}", file=sys.stderr)
            return 1

    failures = 0
    for base in legacy:
        name = base["name"]
        try:
            print(f"  ok {name}: {_verify_vector(base, bins, msgpack, lz4_block, xxh3_64)}")
        except (AssertionError, ValueError, IndexError, KeyError) as e:
            # Per-vector isolation: a malformed vector (truncated hex, missing
            # field) fails only itself with a named FAIL line, not the whole run.
            failures += 1
            print(f"  FAIL {name}: {e!r}", file=sys.stderr)

    for orphan in bins:
        failures += 1
        print(f"  FAIL {orphan}: bin vector without a legacy base", file=sys.stderr)

    for vec in constructed:
        try:
            print(f"  ok {vec['name']}: {_verify_constructed(vec, xxh3_64, msgpack, lz4_block)}")
        except (AssertionError, ValueError, IndexError, KeyError) as e:
            failures += 1
            print(f"  FAIL {vec['name']}: {e!r}", file=sys.stderr)

    bases = {v["name"]: v for v in legacy}
    for vec in rejects:
        try:
            print(f"  ok {vec['name']}: {_verify_reject(vec, bases, xxh3_64, msgpack, lz4_block)}")
        except (AssertionError, ValueError, IndexError, KeyError) as e:
            failures += 1
            print(f"  FAIL {vec['name']}: {e!r}", file=sys.stderr)

    for vec, check in [(v, lambda v: _verify_payload_reject(v, xxh3_64, msgpack)) for v in payload_rejects] + [
        (v, _verify_temporal) for v in temporal
    ]:
        try:
            print(f"  ok {vec['name']}: {check(vec)}")
        except (AssertionError, ValueError, IndexError, KeyError, StopIteration) as e:
            failures += 1
            print(f"  FAIL {vec['name']}: {e!r}", file=sys.stderr)

    extras = [
        label
        for label, mod in (("xxHash3-64", xxh3_64), ("msgpack-python", msgpack), ("liblz4 decode", lz4_block))
        if mod
    ]
    conformance = "with " + " + ".join(extras) + " conformance" if extras else "stdlib-only, checksums unverified"
    if failures:
        print(f"FAIL: {failures} failure(s) ({conformance})", file=sys.stderr)
        return 1
    print(
        f"all {len(legacy)} vector pairs + {len(constructed)} constructed + {len(rejects)} reject + "
        f"{len(payload_rejects)} payload-reject + {len(temporal)} temporal-sentinel verified ({conformance})"
    )
    return 0


def main() -> int:
    argv = sys.argv[1:]
    require_extras = "--require-extras" in argv
    args = [a for a in argv if a != "--require-extras"]
    # Reject anything unrecognised rather than dropping it. `--require-extras` is
    # matched by exact string and it gates the deepest coverage, so a silently
    # ignored `--require-extra` typo used to exit 0 with the extras legs off —
    # the exact fail-open the flag was added to close. The arity check is what
    # closes it: the typo survives the strip above, leaving two positionals. A
    # lone unrecognised token falls through to the unknown-command exit 2 below.
    if len(args) > 1:
        print(__doc__, file=sys.stderr)
        return 2
    cmd = args[0] if args else "verify"
    if require_extras and cmd != "verify":
        # Same rule as the unrecognised-arg rejection above: a flag that is accepted
        # and ignored on the fixture-WRITING path is the fail-open this guard exists
        # to close.
        print(f"FAIL: --require-extras is not valid for '{cmd}'", file=sys.stderr)
        return 2
    if cmd == "generate":
        return generate()
    if cmd == "verify":
        return verify(require_extras=require_extras)
    print(__doc__, file=sys.stderr)
    return 2


if not __debug__:
    # Every integrity check in this file is an `assert`, so -O/-OO strips all of them:
    # `verify` reports a pass having tested nothing and `generate` rewrites the fixture
    # with its input checks gone. Module scope, not main(), because a CLI-only guard is
    # bypassed by importing this module and calling verify() directly — which the
    # regression harness's importlib probe does, and which is how the sibling tools
    # load each other's codecs (interop-v2-reference.py loads interop-reference.py by
    # spec_from_file_location). Regression-tested by tools/test_wire_format_reference.py.
    print(
        "FAIL: assertions disabled (-O / PYTHONOPTIMIZE) — this tool proves nothing",
        file=sys.stderr,
    )
    sys.exit(1)

if __name__ == "__main__":
    sys.exit(main())
