#!/usr/bin/env python3
"""Reference encoder/verifier for the ByteStorage envelope (spec/wire-format.md).

Stdlib-only (optional extras, see below). Scope: the **MessagePack encoding**
of the StorageEnvelope positional array — both the legacy element[0] encoding
(array of integers, pre-1.1 writers) and the canonical one (msgpack `bin`,
protocol 1.1+ writers). xxHash3-64 recomputation is NOT verified here (not
stdlib); byte-level enforcement for the canonical writer lives in
cachekit-core's CI (`tests/wire_format_vectors.rs`, LAB-423).

What `verify` proves, for every vector pair in ../test-vectors/wire-format.json:
  1. Codec fidelity — decoding a legacy vector and re-encoding it in legacy form
     reproduces the pinned bytes exactly. The legacy bytes were generated by
     `rmp_serde::to_vec` (cachekit-core v0.2.0), so byte-identity here proves
     this codec makes the same shortest-form header choices as rmp — which is
     what makes the derived `bin` encoding trustworthy.
  2. Twin equivalence — each `*_bin` vector decodes to field-identical contents
     as its legacy base, its element[0] carries a bin marker (0xc4/0xc5/0xc6),
     the outer fixarray(4) is preserved, and re-encoding the base's fields in
     bin form reproduces the `*_bin` bytes exactly.
  3. Documented size bound — a bin envelope is never more than 1 byte larger
     than its legacy twin (the header-arithmetic bound stated in the spec).
  4. Declared sizes match ground truth — `original_size` equals the real length
     of `input_hex`, not merely the co-located `input_size` field (both declared
     sizes live in the file under test, so they drift together).
  5. The base-vector set is exactly EXPECTED_BASE_VECTORS, and the fixture's own
     declared `limits` block matches the spec's Security Limits table. Both are
     whole-file properties: checks 1-4 iterate the fixture's vector list and so
     are structurally blind to a vector that is simply absent, or to a bound the
     fixture misdeclares to every SDK that reads it.

Usage:
    python3 tools/wire-format-reference.py verify     # default
    python3 tools/wire-format-reference.py verify --require-extras
                                                      # fail if optional deps are
                                                      # missing (CI optional-deps leg)
    python3 tools/wire-format-reference.py generate   # (re)derive *_bin vectors

Two optional-dependency checks deepen `verify` when importable (both run in CI):
  - `msgpack`: third-encoder conformance — msgpack-python re-encodes both forms
    from decoded fields and must reproduce the pinned bytes byte-identically.
  - `lz4`: C-implementation (liblz4) decode conformance — liblz4 must decompress
    every vector's pinned compressed_data to the pinned input. Encoder agreement
    is a drift tripwire against LZ4_ENCODE_DIVERGENT, never a per-vector
    conformance rule (spec 'Compressed-byte reproducibility', LAB-1751): a vector
    liblz4 reproduces must keep reproducing, and a declared-divergent vector must
    keep the exact bytes mapped to its name — "differs from liblz4" alone is a
    one-bit check that any other valid LZ4 block would satisfy.

Both commands refuse to run under -O/PYTHONOPTIMIZE: every check in this file
is an `assert`, so an optimised `verify` would report a pass having tested
nothing, and an optimised `generate` would rewrite the fixture with its input
checks stripped. The guard is at module scope, so `import` cannot skip it
either; regression-tested by tools/test_wire_format_reference.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

FIXTURE_PATH = Path(__file__).resolve().parent.parent / "test-vectors" / "wire-format.json"

FIXTURE_VERSION = "1.1.1"
# The base vectors this fixture is pinned to contain. Checked as a SET, because every
# other integrity check here iterates the fixture's own vector list and therefore
# cannot see a vector that is simply absent: dropping a legacy base AND its `_bin`
# twin together left `generate`'s append-only diff empty and `verify` reporting "all 6
# vector pairs verified", exit 0 (LAB-1751 panel round 3). Same lesson as the
# original_size/input_size drift one level up — a name list derived from the artifact
# under test pins nothing, so the expected set has to live in code.
EXPECTED_BASE_VECTORS = frozenset(
    {
        "empty",
        "simple_string",
        "binary_data",
        "large_compressible",
        "json_like",
        "single_byte",
        "width_boundary_bin16",
    }
)
# spec/wire-format.md 'Security Limits'. Pinned here so the fixture's own declared
# `limits` block cannot drift from the spec table: SDKs read their bounds from that
# block, so a fixture shipping max_uncompressed_size=1 with CI green would hand every
# downstream reader a wrong bound. `verify` compares the two. The per-vector check
# below additionally rejects an inflated declared original_size by name; note the
# ground-truth `original_size == len(input_hex)` assert would catch that case anyway,
# so this bound is about naming the spec limit that was breached, not about bounding
# an allocation. The compressed_data length cap and the 1000:1 bomb check are a
# reader's obligations, not this fixture verifier's.
SPEC_LIMITS = {
    "max_uncompressed_size": 512 * 1024 * 1024,
    "max_compressed_size": 512 * 1024 * 1024,
    "max_compression_ratio": 1000,
}
MAX_UNCOMPRESSED_SIZE = SPEC_LIMITS["max_uncompressed_size"]
# spec/wire-format.md 'Compressed-byte reproducibility' names WHICH vectors liblz4
# fails to reproduce on encode, and maps each to the bytes actually pinned. Encoder
# agreement is not a conformance rule, but the spec's claim about the set is a fact,
# so a change to it must fail CI and force the text to be re-read — otherwise the next
# `lz4==` bump rots the spec silently. The value is load-bearing: asserting only
# "these bytes differ from liblz4's output" is a one-bit check that ANY other valid
# LZ4 block satisfies, so a re-pin of the divergent vector to unrelated bytes passed
# (LAB-1751 panel round 3). Byte-pinning the divergent vector is the only encode-side
# enforcement it has anywhere in the fleet.
# Base names only: twins carry the same compressed_data and are not iterated.
LZ4_ENCODE_DIVERGENT = {"large_compressible": "1f410100ffffffe960414141414141"}
if not LZ4_ENCODE_DIVERGENT.keys() <= EXPECTED_BASE_VECTORS:
    # A phantom name here is never compared against anything in the loop below, so it
    # would leave the spec's named set wrong with CI green.
    raise SystemExit(
        "BUG: LZ4_ENCODE_DIVERGENT names vectors not in EXPECTED_BASE_VECTORS: "
        f"{', '.join(sorted(LZ4_ENCODE_DIVERGENT.keys() - EXPECTED_BASE_VECTORS))}"
    )
ENVELOPE_FORMAT = (
    "MessagePack positional array (rmp_serde::to_vec): "
    "[compressed_data, checksum, original_size, format]. Vectors without an "
    "'envelope_encoding' field use the legacy array-of-integers encoding for "
    "compressed_data and are retained forever as legacy-read proof; their "
    "'*_bin' twins use msgpack bin (canonical for protocol 1.1+ writers). "
    "checksum always encodes as an array of 8 integers. Normative rules: "
    "spec/wire-format.md, 'Byte Layout' / 'Encoding compatibility'."
)
GENERATOR = (
    "six original legacy vectors: cachekit-core v0.2.0; width_boundary_bin16 "
    "legacy vector: cachekit-core v0.5.0 real writer; *_bin vectors: "
    "tools/wire-format-reference.py generate - deterministic re-encode of the "
    "legacy fields, byte-verified against rmp-serde 1.3.1 + serde_bytes 0.11.19 "
    "output (LAB-783)"
)

# --- minimal MessagePack codec ------------------------------------------------
# Deliberately scoped to the types a StorageEnvelope uses. The encoder emits
# shortest-form headers only — the same choices rmp_serde makes — and `verify`
# proves that equivalence against the pinned legacy bytes on every run.


class _Reader:
    def __init__(self, buf: bytes):
        self.buf = buf
        self.pos = 0

    def take(self, n: int) -> bytes:
        if self.pos + n > len(self.buf):
            raise ValueError("truncated msgpack document")
        out = self.buf[self.pos : self.pos + n]
        self.pos += n
        return out

    def u8(self) -> int:
        return self.take(1)[0]

    def be(self, n: int) -> int:
        return int.from_bytes(self.take(n), "big")

    def peek(self) -> int:
        """Look at the next marker byte without consuming it (bounds-checked)."""
        if self.pos >= len(self.buf):
            raise ValueError("truncated msgpack document")
        return self.buf[self.pos]


def _decode_uint(r: _Reader) -> int:
    m = r.u8()
    if m <= 0x7F:
        return m
    if m == 0xCC:
        return r.be(1)
    if m == 0xCD:
        return r.be(2)
    if m == 0xCE:
        return r.be(4)
    raise ValueError(f"expected msgpack uint, got marker 0x{m:02x}")


def _decode_array_header(r: _Reader) -> int:
    m = r.u8()
    if 0x90 <= m <= 0x9F:
        return m & 0x0F
    if m == 0xDC:
        return r.be(2)
    if m == 0xDD:
        return r.be(4)
    raise ValueError(f"expected msgpack array, got marker 0x{m:02x}")


def _decode_str(r: _Reader) -> str:
    m = r.u8()
    if not 0xA0 <= m <= 0xBF:
        # format is a bounded registry token (e.g. "msgpack"), always fixstr.
        raise ValueError(f"expected msgpack fixstr, got marker 0x{m:02x}")
    return r.take(m & 0x1F).decode("utf-8")


def _decode_bytes_field(r: _Reader) -> tuple[bytes, str]:
    """Decode element[0]: either legacy array-of-ints or bin. Returns (data, encoding)."""
    m = r.peek()
    if m in (0xC4, 0xC5, 0xC6):
        r.u8()
        n = r.be({0xC4: 1, 0xC5: 2, 0xC6: 4}[m])
        return r.take(n), "bin"
    n = _decode_array_header(r)
    data = bytearray()
    for _ in range(n):
        v = _decode_uint(r)
        if v > 0xFF:
            raise ValueError(f"byte-array element out of range: {v}")
        data.append(v)
    return bytes(data), "int-array"


def _encode_uint(v: int) -> bytes:
    if v < 0:
        raise ValueError("negative uint")
    if v <= 0x7F:
        return bytes([v])
    if v <= 0xFF:
        return bytes([0xCC, v])
    if v <= 0xFFFF:
        return b"\xcd" + v.to_bytes(2, "big")
    if v <= 0xFFFFFFFF:
        return b"\xce" + v.to_bytes(4, "big")
    raise ValueError("uint too large for envelope fields")


def _encode_array_header(n: int) -> bytes:
    if n <= 0x0F:
        return bytes([0x90 | n])
    if n <= 0xFFFF:
        return b"\xdc" + n.to_bytes(2, "big")
    return b"\xdd" + n.to_bytes(4, "big")


def _encode_int_array(data: bytes) -> bytes:
    return _encode_array_header(len(data)) + b"".join(_encode_uint(b) for b in data)


def _encode_bin(data: bytes) -> bytes:
    n = len(data)
    if n <= 0xFF:
        return b"\xc4" + bytes([n]) + data
    if n <= 0xFFFF:
        return b"\xc5" + n.to_bytes(2, "big") + data
    return b"\xc6" + n.to_bytes(4, "big") + data


def _encode_str(s: str) -> bytes:
    raw = s.encode("utf-8")
    if len(raw) > 31:
        raise ValueError("format string too long for a fixstr registry token")
    return bytes([0xA0 | len(raw)]) + raw


# --- envelope <-> fields -------------------------------------------------------


def decode_envelope(env: bytes) -> tuple[bytes, bytes, int, str, str]:
    """Returns (compressed_data, checksum, original_size, format, element0_encoding)."""
    r = _Reader(env)
    if _decode_array_header(r) != 4:
        raise ValueError("StorageEnvelope must be a 4-element array")
    data, encoding = _decode_bytes_field(r)
    if _decode_array_header(r) != 8:
        raise ValueError("checksum must be an 8-element array")
    checksum = bytes(_decode_uint(r) for _ in range(8))
    original_size = _decode_uint(r)
    fmt = _decode_str(r)
    if r.pos != len(env):
        raise ValueError(f"{len(env) - r.pos} trailing bytes after envelope")
    return data, checksum, original_size, fmt, encoding


def encode_envelope(
    data: bytes, checksum: bytes, original_size: int, fmt: str, *, encoding: str
) -> bytes:
    element0 = _encode_bin(data) if encoding == "bin" else _encode_int_array(data)
    return (
        _encode_array_header(4)
        + element0
        + _encode_int_array(checksum)
        + _encode_uint(original_size)
        + _encode_str(fmt)
    )


# --- generate / verify ----------------------------------------------------------


def _load() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _split_vectors(fixture: dict) -> tuple[list[dict], dict[str, dict]]:
    legacy = [v for v in fixture["vectors"] if "envelope_encoding" not in v]
    bins = {v["name"]: v for v in fixture["vectors"] if v.get("envelope_encoding") == "bin"}
    # Fail closed: every vector must classify as exactly one of the two sets,
    # with no duplicate names — otherwise verify would silently skip it (and
    # generate would silently drop it from the append-only fixture). Named
    # separately, and caught by both callers, so the failure says WHICH vector
    # is unusable instead of exiting via a bare traceback.
    if len(legacy) + len(bins) != len(fixture["vectors"]):
        classified = {v["name"] for v in legacy} | set(bins)
        stray = [v["name"] for v in fixture["vectors"] if v["name"] not in classified]
        raise ValueError(
            "fixture vector(s) classify as neither legacy nor bin (envelope_encoding "
            f"must be absent or 'bin'): {', '.join(sorted(stray))}"
        )
    names = [v["name"] for v in legacy]
    if len(set(names)) != len(names):
        dupes = sorted({n for n in names if names.count(n) > 1})
        raise ValueError(f"fixture contains duplicate-named legacy vector(s): {', '.join(dupes)}")
    return legacy, bins


def _base_set_error(legacy: list[dict]) -> str | None:
    """Compare the fixture's base-vector set against EXPECTED_BASE_VECTORS.

    Absence is the one drift class every per-vector check is blind to, because they
    all iterate the fixture's own list. Returns a message, or None when the set is
    exactly as pinned.
    """
    present = {v["name"] for v in legacy}
    missing = EXPECTED_BASE_VECTORS - present
    unexpected = present - EXPECTED_BASE_VECTORS
    if not missing and not unexpected:
        return None
    parts = []
    if missing:
        parts.append(f"missing base vector(s): {', '.join(sorted(missing))}")
    if unexpected:
        parts.append(f"unexpected base vector(s): {', '.join(sorted(unexpected))}")
    return (
        f"fixture base-vector set drifted — {'; '.join(parts)}. A dropped base and its "
        "'_bin' twin are invisible to every per-vector check; add a genuinely new "
        "vector to EXPECTED_BASE_VECTORS deliberately, and never remove one."
    )


def _bin_twin(base: dict) -> dict:
    data, checksum, size, fmt, encoding = decode_envelope(bytes.fromhex(base["envelope_hex"]))
    assert encoding == "int-array", f"[{base['name']}] base vector is not legacy-encoded"
    env = encode_envelope(data, checksum, size, fmt, encoding="bin")
    twin = dict(base)  # preserves key order of the legacy vectors
    twin["name"] = base["name"] + "_bin"
    twin["description"] = (
        f"bin-encoded twin of '{base['name']}': identical fields, compressed_data "
        "as msgpack bin (canonical writer encoding, protocol 1.1+)"
    )
    twin["envelope_hex"] = env.hex()
    twin["envelope_size"] = len(env)
    twin["envelope_encoding"] = "bin"
    twin["derived_from"] = base["name"]
    return twin


def generate() -> int:
    try:
        fixture = _load()
        legacy, _ = _split_vectors(fixture)
    except ValueError as e:
        print(f"REFUSED: unusable fixture: {e}", file=sys.stderr)
        return 1
    # Refuse before the write if the base set itself has drifted. The `lost` diff below
    # is derived from the fixture on both sides, so dropping a base AND its twin
    # together nets to zero there and `generate` would happily write the shrunken
    # fixture (LAB-1751 panel round 3).
    set_error = _base_set_error(legacy)
    if set_error:
        print(f"REFUSED: {set_error}", file=sys.stderr)
        return 1
    rebuilt = legacy + [_bin_twin(v) for v in legacy]
    # Append-only, as the fixture's own contract requires (LAB-783), and the same
    # refusal the sibling python-frame-reference.py uses for its whole-fixture rebuild
    # (its upsert-by-name applies only to the single-vector append mode, LAB-1203 — do
    # not "align" this to an upsert). Rebuilding from the legacy set alone silently
    # drops any committed vector that is not a derived twin, and `verify`'s orphan FAIL
    # names `generate` as the remedy — so the repair step completes the data loss.
    # Refuse instead: this file is vendored and sha256-pinned downstream, and a
    # deletion here is invisible until an SDK's conformance coverage has already shrunk.
    lost = {v["name"] for v in fixture["vectors"]} - {v["name"] for v in rebuilt}
    if lost:
        print(
            f"REFUSED: generate would drop committed vector(s): {', '.join(sorted(lost))}. "
            "A bin vector with no legacy base is not regenerable from the legacy set — "
            "restore the missing base vector rather than regenerating.",
            file=sys.stderr,
        )
        return 1
    fixture["vectors"] = rebuilt
    fixture["envelope_format"] = ENVELOPE_FORMAT
    fixture["generator"] = GENERATOR
    fixture["version"] = FIXTURE_VERSION
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH.name}: {len(legacy)} legacy + {len(legacy)} bin vectors")
    return 0


def _verify_vector(base: dict, bins: dict, msgpack, lz4_block) -> str:
    """Validate one legacy vector against its bin twin (popped from `bins`).

    Returns the one-line size-delta summary on success, or raises
    AssertionError/ValueError (and, on a malformed fixture entry,
    IndexError/KeyError) which verify()'s per-vector guard isolates.
    """
    old_env = bytes.fromhex(base["envelope_hex"])
    data, checksum, size, fmt, encoding = decode_envelope(old_env)

    # 1. codec fidelity against the rmp_serde-generated legacy bytes
    assert encoding == "int-array", "legacy vector not array-of-ints encoded"
    assert encode_envelope(data, checksum, size, fmt, encoding="int-array") == old_env, (
        "legacy re-encode not byte-identical"
    )
    assert len(old_env) == base["envelope_size"], "envelope_size mismatch"
    assert fmt == base["format"], "format field mismatch"
    assert size == base["input_size"], "original_size != input_size"
    # ...and against ground truth. original_size and input_size both live IN the
    # file under test, so a regeneration bug that inflates them drifts them
    # together and the line above still passes (LAB-903's lesson). input_hex is
    # the only field the pinned bytes are actually derived from, so it is the
    # one to measure against. Stdlib, and outside the optional-deps gate below,
    # so fixture self-consistency holds on both CI legs. This is NOT spec decode
    # step 9 (data.length == original_size after decompression) — that compares
    # decompressed output and only runs on the lz4 leg, as `got == inp` below.
    if size > MAX_UNCOMPRESSED_SIZE:
        # Before the compare, and before any decompression: an inflated declared
        # size must fail by name on both legs, not be sized into RAM downstream.
        raise ValueError(
            f"original_size {size} exceeds the spec's {MAX_UNCOMPRESSED_SIZE} B limit"
        )
    assert size == len(bytes.fromhex(base["input_hex"])), (
        "original_size != len(input_hex)"
    )
    # A vector the spec declares encode-divergent keeps the exact bytes mapped to its
    # name. Stdlib, and deliberately OUTSIDE the optional-deps gate below (same reason
    # as the ground-truth compare above): the set-level tripwire on the lz4 leg only
    # asserts "these bytes differ from liblz4's output", which ANY other valid LZ4
    # block satisfies — so a re-pin to unrelated bytes passed both legs. This is the
    # only encode-side enforcement the divergent vector has anywhere in the fleet;
    # cachekit-core re-encodes via lz4_flex and so cannot check it either.
    pinned_hex = LZ4_ENCODE_DIVERGENT.get(base["name"])
    assert pinned_hex is None or data.hex() == pinned_hex, (
        f"declared-divergent vector {base['name']} no longer carries its pinned "
        f"compressed_data ({data.hex()} != {pinned_hex}) — re-pin deliberately in "
        "LZ4_ENCODE_DIVERGENT and re-read spec/wire-format.md 'Compressed-byte "
        "reproducibility'"
    )

    # 2. twin equivalence
    twin = bins.pop(base["name"] + "_bin", None)
    assert twin is not None, "missing bin twin vector"
    new_env = bytes.fromhex(twin["envelope_hex"])
    assert encode_envelope(data, checksum, size, fmt, encoding="bin") == new_env, (
        "bin re-encode not byte-identical to twin"
    )
    assert new_env[0] == 0x94, "outer fixarray(4) not preserved"
    assert new_env[1] in (0xC4, 0xC5, 0xC6), "element[0] not bin-encoded"
    t_data, t_checksum, t_size, t_fmt, _t_encoding = decode_envelope(new_env)
    assert (t_data, t_checksum, t_size, t_fmt) == (data, checksum, size, fmt), (
        "twin decodes to different fields"
    )
    assert twin["input_hex"] == base["input_hex"], "twin input_hex drifted"
    assert twin["input_size"] == base["input_size"], "twin input_size drifted"
    assert twin["format"] == base["format"], "twin format drifted"
    assert len(new_env) == twin["envelope_size"], "twin envelope_size mismatch"

    # 3. documented size bound: the only pairing where bin loses is
    # bin8 (2 B) vs fixarray (1 B), i.e. compressed_data <= 15 bytes,
    # so a bin twin is never more than 1 byte larger than its legacy base.
    assert len(new_env) <= len(old_env) + 1, "bin twin exceeds +1 B header bound"

    # optional: third-encoder conformance via msgpack-python
    if msgpack is not None:
        obj = msgpack.unpackb(new_env, raw=False)
        assert obj == [data, list(checksum), size, fmt], "msgpack-python bin decode mismatch"
        assert msgpack.packb([data, list(checksum), size, fmt], use_bin_type=True) == new_env, (
            "msgpack-python bin re-encode mismatch"
        )
        obj = msgpack.unpackb(old_env, raw=False)
        assert obj == [list(data), list(checksum), size, fmt], (
            "msgpack-python legacy decode mismatch"
        )
        assert msgpack.packb([list(data), list(checksum), size, fmt]) == old_env, (
            "msgpack-python legacy re-encode mismatch"
        )

    # optional: liblz4 decode conformance. Encode agreement is asserted only against
    # the declared LZ4_ENCODE_DIVERGENT set — a drift tripwire, never a per-vector
    # conformance rule; see spec 'Compressed-byte reproducibility' (LAB-1751).
    lz4_note = ""
    if lz4_block is not None:
        inp = bytes.fromhex(base["input_hex"])
        try:
            got = lz4_block.decompress(data, uncompressed_size=size)
        except (lz4_block.LZ4BlockError, OverflowError) as e:
            # convert to the guarded type so a corrupt stream fails itself, not the
            # run. MemoryError is deliberately NOT caught: it is a host signal, and
            # relabelling it as a per-vector conformance failure would hide an OOM.
            raise AssertionError(f"liblz4 rejects pinned compressed_data: {e}") from e
        assert got == inp, "liblz4 does not decompress pinned compressed_data to the input"
        theirs = lz4_block.compress(inp, store_size=False)
        diverges = theirs != data
        # Set-level half of the tripwire: WHICH vectors liblz4 fails to reproduce is a
        # spec fact, so a change either direction must fail CI. The byte-level half
        # (the pinned bytes themselves) is asserted above on both legs.
        assert diverges == (pinned_hex is not None), (
            f"liblz4 encode-divergence set changed: {base['name']} "
            f"{'now diverges from' if diverges else 'now reproduces'} the pin — "
            "update spec/wire-format.md 'Compressed-byte reproducibility' and "
            "LZ4_ENCODE_DIVERGENT together"
        )
        lz4_note = (
            f"; liblz4 decode ok, encode diverges ({len(theirs)} B vs {len(data)} B pinned — decode-verified only)"
            if diverges
            else "; liblz4 decode ok, encode reproduces pin"
        )

    delta = len(new_env) - len(old_env)
    return f"legacy {len(old_env)} B -> bin {len(new_env)} B ({delta:+d} B){lz4_note}"


def verify(require_extras: bool = False) -> int:
    fixture = _load()
    try:
        legacy, bins = _split_vectors(fixture)
    except ValueError as e:
        print(f"FAIL: unusable fixture: {e}", file=sys.stderr)
        return 1
    if not legacy:
        print("FAIL: no legacy vectors found", file=sys.stderr)
        return 1
    if fixture.get("version") != FIXTURE_VERSION:
        print(f"FAIL: fixture version {fixture.get('version')} != {FIXTURE_VERSION}", file=sys.stderr)
        return 1
    set_error = _base_set_error(legacy)
    if set_error:
        print(f"FAIL: {set_error}", file=sys.stderr)
        return 1
    # The fixture declares the bounds SDKs read; the spec table is normative. Neither
    # pinned the other, so a fixture rewriting max_uncompressed_size to 1 verified
    # green (LAB-1751 panel round 3).
    declared = fixture.get("limits", {})
    drifted = sorted(k for k, v in SPEC_LIMITS.items() if declared.get(k) != v)
    if drifted:
        detail = ", ".join(f"{k}: fixture {declared.get(k)!r} != spec {SPEC_LIMITS[k]}" for k in drifted)
        print(
            f"FAIL: fixture 'limits' drifted from spec/wire-format.md 'Security Limits' — {detail}",
            file=sys.stderr,
        )
        return 1

    try:
        import msgpack  # type: ignore[import-untyped]
    except ImportError:
        msgpack = None
    try:
        import lz4.block as lz4_block  # type: ignore[import-untyped]
    except ImportError:
        lz4_block = None
    if require_extras and (msgpack is None or lz4_block is None):
        # CI's optional-deps leg passes --require-extras so a dependency drift
        # cannot silently turn the deeper conformance checks off (exit-0 with
        # a "stdlib-only" banner would be an unflagged loss of coverage).
        missing = [n for n, mod in (("msgpack", msgpack), ("lz4", lz4_block)) if mod is None]
        print(f"FAIL: --require-extras set but not importable: {', '.join(missing)}", file=sys.stderr)
        return 1

    failures = 0
    for base in legacy:
        name = base["name"]
        try:
            print(f"  ok {name}: {_verify_vector(base, bins, msgpack, lz4_block)}")
        except (AssertionError, ValueError, IndexError, KeyError) as e:
            # Per-vector isolation: a malformed vector (truncated hex, missing
            # field) fails only itself with a named FAIL line, not the whole run.
            failures += 1
            print(f"  FAIL {name}: {e!r}", file=sys.stderr)

    for orphan in bins:
        failures += 1
        print(f"  FAIL {orphan}: bin vector without a legacy base", file=sys.stderr)

    extras = [label for label, mod in (("msgpack-python", msgpack), ("liblz4 decode", lz4_block)) if mod]
    conformance = "with " + " + ".join(extras) + " conformance" if extras else "stdlib-only"
    if failures:
        print(f"FAIL: {failures} failure(s) ({conformance})", file=sys.stderr)
        return 1
    print(f"all {len(legacy)} vector pairs verified ({conformance})")
    return 0


def main() -> int:
    argv = sys.argv[1:]
    require_extras = "--require-extras" in argv
    args = [a for a in argv if a != "--require-extras"]
    # Reject anything unrecognised rather than dropping it. `--require-extras` is
    # matched by exact string and it gates the deepest coverage, so a silently
    # ignored `--require-extra` typo used to exit 0 with the extras legs off —
    # the exact fail-open the flag was added to close. The arity check is what
    # closes it: the typo survives the strip above, leaving two positionals. A
    # lone unrecognised token falls through to the unknown-command exit 2 below.
    if len(args) > 1:
        print(__doc__, file=sys.stderr)
        return 2
    cmd = args[0] if args else "verify"
    if require_extras and cmd != "verify":
        # Same rule as the unrecognised-arg rejection above: a flag that is accepted
        # and ignored on the fixture-WRITING path is the fail-open this guard exists
        # to close.
        print(f"FAIL: --require-extras is not valid for '{cmd}'", file=sys.stderr)
        return 2
    if cmd == "generate":
        return generate()
    if cmd == "verify":
        return verify(require_extras=require_extras)
    print(__doc__, file=sys.stderr)
    return 2


if not __debug__:
    # Every integrity check in this file is an `assert`, so -O/-OO strips all of them:
    # `verify` reports a pass having tested nothing and `generate` rewrites the fixture
    # with its input checks gone. Module scope, not main(), because a CLI-only guard is
    # bypassed by importing this module and calling verify() directly — which the
    # regression harness's importlib probe does, and which is how the sibling tools
    # load each other's codecs (interop-v2-reference.py loads interop-reference.py by
    # spec_from_file_location). Regression-tested by tools/test_wire_format_reference.py.
    print(
        "FAIL: assertions disabled (-O / PYTHONOPTIMIZE) — this tool proves nothing",
        file=sys.stderr,
    )
    sys.exit(1)

if __name__ == "__main__":
    sys.exit(main())
